(() => {
'use strict';
const CFG_KEY='ptpro10_supabase_config',SESSION_KEY='ptpro10_session',INVITE_KEY='ptpro11_pending_invite',app=document.getElementById('app');
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const fieldStyle='width:100%;box-sizing:border-box;background:#182233;color:#f5f7fb;border:1px solid #2a3850;border-radius:14px;padding:14px;outline:none';
const btnStyle='width:100%;margin-top:9px;border:0;border-radius:14px;padding:13px;font-weight:850;background:linear-gradient(135deg,#7657ff,#4f7eff);color:#fff;cursor:pointer';
function renderCard(inner){app.innerHTML=`<div style="min-height:100vh;display:grid;place-items:center;padding:24px;background:#090d14;color:#f5f7fb;font-family:system-ui,-apple-system,Segoe UI,sans-serif"><div style="width:min(100%,460px);background:#121a27;border:1px solid #2a3850;border-radius:28px;padding:26px;box-shadow:0 22px 70px #0007"><div style="display:flex;align-items:center;gap:13px;margin-bottom:20px"><div style="width:58px;height:58px;border-radius:18px;background:linear-gradient(135deg,#7657ff,#477eff);display:grid;place-items:center;font-size:22px;font-weight:900">PT</div><div><b style="font-size:17px">PT-PRO</b><div style="font-size:11px;color:#91a0b7;margin-top:3px">Wellness · Sport · Performance</div></div></div>${inner}</div></div>`}
function renderLoading(text='Caricamento PT-PRO Cloud…'){renderCard(`<h1 style="margin:0 0 8px">PT-PRO Cloud</h1><p style="color:#91a0b7">${esc(text)}</p>`)}
function alertBox(message,ok=false){return message?`<div style="margin:12px 0;padding:12px;border-radius:13px;background:${ok?'#17362f':'#3a2332'};border:1px solid ${ok?'#397c68':'#8b465d'};color:${ok?'#83e6c1':'#ff7894'}">${esc(message)}</div>`:''}
function renderError(message){renderCard(`<h1 style="margin:0 0 8px">PT-PRO Cloud</h1><p style="color:#91a0b7">Errore durante il caricamento.</p>${alertBox(message)}<button id="retryCloud" style="${btnStyle}">Riprova</button>`);document.getElementById('retryCloud').onclick=boot}
function loadConfig(){try{return JSON.parse(localStorage.getItem(CFG_KEY)||'null')}catch{return null}}
function loadSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
async function fetchRuntimeConfig(){const res=await fetch('/api/config',{cache:'no-store'}),data=await res.json();if(!res.ok||!data?.url||!data?.key)throw Error(data?.error||'Configurazione Supabase non disponibile');const cfg={url:String(data.url).replace(/\/+$/,''),key:data.key};localStorage.setItem(CFG_KEY,JSON.stringify(cfg));return cfg}
async function validateOrRefresh(cfg,session){if(!session?.access_token)return null;let res=await fetch(`${cfg.url}/auth/v1/user`,{headers:{apikey:cfg.key,Authorization:`Bearer ${session.access_token}`}});if(res.ok)return session;if(!session.refresh_token)return null;res=await fetch(`${cfg.url}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:cfg.key,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})});const data=await res.json();if(!res.ok)return null;localStorage.setItem(SESSION_KEY,JSON.stringify(data));return data}
async function redeemPendingInvite(cfg,session){const code=(localStorage.getItem(INVITE_KEY)||'').trim();if(!code||!session?.access_token)return;try{const res=await fetch(`${cfg.url}/rest/v1/rpc/redeem_registration_invite`,{method:'POST',headers:{apikey:cfg.key,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({p_code:code})});if(res.ok)localStorage.removeItem(INVITE_KEY)}catch{}}
async function loadScript(src,version){return new Promise((resolve,reject)=>{if([...document.scripts].some(s=>s.src.includes('/'+src)))return resolve();const s=document.createElement('script');s.src=src+'?v='+(version||'10.0.0-rc1');s.onload=resolve;s.onerror=()=>reject(Error('Impossibile caricare '+src));document.body.appendChild(s)})}
async function loadAppScripts(){app.innerHTML='';const fallback=['app-1.js','app-2.js','app-3.js','app-4.js','app-5.js','app-6.js'],modules=Array.isArray(window.PTPRO_APP_MODULES)&&window.PTPRO_APP_MODULES.length?window.PTPRO_APP_MODULES:fallback.map(src=>({src})),version=window.PTPRO_APP_VERSION||'10.0.0-rc1',foundation=modules.filter(m=>['data','nutrition-library','nutrition-engine','core','wellness-engine','sport-library','sport-library-walking','universal-catalog','exercise-guide-library','school-academy-library','school-planner-library'].includes(m.domain)),tail=modules.filter(m=>['smart-coach-sport','lifecycle','catalog-runtime','nutrition-session','school-tools','school-academy','school-planner','bootstrap'].includes(m.domain)),features=modules.filter(m=>!foundation.includes(m)&&!tail.includes(m));for(const m of foundation)await loadScript(m.src,version);await Promise.all(features.map(m=>loadScript(m.src,version)));for(const m of tail)await loadScript(m.src,version);document.documentElement.dataset.ptproModules=String(modules.length);window.dispatchEvent(new CustomEvent('ptpro:modules-ready',{detail:modules}))}
function label(text,input){return `<label style="display:grid;gap:7px;margin:13px 0"><span style="font-size:12px;font-weight:800;color:#a9b8cf">${text}</span>${input}</label>`}
function tabs(active){return `<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:6px;padding:5px;background:#0d1521;border-radius:14px;margin-bottom:20px">${[['login','Accedi'],['signup','Registrati'],['recover','Password']].map(([k,l])=>`<button data-auth-tab="${k}" style="border:0;border-radius:10px;padding:10px 6px;background:${active===k?'#263652':'transparent'};color:${active===k?'#fff':'#91a0b7'};font-weight:800;cursor:pointer">${l}</button>`).join('')}</div>`}
function bindTabs(){document.querySelectorAll('[data-auth-tab]').forEach(b=>b.onclick=()=>renderAuth(b.dataset.authTab))}
function renderAuth(mode='login',message='',ok=false){
 if(mode==='signup')return renderSignup(message,ok);
 if(mode==='recover')return renderRecovery(message,ok);
 renderLogin(message,ok);
}
function renderLogin(message='',ok=false){renderCard(`${tabs('login')}<h1 style="margin:0 0 8px">Bentornato</h1><p style="color:#91a0b7;margin:0 0 18px">Accedi alla tua area PT-PRO.</p>${alertBox(message,ok)}<form id="cloudLoginForm">${label('Email',`<input id="cloudEmail" type="email" autocomplete="username" required style="${fieldStyle}">`)}${label('Password',`<input id="cloudPassword" type="password" autocomplete="current-password" required style="${fieldStyle}">`)}<button id="cloudLoginBtn" type="submit" style="${btnStyle}">Accedi</button></form><p style="font-size:12px;color:#91a0b7;margin-top:14px">I dati sono sincronizzati nel Cloud e separati per ogni utente.</p>`);bindTabs();document.getElementById('cloudLoginForm').onsubmit=async e=>{e.preventDefault();const btn=document.getElementById('cloudLoginBtn');btn.disabled=true;btn.textContent='Accesso…';try{const cfg=loadConfig(),res=await fetch(`${cfg.url}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:cfg.key,'Content-Type':'application/json'},body:JSON.stringify({email:document.getElementById('cloudEmail').value.trim(),password:document.getElementById('cloudPassword').value})}),data=await res.json();if(!res.ok)throw Error(data?.msg||data?.message||data?.error_description||'Accesso non riuscito');localStorage.setItem(SESSION_KEY,JSON.stringify(data));await redeemPendingInvite(cfg,data);renderLoading('Accesso riuscito. Carico PT-PRO…');await loadAppScripts()}catch(err){renderLogin(err.message)}}}
function renderSignup(message='',ok=false){renderCard(`${tabs('signup')}<h1 style="margin:0 0 8px">Crea il tuo account</h1><p style="color:#91a0b7;margin:0 0 18px">Registrati come atleta. Dopo l’accesso PT-PRO personalizzerà attività e programma.</p>${alertBox(message,ok)}<form id="cloudSignupForm">${label('Nome',`<input id="signupName" autocomplete="name" required style="${fieldStyle}">`)}${label('Email',`<input id="signupEmail" type="email" autocomplete="email" required style="${fieldStyle}">`)}${label('Password',`<input id="signupPassword" type="password" minlength="8" autocomplete="new-password" required style="${fieldStyle}">`)}${label('Codice invito (facoltativo)',`<input id="signupInvite" autocomplete="off" placeholder="Se ti ha invitato un coach/admin" style="${fieldStyle}">`)}<button id="cloudSignupBtn" type="submit" style="${btnStyle}">Registrati</button></form><p style="font-size:11px;color:#91a0b7;margin-top:14px">Se la verifica email è attiva, riceverai un messaggio di conferma prima del primo accesso.</p>`);bindTabs();document.getElementById('cloudSignupForm').onsubmit=async e=>{e.preventDefault();const btn=document.getElementById('cloudSignupBtn');btn.disabled=true;btn.textContent='Registrazione…';try{const cfg=loadConfig(),name=document.getElementById('signupName').value.trim(),email=document.getElementById('signupEmail').value.trim(),password=document.getElementById('signupPassword').value,invite=document.getElementById('signupInvite').value.trim();if(invite)localStorage.setItem(INVITE_KEY,invite);const res=await fetch(`${cfg.url}/auth/v1/signup`,{method:'POST',headers:{apikey:cfg.key,'Content-Type':'application/json'},body:JSON.stringify({email,password,data:{display_name:name,role:'athlete'},options:{emailRedirectTo:location.origin}})}),data=await res.json();if(!res.ok)throw Error(data?.msg||data?.message||data?.error_description||'Registrazione non riuscita');if(data?.access_token){localStorage.setItem(SESSION_KEY,JSON.stringify(data));await redeemPendingInvite(cfg,data);renderLoading('Account creato. Preparo il tuo profilo…');await loadAppScripts()}else renderLogin('Account creato. Controlla la tua email per confermare la registrazione.',true)}catch(err){renderSignup(err.message)}}}
function renderRecovery(message='',ok=false){renderCard(`${tabs('recover')}<h1 style="margin:0 0 8px">Recupera password</h1><p style="color:#91a0b7;margin:0 0 18px">Ti invieremo il link di recupero all’indirizzo del tuo account.</p>${alertBox(message,ok)}<form id="cloudRecoveryForm">${label('Email',`<input id="recoveryEmail" type="email" autocomplete="email" required style="${fieldStyle}">`)}<button id="recoveryBtn" type="submit" style="${btnStyle}">Invia link di recupero</button></form>`);bindTabs();document.getElementById('cloudRecoveryForm').onsubmit=async e=>{e.preventDefault();try{const cfg=loadConfig(),email=document.getElementById('recoveryEmail').value.trim(),res=await fetch(`${cfg.url}/auth/v1/recover`,{method:'POST',headers:{apikey:cfg.key,'Content-Type':'application/json'},body:JSON.stringify({email,redirect_to:location.origin})}),data=await res.json().catch(()=>({}));if(!res.ok)throw Error(data?.msg||data?.message||'Impossibile inviare il recupero');renderRecovery('Email di recupero inviata. Controlla la posta.',true)}catch(err){renderRecovery(err.message)}}}
async function boot(){renderLoading();try{const cfg=await fetchRuntimeConfig(),session=await validateOrRefresh(cfg,loadSession());if(!session){localStorage.removeItem(SESSION_KEY);renderLogin();return}await redeemPendingInvite(cfg,session);await loadAppScripts()}catch(err){renderError(err.message)}}
boot();
})();
