import fs from 'node:fs';import vm from 'node:vm';
const academy=fs.readFileSync('v10/school-academy-library.js','utf8'),planner=fs.readFileSync('v10/school-planner-library.js','utf8'),ctx={window:{},Date};vm.createContext(ctx);vm.runInContext(academy,ctx);vm.runInContext(planner,ctx);const p=ctx.window.PTPROSchoolPlanner;
if(p.grades.length!==8)throw Error(`Anni scolastici non completi: ${p.grades.length}`);if(p.periods.length!==5)throw Error('Periodi annuali incompleti');
for(const g of p.grades){if(p.sequences[g.id]?.length!==5)throw Error(`Progressione mancante: ${g.id}`);for(let i=0;i<5;i++)if(p.recommend(g.id,i).length<4)throw Error(`Consigli insufficienti: ${g.id}/${i}`)}
const runtime=fs.readFileSync('v10/school-planner-runtime.js','utf8');for(const token of ['Nuova classe','Aggiungi alunni','Presenze','Valutazione','Piano annuale','studentIds','syncCloud','schoolPlannerUpdatedAt','missingSchoolTables','app_settings','preferences','notification_settings','athlete_id:`eq.${uid()}`','Modifica classe','Elimina classe','Modifica alunno','Elimina alunno','Sincronizza ora','Cloud non ha confermato tutte le classi','Parte teorica','Parte pratica','Teoria svolta','Pratica svolta','Segna svolta','In svolgimento','completedAt','teacherNote','school_assignments','school_assignment_students','school_attendance','Privacy e dati scuola','privacyMasked','Esporta backup JSON'])if(!runtime.includes(token))throw Error(`Funzione registro mancante: ${token}`);
if(!runtime.includes('newStudentsFast')||!runtime.includes("api.post('school_students',payloads)"))throw Error('Salvataggio alunni in blocco mancante');
if(!runtime.includes('function loadDevice()')||!runtime.includes("{childList:true}")||runtime.includes("{childList:true,subtree:true}"))throw Error('Caricamento immediato o osservatore UI sicuro mancante');
const api=fs.readFileSync('v10/api.js','utf8');if(!api.includes('CLOUD_TIMEOUT')||!api.includes('15000'))throw Error('Protezione timeout Cloud mancante');
const migration=fs.readFileSync('supabase/PT-PRO_11_7_SCHOOL_REGISTER.sql','utf8');for(const token of ['school_assignments','school_assignment_students','school_attendance','school_audit_log','enable row level security','unique (student_id,attendance_on)'])if(!migration.includes(token))throw Error(`Migrazione registro incompleta: ${token}`);
console.log('School Planner OK: 8 anni, 5 periodi, classi, alunni, assegnazioni, presenze e valutazioni');
