import fs from 'node:fs';
const required=['index.html','styles.css','auth-gate.js','telemetry.js','ui-fixes.js','cloud-evolution.js','ux-unifier.js','progress-evolution.js','nutrition-evolution.js','smart-coach-evolution.js','calendar-coach-evolution.js','onboarding-evolution.js','hardening-evolution.js','manifest.webmanifest','sw.js','app-1.js','app-2.js','app-3.js','app-4.js','app-5.js','app-6.js','api/config.js','tests/rls-audit.sql'];
const missing=required.filter(f=>!fs.existsSync(f));
if(missing.length)throw new Error('File mancanti: '+missing.join(', '));
const index=fs.readFileSync('index.html','utf8');
for(const ref of ['manifest.webmanifest','auth-gate.js','ui-fixes.js','cloud-evolution.js','progress-evolution.js','nutrition-evolution.js','smart-coach-evolution.js','calendar-coach-evolution.js','onboarding-evolution.js','hardening-evolution.js'])if(!index.includes(ref))throw new Error('index.html non collega '+ref);
const auth=fs.readFileSync('auth-gate.js','utf8');
if(!auth.includes('/api/config'))throw new Error('Runtime Supabase config non attiva');
if(!auth.includes('ptpro10_session'))throw new Error('Gestione sessione mancante');
const evolution=fs.readFileSync('cloud-evolution.js','utf8');
for(const feature of ['serviceWorker','beforeinstallprompt','ptproSearchInput','weekly_checkins'])if(!evolution.includes(feature))throw new Error('Evolution feature mancante: '+feature);
const progress=fs.readFileSync('progress-evolution.js','utf8');
for(const feature of ['measurements','workout_sessions','goals','weekly_checkins','v_exercise_prs'])if(!progress.includes(feature))throw new Error('Progress feature mancante: '+feature);
const nutrition=fs.readFileSync('nutrition-evolution.js','utf8');
for(const feature of ['nutrition_plans','nutrition_days','recipes','pantry_stock','shopping_lists','supplements'])if(!nutrition.includes(feature))throw new Error('Nutrition feature mancante: '+feature);
const coach=fs.readFileSync('smart-coach-evolution.js','utf8');
for(const feature of ['Readiness','Deload','weekly_checkins','workout_sessions'])if(!coach.includes(feature))throw new Error('Coach feature mancante: '+feature);
const calendar=fs.readFileSync('calendar-coach-evolution.js','utf8');
for(const feature of ['calendar_events','notifications','coach_athletes','profiles'])if(!calendar.includes(feature))throw new Error('Calendar/coach feature mancante: '+feature);
const hardening=fs.readFileSync('hardening-evolution.js','utf8');
for(const feature of ['exportData','Blob','workout_sets','nutrition_plans','dedupeScripts'])if(!hardening.includes(feature))throw new Error('Hardening feature mancante: '+feature);
const rls=fs.readFileSync('tests/rls-audit.sql','utf8');
for(const feature of ['pg_policies','relrowsecurity','tables_without_rls'])if(!rls.includes(feature))throw new Error('RLS audit incompleto: '+feature);
const ui=fs.readFileSync('ui-fixes.js','utf8');
if(!ui.includes('UUID'))throw new Error('Protezione UUID non presente');
console.log('PT-PRO smoke test OK');
