import fs from 'node:fs';
const need=['index.html','app-manifest.js','auth-gate.js','v10/api.js','v10/kernel.js','v10/home.js','v10/workout.js','v10/progress.js','v10/nutrition.js','v10/more.js','v10/bootstrap.js','v10/styles.css','v10/features.css'];
for(const f of need){if(!fs.existsSync(f))throw new Error(`Missing ${f}`)}
const index=fs.readFileSync('index.html','utf8');
if(!index.includes('/v10/styles.css')||!index.includes('/v10/features.css'))throw new Error('v10 styles not loaded');
if(/app-[1-6]\.js|media-evolution|cloud-evolution|ux-unifier/.test(index))throw new Error('Legacy runtime still referenced by index');
const manifest=fs.readFileSync('app-manifest.js','utf8');
for(const f of ['v10/api.js','v10/kernel.js','v10/home.js','v10/workout.js','v10/progress.js','v10/nutrition.js','v10/more.js','v10/bootstrap.js'])if(!manifest.includes(f))throw new Error(`Manifest missing ${f}`);
if(/app-[1-6]\.js|v10\/app\.js/.test(manifest))throw new Error('Legacy or monolithic runtime still active');
const api=fs.readFileSync('v10/api.js','utf8');
for(const token of ['exercises','image_url','workout_items','workout_sessions','workout_sets','exercise_notes','exercise_substitutions','measurements','weekly_checkins','goals','progress_photos','nutrition_plans','nutrition_days','meals','meal_items','calendar_events','notifications','coach_athletes','coach_notes','uploadProgressPhoto'])if(!api.includes(token))throw new Error(`API missing ${token}`);
const workout=fs.readFileSync('v10/workout.js','utf8');
for(const token of ['Smart Coach','Warm-up','Sostituisci','Note','Tecnica','workout-day','exerciseMedia'])if(!workout.includes(token))throw new Error(`Workout missing ${token}`);
const progress=fs.readFileSync('v10/progress.js','utf8');
for(const token of ['Centro Progressi','Check-in','Foto progressi','Nuovo obiettivo','Nuova misura'])if(!progress.includes(token))throw new Error(`Progress missing ${token}`);
const nutrition=fs.readFileSync('v10/nutrition.js','utf8');
for(const token of ['Genera oggi','Ricette','Dispensa','Lista spesa','Integratori'])if(!nutrition.includes(token))throw new Error(`Nutrition missing ${token}`);
const more=fs.readFileSync('v10/more.js','utf8');
for(const token of ['Calendario','Notifiche','Coach','Ricerca globale','Backup','Smart Coach'])if(!more.includes(token))throw new Error(`Tools missing ${token}`);
console.log('PT-PRO v10 modular smoke: OK');