import fs from 'node:fs';
const need=['index.html','app-manifest.js','auth-gate.js','v10/api.js','v10/nutrition-engine.js','v10/kernel.js','v10/wellness-engine.js','v10/wellness.js','v10/home.js','v10/workout.js','v10/progress.js','v10/nutrition.js','v10/more.js','v10/pro.js','v10/pro-advanced.js','v10/admin-pro.js','v10/coach-engine.js','v10/appearance-pro.js','v10/support.js','v10/final-runtime.js','v10/bootstrap.js','v10/styles.css','v10/features.css','v10/pro.css','v10/layout.css','supabase/PT-PRO_11_WELLNESS_SPORT_FOUNDATION.sql'];
for(const f of need){if(!fs.existsSync(f))throw new Error(`Missing ${f}`)}
const index=fs.readFileSync('index.html','utf8');
for(const css of ['/v10/styles.css','/v10/features.css','/v10/pro.css','/v10/layout.css'])if(!index.includes(css))throw new Error(`Missing style ${css}`);
if(!index.includes('11.0.0-wellness-sport'))throw new Error('PT-PRO 11 cache release missing');
const manifest=fs.readFileSync('app-manifest.js','utf8');
for(const f of ['v10/api.js','v10/kernel.js','v10/wellness-engine.js','v10/wellness.js','v10/home.js','v10/workout.js','v10/progress.js','v10/nutrition.js','v10/coach-engine.js','v10/support.js','v10/bootstrap.js'])if(!manifest.includes(f))throw new Error(`Manifest missing ${f}`);
if(!manifest.includes('11.0.0-WELLNESS-SPORT'))throw new Error('PT-PRO 11 release missing');
const kernel=fs.readFileSync('v10/kernel.js','utf8');
for(const token of ["['wellness','✨','Attività & Sport']","['onboarding','◎','Il mio percorso']","['admin-users','♛','Utenti & Attività']","['guide','?','Guida & Tutorial']"])if(!kernel.includes(token))throw new Error(`Navigation missing ${token}`);
const auth=fs.readFileSync('auth-gate.js','utf8');
for(const token of ['Registrati','Recupera password','renderSignup','renderRecovery','redeemPendingInvite','/auth/v1/signup','/auth/v1/recover'])if(!auth.includes(token))throw new Error(`Auth missing ${token}`);
const wellness=fs.readFileSync('v10/wellness.js','utf8');
for(const token of ["A.register('wellness'","A.register('onboarding'","A.register('wellness-program'","A.register('admin-users'",'Genera programma personalizzato','registration_invites','activities'])if(!wellness.includes(token))throw new Error(`Wellness missing ${token}`);
const we=fs.readFileSync('v10/wellness-engine.js','utf8');
for(const token of ['ageBand','modifiers','prescribe','safeguards','walking','running','strength','teamSport'])if(!we.includes(token))throw new Error(`Wellness engine missing ${token}`);
const sql=fs.readFileSync('supabase/PT-PRO_11_WELLNESS_SPORT_FOUNDATION.sql','utf8');
for(const token of ['activities','user_activity_profiles','wellness_programs','wellness_program_days','wellness_program_items','activity_logs','registration_invites','ptpro_is_admin','redeem_registration_invite','Camminata','Corsa','Nuoto','Calcio','Yoga','Fitness senior'])if(!sql.includes(token))throw new Error(`Foundation SQL missing ${token}`);
const appearance=fs.readFileSync('v10/appearance-pro.js','utf8');
for(const token of ['theme_mode','app_settings','Colore principale','Dimensione testo','Densità interfaccia'])if(!appearance.includes(token))throw new Error(`Appearance missing ${token}`);
const api=fs.readFileSync('v10/api.js','utf8');
for(const token of ['activeSession','saveGoal','generateShoppingList','syncWorkoutCalendar','createSmartNotifications'])if(!api.includes(token))throw new Error(`Complete API missing ${token}`);
const workout=fs.readFileSync('v10/workout.js','utf8');
for(const token of ['Smart Coach PRO','Warm-up','Sostituisci','RPE','Nuovo PR'])if(!workout.includes(token))throw new Error(`Workout missing ${token}`);
const nutrition=fs.readFileSync('v10/nutrition.js','utf8');
for(const token of ['Nutrizione PRO','Settimana','Mese','Ricette','Dispensa','Lista spesa','Integratori'])if(!nutrition.includes(token))throw new Error(`Nutrition missing ${token}`);
const progress=fs.readFileSync('v10/progress.js','utf8');
for(const token of ['Centro Progressi PRO','Check-in','Foto progressi','PR ed e1RM'])if(!progress.includes(token))throw new Error(`Progress missing ${token}`);
const coach=fs.readFileSync('v10/coach-engine.js','utf8');
for(const token of ['Smart Coach PRO 4.0','groupedSessions','recovery','confidence'])if(!coach.includes(token))throw new Error(`Smart Coach missing ${token}`);
console.log('PT-PRO 11 Wellness & Sport smoke: OK');