import fs from 'node:fs';
const need=['index.html','app-manifest.js','auth-gate.js','v10/api.js','v10/nutrition-engine.js','v10/kernel.js','v10/home.js','v10/workout.js','v10/progress.js','v10/nutrition.js','v10/more.js','v10/pro.js','v10/bootstrap.js','v10/styles.css','v10/features.css','v10/pro.css'];
for(const f of need){if(!fs.existsSync(f))throw new Error(`Missing ${f}`)}
const index=fs.readFileSync('index.html','utf8');
for(const css of ['/v10/styles.css','/v10/features.css','/v10/pro.css'])if(!index.includes(css))throw new Error(`Missing style ${css}`);
if(/app-[1-6]\.js|media-evolution|cloud-evolution|ux-unifier/.test(index))throw new Error('Legacy runtime still referenced by index');
const manifest=fs.readFileSync('app-manifest.js','utf8');
for(const f of ['v10/api.js','v10/nutrition-engine.js','v10/kernel.js','v10/home.js','v10/workout.js','v10/progress.js','v10/nutrition.js','v10/more.js','v10/pro.js','v10/bootstrap.js'])if(!manifest.includes(f))throw new Error(`Manifest missing ${f}`);
if(/app-[1-6]\.js|v10\/app\.js/.test(manifest))throw new Error('Legacy or monolithic runtime still active');
const api=fs.readFileSync('v10/api.js','utf8');
for(const token of ['exercises','image_url','workout_items','workout_sessions','workout_sets','exercise_notes','exercise_substitutions','measurements','weekly_checkins','goals','progress_photos','nutrition_plans','nutrition_days','meals','meal_items','calendar_events','notifications','coach_athletes','coach_notes','uploadProgressPhoto'])if(!api.includes(token))throw new Error(`API missing ${token}`);
const engine=fs.readFileSync('v10/nutrition-engine.js','utf8');
for(const token of ['foods','meal_items','createNutritionDay','generateNutritionRange','protein_100','carbs_100','fat_100'])if(!engine.includes(token))throw new Error(`Nutrition engine missing ${token}`);
const workout=fs.readFileSync('v10/workout.js','utf8');
for(const token of ['Smart Coach','Warm-up','Sostituisci','Note','Tecnica','workout-day','exerciseMedia'])if(!workout.includes(token))throw new Error(`Workout missing ${token}`);
const progress=fs.readFileSync('v10/progress.js','utf8');
for(const token of ['Centro Progressi','Check-in','Foto progressi','Nuovo obiettivo','Nuova misura'])if(!progress.includes(token))throw new Error(`Progress missing ${token}`);
const nutrition=fs.readFileSync('v10/nutrition.js','utf8');
for(const token of ['Genera oggi','Ricette','Dispensa','Lista spesa','Integratori'])if(!nutrition.includes(token))throw new Error(`Nutrition missing ${token}`);
const pro=fs.readFileSync('v10/pro.js','utf8');
for(const token of ['Centro Controllo PRO','Smart Coach PRO','Report & Analytics PRO','Gestione Schede PRO','plan-builder','Planner Nutrizione PRO','Profilo PRO','Azioni rapide','Integrità dati','Cestino','Sistema'])if(!pro.includes(token))throw new Error(`PRO surface missing ${token}`);
console.log('PT-PRO 10 Cloud PRO Evolution smoke: OK');