(() => {
'use strict';
const A=window.PTAPP;
if(!A)return;
const {api,state,esc,shell,loading,toast,modal,go}=A;
const uid=()=>state.boot?.uid;
const roleLabel=r=>r==='admin'?'Admin':r==='coach'?'Coach':'Atleta';
const code=()=>`PT11-${crypto.randomUUID().replace(/-/g,'').slice(0,10).toUpperCase()}`;
async function ensureAdmin(){let me=state.boot?.profile||{};if(me.role==='admin')return me;try{await api.post('rpc/ptpro_claim_initial_admin',{})}catch{}await A.refresh();return state.boot?.profile||{}}
async function loadAdminData(){return Promise.all([
  api.get('profiles',{select:'id,display_name,first_name,last_name,role,onboarding_completed,created_at',order:'created_at.desc',limit:500}),
  api.get('registration_invites',{select:'*',order:'created_at.desc',limit:150}).catch(()=>[]),
  api.get('activities',{select:'*',order:'category.asc,name.asc',limit:500}).catch(()=>[]),
  api.get('coach_athletes',{select:'*',active:'eq.true',limit:1000}).catch(()=>[])
])}
function userName(u){return u.display_name||[u.first_name,u.last_name].filter(Boolean).join(' ')||'Utente'}
function activityRows(list){return list.map(x=>`<div class="manageRow"><div><b>${esc(x.icon||'•')} ${esc(x.name)}</b><span>${esc(x.category)} · ${x.active?'attiva':'disattiva'}</span></div><button class="btn secondary" data-toggle-activity="${x.id}" data-active="${x.active?'1':'0'}">${x.active?'Disattiva':'Attiva'}</button></div>`).join('')}
function inviteRows(inv){return inv.map(x=>`<div class="row"><span><b>${esc(x.email||'Invito senza email')}</b><small>${esc(roleLabel(x.role))} · ${esc(x.status)} · scade ${new Date(x.expires_at).toLocaleDateString('it-IT')}</small></span><b>${esc(x.invite_code)}</b></div>`).join('')||'<div class="empty">Nessun invito.</div>'}
function inviteModal(users){const coaches=users.filter(x=>x.role==='coach'||x.role==='admin');const box=modal('Nuovo invito',`<label class="field">Email facoltativa<input id="aiEmail" type="email" placeholder="utente@email.it"></label><label class="field">Ruolo<select id="aiRole"><option value="athlete">Atleta</option><option value="coach">Coach</option></select></label><label class="field" id="aiCoachWrap">Coach associato<select id="aiCoach"><option value="">Nessuno</option>${coaches.map(x=>`<option value="${x.id}">${esc(userName(x))}</option>`).join('')}</select></label><p class="muted">Gli inviti Coach possono essere creati solo dall'Admin. Gli inviti Atleta possono essere collegati a un Coach.</p><button class="btn primary full" id="aiCreate">Crea invito</button>`);const role=box.querySelector('#aiRole'),wrap=box.querySelector('#aiCoachWrap');role.onchange=()=>wrap.style.display=role.value==='athlete'?'grid':'none';box.querySelector('#aiCreate').onclick=async()=>{const r=role.value,email=box.querySelector('#aiEmail').value.trim()||null,coach=r==='athlete'?(box.querySelector('#aiCoach').value||null):null;await api.post('registration_invites',{created_by:uid(),coach_id:coach,email,role:r,invite_code:code(),status:'open'});box.remove();toast('Invito creato ✓');go('admin-users')}}
function activityModal(){const box=modal('Aggiungi attività',`<div class="formGrid"><label class="field">Nome<input id="aaName" placeholder="Es. Nordic walking"></label><label class="field">Categoria<input id="aaCategory" placeholder="cardio"></label><label class="field">Icona<input id="aaIcon" placeholder="🏃"></label><label class="field">Ambiente<input id="aaEnv" placeholder="outdoor, indoor"></label></div><label class="field">Descrizione<textarea id="aaDescription"></textarea></label><button class="btn primary full" id="aaSave">Salva attività</button>`);box.querySelector('#aaSave').onclick=async()=>{const name=box.querySelector('#aaName').value.trim(),category=box.querySelector('#aaCategory').value.trim().toLowerCase();if(!name||!category)return toast('Nome e categoria obbligatori','err');const slug=name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString(36).slice(-4),env=box.querySelector('#aaEnv').value.split(',').map(x=>x.trim()).filter(Boolean);await api.post('activities',{slug,name,category,description:box.querySelector('#aaDescription').value.trim()||null,icon:box.querySelector('#aaIcon').value.trim()||'•',environment:env,supported_goals:['wellness','fitness','maintenance'],metric_schema:{duration:true,rpe:true},active:true});box.remove();toast('Attività aggiunta ✓');go('admin-users')}}
A.register('admin-users',async()=>{state.view='admin-users';loading('Carico amministrazione…');const me=await ensureAdmin();if(me.role!=='admin')return shell('<div class="card"><h2>Area Admin</h2><p class="muted">Il profilo corrente non dispone dei permessi Admin.</p></div>');const [users,inv,activities,links]=await loadAdminData(),coaches=users.filter(x=>x.role==='coach'),athletes=users.filter(x=>x.role==='athlete');shell(`<div class="sectionHead"><div><div class="eyebrow">AMMINISTRAZIONE PT-PRO 11</div><h1>Utenti & Attività</h1><span class="muted">Ruoli protetti, inviti, Coach↔Atleta e catalogo Wellness.</span></div><button class="btn primary" id="adminInvite">+ Nuovo invito</button></div><div class="kpis four"><div class="kpi"><b>${users.length}</b><span>Utenti</span></div><div class="kpi"><b>${athletes.length}</b><span>Atleti</span></div><div class="kpi"><b>${coaches.length}</b><span>Coach</span></div><div class="kpi"><b>${links.length}</b><span>Associazioni</span></div></div><section class="section"><div class="sectionHead"><h2>Utenti</h2><span class="muted">Il tuo ruolo Admin non è modificabile da questa schermata.</span></div><div class="card list">${users.map(u=>`<div class="manageRow"><div><b>${esc(userName(u))}${u.id===uid()?' · Tu':''}</b><span>${esc(roleLabel(u.role))} · onboarding ${u.onboarding_completed?'completo':'da completare'}</span></div>${u.id===uid()?'<span class="muted">Protetto</span>':`<div class="manageButtons"><button class="btn secondary" data-role-user="${u.id}" data-role="athlete">Atleta</button><button class="btn secondary" data-role-user="${u.id}" data-role="coach">Coach</button><button class="btn secondary" data-role-user="${u.id}" data-role="admin">Admin</button></div>`}</div>`).join('')}</div></section><section class="section"><div class="sectionHead"><h2>Inviti</h2></div><div class="card list">${inviteRows(inv)}</div></section><section class="section"><div class="sectionHead"><h2>Catalogo attività</h2><button class="btn secondary" id="adminAddActivity">+ Attività</button></div><div class="card list">${activityRows(activities)}</div></section>`);A.bindRoutes();document.getElementById('adminInvite').onclick=()=>inviteModal(users);document.getElementById('adminAddActivity').onclick=activityModal;document.querySelectorAll('[data-role-user]').forEach(b=>b.onclick=async()=>{if(b.dataset.roleUser===uid())return toast('Il tuo ruolo Admin è protetto','err');await api.patch('profiles',{id:`eq.${b.dataset.roleUser}`},{role:b.dataset.role});toast(`Ruolo aggiornato: ${roleLabel(b.dataset.role)} ✓`);go('admin-users')});document.querySelectorAll('[data-toggle-activity]').forEach(b=>b.onclick=async()=>{await api.patch('activities',{id:`eq.${b.dataset.toggleActivity}`},{active:b.dataset.active!=='1'});toast('Catalogo aggiornato ✓');go('admin-users')})});
})();