(() => {
'use strict';
const CFG='ptpro10_supabase_config',SES='ptpro10_session';
const config=()=>{try{return JSON.parse(localStorage.getItem(CFG)||'null')}catch{return null}};
const session=()=>{try{return JSON.parse(localStorage.getItem(SES)||'null')}catch{return null}};
let refreshing=null;
async function refreshAccess(){if(refreshing)return refreshing;const c=config(),s=session();if(!c?.url||!c?.key||!s?.refresh_token)throw Error('Sessione scaduta: accedi di nuovo');refreshing=fetch(`${c.url}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:c.key,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:s.refresh_token})}).then(async r=>{const data=await r.json();if(!r.ok||!data?.access_token)throw Error('Sessione scaduta: accedi di nuovo');localStorage.setItem(SES,JSON.stringify(data));window.dispatchEvent(new CustomEvent('ptpro:session-refreshed'));return data}).finally(()=>{refreshing=null});return refreshing}
async function request(path,{method='GET',body,headers={},raw=false}={}){const c=config(),s=session();if(!c?.url||!c?.key)throw Error('Configurazione Cloud mancante');if(!s?.access_token)throw Error('Sessione scaduta: accedi di nuovo');const h={apikey:c.key,Authorization:`Bearer ${s.access_token}`,Accept:'application/json',...headers};if(body!==undefined&&!raw)h['Content-Type']='application/json';let r;try{r=await fetch(c.url+path,{method,headers:h,body:body===undefined?undefined:(raw?body:JSON.stringify(body))})}catch{const error=Error('Connessione al Cloud non disponibile. Controlla la rete e riprova.');window.dispatchEvent(new CustomEvent('ptpro:api-error',{detail:{path,method,status:0,message:error.message}}));throw error}const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok){const technical=data?.message||data?.hint||data?.error_description||data?.error||`Errore ${r.status}`,friendly=r.status===401?'Sessione scaduta: accedi di nuovo':r.status===403?'Operazione non autorizzata per questo account':r.status===404?'Dati richiesti non disponibili':r.status>=500?'Servizio Cloud temporaneamente non disponibile':technical,error=Error(friendly);error.status=r.status;error.technical=technical;window.dispatchEvent(new CustomEvent('ptpro:api-error',{detail:{path,method,status:r.status,message:friendly}}));console.error('[PT-PRO API]',method,path,r.status,technical);throw error}return data}
const qs=o=>{const q=new URLSearchParams();Object.entries(o||{}).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')q.set(k,String(v))});return q.toString()};
function timed(promise,ms=15000){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{const e=Error('Il Cloud sta impiegando troppo tempo. I dati gia salvati restano disponibili: riprova tra poco.');e.code='CLOUD_TIMEOUT';reject(e)},ms);Promise.resolve(promise).then(value=>{clearTimeout(timer);resolve(value)},error=>{clearTimeout(timer);reject(error)})})}
async function authedRequest(path,options){try{return await timed(request(path,options))}catch(e){if(e.status!==401)throw e;await timed(refreshAccess());return timed(request(path,options))}}
const get=(t,p={})=>authedRequest(`/rest/v1/${t}?${qs(p)}`),post=(t,b)=>authedRequest(`/rest/v1/${t}`,{method:'POST',body:b,headers:{Prefer:'return=representation'}}),patch=(t,f,b)=>authedRequest(`/rest/v1/${t}?${qs(f)}`,{method:'PATCH',body:b,headers:{Prefer:'return=representation'}}),del=(t,f)=>authedRequest(`/rest/v1/${t}?${qs(f)}`,{method:'DELETE',headers:{Prefer:'return=representation'}});
async function user(){return authedRequest('/auth/v1/user')}
async function bootstrap(){const u=await user(),uid=u.id;const [profiles,plans,measures,sessions,checkins,goals,events,notifications,prefs]=await Promise.all([get('profiles',{select:'*',id:`eq.${uid}`,limit:1}),get('workout_plans',{select:'*',athlete_id:`eq.${uid}`,archived_at:'is.null',order:'active.desc,created_at.desc'}),get('measurements',{select:'*',athlete_id:`eq.${uid}`,order:'measured_on.desc',limit:30}),get('workout_sessions',{select:'*',athlete_id:`eq.${uid}`,order:'started_at.desc',limit:80}),get('weekly_checkins',{select:'*',athlete_id:`eq.${uid}`,order:'checkin_date.desc',limit:12}).catch(()=>[]),get('goals',{select:'*',athlete_id:`eq.${uid}`,order:'created_at.desc',limit:30}).catch(()=>[]),get('calendar_events',{select:'*',athlete_id:`eq.${uid}`,order:'starts_at.asc',limit:100}).catch(()=>[]),get('notifications',{select:'*',athlete_id:`eq.${uid}`,archived_at:'is.null',order:'created_at.desc',limit:100}).catch(()=>[]),get('user_preferences',{select:'*',athlete_id:`eq.${uid}`,limit:1}).catch(()=>[])]);const plan=plans.find(x=>x.active)||plans[0]||null;const days=plan?await get('workout_days',{select:'*',plan_id:`eq.${plan.id}`,archived_at:'is.null',order:'sort_order.asc'}):[];const activeSession=sessions.find(x=>!x.ended_at)||null;return {uid,user:u,profile:profiles[0]||{},plan,plans,days,measures,sessions,checkins,goals,events,notifications,prefs:prefs[0]||{},activeSession}}
async function workout(dayId){const [days,items]=await Promise.all([get('workout_days',{select:'*',id:`eq.${dayId}`,limit:1}),get('workout_items',{select:'*',day_id:`eq.${dayId}`,archived_at:'is.null',order:'sort_order.asc'})]);const day=days[0];if(!day)throw Error('Giorno non trovato');const ids=[...new Set(items.map(x=>x.exercise_id).filter(Boolean))];const exercises=ids.length?await get('exercises',{select:'id,legacy_id,name,muscle_group,equipment,description,technique,image_url,video_url,tags',id:`in.(${ids.join(',')})`}):[];const notes=ids.length?await get('exercise_notes',{select:'*',athlete_id:`eq.${day.athlete_id}`,exercise_id:`in.(${ids.join(',')})`}).catch(()=>[]):[];const targets=items.length?await get('workout_item_set_targets',{select:'*',workout_item_id:`in.(${items.map(x=>x.id).join(',')})`,order:'set_index.asc'}).catch(()=>[]):[];const em=new Map(exercises.map(e=>[e.id,e])),nm=new Map(notes.map(n=>[n.exercise_id,n])),tm=new Map();for(const t of targets){if(!tm.has(t.workout_item_id))tm.set(t.workout_item_id,[]);tm.get(t.workout_item_id).push(t)}return {day,items:items.map(i=>({...i,exercise:em.get(i.exercise_id)||null,exercise_note:nm.get(i.exercise_id)||null,set_targets:tm.get(i.id)||[]}))}}
async function exerciseCatalog(){return get('exercises',{select:'id,legacy_id,name,muscle_group,equipment,description,technique,image_url,video_url,tags,active',active:'eq.true',order:'name.asc'})}
async function previousSets(uid,exerciseId,limit=50){return get('workout_sets',{select:'*',athlete_id:`eq.${uid}`,exercise_id:`eq.${exerciseId}`,order:'logged_at.desc',limit})}
async function startSession(uid,planId,dayId,count,readiness){const active=await get('workout_sessions',{select:'*',athlete_id:`eq.${uid}`,day_id:`eq.${dayId}`,ended_at:'is.null',order:'started_at.desc',limit:1}).catch(()=>[]);if(active.length)return active[0];const r=await post('workout_sessions',{athlete_id:uid,plan_id:planId||null,day_id:dayId,planned_exercises:count||0,readiness_score:readiness??null});return r?.[0]}
async function activeSession(uid){const r=await get('workout_sessions',{select:'*',athlete_id:`eq.${uid}`,ended_at:'is.null',order:'started_at.desc',limit:1}).catch(()=>[]);return r[0]||null}
async function sessionSets(sessionId){return get('workout_sets',{select:'*',session_id:`eq.${sessionId}`,order:'logged_at.asc'}).catch(()=>[])}
async function saveSet(payload){const old=await get('workout_sets',{select:'id',session_id:`eq.${payload.session_id}`,workout_item_id:`eq.${payload.workout_item_id}`,set_index:`eq.${payload.set_index}`,limit:1}).catch(()=>[]);if(old.length){const r=await patch('workout_sets',{id:`eq.${old[0].id}`},payload);return r?.[0]}const r=await post('workout_sets',payload);return r?.[0]}
async function finishSession(id,payload){const r=await patch('workout_sessions',{id:`eq.${id}`},payload);return r?.[0]}
async function saveExerciseNote(uid,exerciseId,note){const old=await get('exercise_notes',{select:'id',athlete_id:`eq.${uid}`,exercise_id:`eq.${exerciseId}`,limit:1});return old.length?patch('exercise_notes',{id:`eq.${old[0].id}`},note):post('exercise_notes',{athlete_id:uid,exercise_id:exerciseId,note})}
async function substitute(uid,sessionId,itemId,fromId,toId,reason='',applyToPlan=false){if(applyToPlan)await patch('workout_items',{id:`eq.${itemId}`},{exercise_id:toId});return post('exercise_substitutions',{athlete_id:uid,session_id:sessionId||null,workout_item_id:itemId,from_exercise_id:fromId,to_exercise_id:toId,reason,apply_to_plan:!!applyToPlan})}
async function progress(uid){const [measures,goals,checkins,photos,prs,volumes]=await Promise.all([get('measurements',{select:'*',athlete_id:`eq.${uid}`,order:'measured_on.desc',limit:120}),get('goals',{select:'*',athlete_id:`eq.${uid}`,order:'created_at.desc',limit:100}),get('weekly_checkins',{select:'*',athlete_id:`eq.${uid}`,order:'checkin_date.desc',limit:52}),get('progress_photos',{select:'*',athlete_id:`eq.${uid}`,order:'photo_date.desc',limit:100}).catch(()=>[]),get('v_exercise_prs',{select:'*',athlete_id:`eq.${uid}`,limit:200}).catch(()=>[]),get('v_weekly_training_volume',{select:'*',athlete_id:`eq.${uid}`,order:'week_start.desc',limit:52}).catch(()=>[])]);const ids=[...new Set(prs.map(x=>x.exercise_id).filter(Boolean))],ex=ids.length?await get('exercises',{select:'id,name,muscle_group',id:`in.(${ids.join(',')})`}).catch(()=>[]):[],em=new Map(ex.map(x=>[x.id,x]));return {measures,goals,checkins,photos,prs:prs.map(x=>({...x,exercise_name:em.get(x.exercise_id)?.name||'Esercizio',muscle_group:em.get(x.exercise_id)?.muscle_group||''})),volumes}}
async function saveGoal(uid,data){if(data.id)return patch('goals',{id:`eq.${data.id}`},{...data,id:undefined});return post('goals',{athlete_id:uid,...data})}
async function saveMeasurement(uid,data){if(data.id)return patch('measurements',{id:`eq.${data.id}`},{...data,id:undefined});return post('measurements',{athlete_id:uid,...data})}
async function ensureNutritionPlan(uid){
 const plans=await get('nutrition_plans',{select:'*',athlete_id:`eq.${uid}`,order:'active.desc,created_at.desc'}),active=plans.find(x=>x.active);if(active)return active;
 if(plans.length){const updated=await patch('nutrition_plans',{id:`eq.${plans[0].id}`},{active:true});return updated?.[0]||{...plans[0],active:true}}
 const measures=await get('measurements',{select:'weight_kg',athlete_id:`eq.${uid}`,order:'measured_on.desc',limit:1}).catch(()=>[]),weight=Number(measures[0]?.weight_kg),kg=Number.isFinite(weight)&&weight>=35&&weight<=250?weight:75,kcal=Math.round(Math.max(1600,Math.min(3400,kg*30))/50)*50,protein=Math.round(kg*1.6),fat=Math.round(kg*.8),carbs=Math.max(130,Math.round((kcal-protein*4-fat*9)/4));
 const created=await post('nutrition_plans',{athlete_id:uid,title:'Piano Smart iniziale',kcal_target:kcal,protein_g_target:protein,carbs_g_target:carbs,fat_g_target:fat,goal:'Benessere e composizione corporea',notes:'Creato automaticamente da PT-PRO. Personalizza i target nella sezione Piano.',active:true});return created?.[0]
}
async function nutrition(uid){const plan=await ensureNutritionPlan(uid),[plans,days,recipes,pantry,lists,supp,logs,prefs,subs,foods]=await Promise.all([get('nutrition_plans',{select:'*',athlete_id:`eq.${uid}`,order:'active.desc,created_at.desc'}).catch(()=>plan?[plan]:[]),get('nutrition_days',{select:'*',athlete_id:`eq.${uid}`,order:'day_date.desc',limit:62}).catch(()=>[]),get('recipes',{select:'*',limit:300}).catch(()=>[]),get('pantry_stock',{select:'*',athlete_id:`eq.${uid}`,order:'created_at.desc',limit:300}).catch(()=>[]),get('shopping_lists',{select:'*',athlete_id:`eq.${uid}`,order:'created_at.desc',limit:60}).catch(()=>[]),get('supplements',{select:'*',order:'name.asc',limit:150}).catch(()=>[]),get('supplement_logs',{select:'*',athlete_id:`eq.${uid}`,order:'logged_at.desc',limit:200}).catch(()=>[]),get('food_preferences',{select:'*',athlete_id:`eq.${uid}`,limit:300}).catch(()=>[]),get('food_substitutions',{select:'*',athlete_id:`eq.${uid}`,limit:300}).catch(()=>[]),get('foods',{select:'*',active:'eq.true',order:'name.asc',limit:1000}).catch(()=>[])]);return {plans,days,recipes,pantry,lists,supp,logs,prefs,subs,foods}}
async function nutritionDay(uid,date){const ds=await get('nutrition_days',{select:'*',athlete_id:`eq.${uid}`,day_date:`eq.${date}`,limit:1});if(!ds.length)return {day:null,meals:[]};const day=ds[0],meals=await get('meals',{select:'*',nutrition_day_id:`eq.${day.id}`,order:'sort_order.asc'});for(const m of meals)m.items=await get('meal_items',{select:'*',meal_id:`eq.${m.id}`,order:'created_at.asc'});return {day,meals}}
async function createNutritionDay(uid,plan,date,dayType='AUTO'){const old=await get('nutrition_days',{select:'id',athlete_id:`eq.${uid}`,day_date:`eq.${date}`,limit:1});if(old.length)await del('nutrition_days',{id:`eq.${old[0].id}`});const d=(await post('nutrition_days',{athlete_id:uid,plan_id:plan?.id||null,day_date:date,day_type:dayType,kcal:plan?.kcal_target||0,protein_g:plan?.protein_g_target||0,carbs_g:plan?.carbs_g_target||0,fat_g:plan?.fat_g_target||0,advice:'Giornata generata da PT-PRO Cloud'}))[0];const mealNames=['Colazione','Pranzo','Spuntino','Cena'];const ratios=[.25,.35,.15,.25];for(let i=0;i<mealNames.length;i++)await post('meals',{athlete_id:uid,nutrition_day_id:d.id,nutrition_plan_id:plan?.id||null,name:mealNames[i],sort_order:i+1,kcal:Number(d.kcal||0)*ratios[i],protein_g:Number(d.protein_g||0)*ratios[i],carbs_g:Number(d.carbs_g||0)*ratios[i],fat_g:Number(d.fat_g||0)*ratios[i]});return d}
async function setFoodPreference(uid,foodId,status){const old=await get('food_preferences',{select:'id',athlete_id:`eq.${uid}`,food_id:`eq.${foodId}`,limit:1}).catch(()=>[]);if(old.length)return patch('food_preferences',{id:`eq.${old[0].id}`},{preference:status});return post('food_preferences',{athlete_id:uid,food_id:foodId,preference:status})}
async function mealAlternatives(uid,foodId,limit=20){const foods=await get('foods',{select:'*',active:'eq.true',order:'name.asc',limit:1000}),base=foods.find(x=>x.id===foodId);if(!base)return [];return foods.filter(x=>x.id!==foodId).map(x=>{const kcal=Math.abs(Number(x.kcal_100||0)-Number(base.kcal_100||0)),p=Math.abs(Number(x.protein_100||0)-Number(base.protein_100||0)),c=Math.abs(Number(x.carbs_100||0)-Number(base.carbs_100||0)),f=Math.abs(Number(x.fat_100||0)-Number(base.fat_100||0));return {...x,match_score:Math.max(0,100-(kcal*.25+p*2+c*.7+f*1.2))}}).sort((a,b)=>b.match_score-a.match_score).slice(0,limit)}
async function generateShoppingList(uid,planId,weekStart){const days=await get('nutrition_days',{select:'id,day_date',athlete_id:`eq.${uid}`,plan_id:`eq.${planId}`,day_date:`gte.${weekStart}`,order:'day_date.asc',limit:7}).catch(()=>[]);const mealIds=[];for(const d of days){const ms=await get('meals',{select:'id',nutrition_day_id:`eq.${d.id}`}).catch(()=>[]);mealIds.push(...ms.map(x=>x.id))}const all=[];for(const id of mealIds){const its=await get('meal_items',{select:'*',meal_id:`eq.${id}`}).catch(()=>[]);all.push(...its)}const pantry=await get('pantry_stock',{select:'*',athlete_id:`eq.${uid}`}).catch(()=>[]),stock=new Map(pantry.map(x=>[x.food_id||x.name,Number(x.quantity||0)])),agg=new Map();for(const x of all){const k=x.food_id||x.food_name_snapshot;if(!k)continue;const v=agg.get(k)||{food_id:x.food_id||null,name:x.food_name_snapshot||'Alimento',quantity:0,unit:x.unit||'g'};v.quantity+=Number(x.quantity||0);agg.set(k,v)}const list=(await post('shopping_lists',{athlete_id:uid,week_start:weekStart,title:`Spesa · ${weekStart}`,status:'open',generated_from_plan_id:planId}))[0];for(const v of agg.values()){const have=stock.get(v.food_id||v.name)||0,final=Math.max(0,v.quantity-have);if(final>0)await post('shopping_list_items',{athlete_id:uid,shopping_list_id:list.id,food_id:v.food_id,name:v.name,quantity:v.quantity,unit:v.unit,pantry_quantity:have,final_quantity:final,checked:false})}return list}
async function calendar(uid){return get('calendar_events',{select:'*',athlete_id:`eq.${uid}`,order:'starts_at.asc',limit:200})}
async function syncWorkoutCalendar(uid,session,day){if(!session?.id||!day)return null;const key=`workout:${session.id}`,old=await get('calendar_events',{select:'id',athlete_id:`eq.${uid}`,notes:`eq.${key}`,limit:1}).catch(()=>[]),payload={athlete_id:uid,title:`Allenamento · ${day.name||'Workout'}`,starts_at:session.started_at||new Date().toISOString(),ends_at:session.ended_at||new Date().toISOString(),all_day:false,event_type:'workout',notes:key,related_plan_id:day.plan_id||null,related_day_id:day.id||null};return old.length?patch('calendar_events',{id:`eq.${old[0].id}`},payload):post('calendar_events',payload)}
async function createSmartNotifications(uid,boot){const out=[],today=new Date().toISOString().slice(0,10),check=boot?.checkins?.[0];if(check&&Number(check.recovery_score)<55)out.push({priority:'high',notification_type:'recovery',title:'Recupero basso',body:'Smart Coach consiglia di ridurre volume o intensità oggi.',dedupe_key:`recovery:${today}`});const goals=(boot?.goals||[]).filter(x=>x.status==='active'&&x.target_date&&x.target_date<=today);if(goals.length)out.push({priority:'medium',notification_type:'goal',title:'Obiettivi da aggiornare',body:`${goals.length} obiettivi hanno raggiunto la data target.`,dedupe_key:`goals:${today}`});for(const n of out){const old=await get('notifications',{select:'id',athlete_id:`eq.${uid}`,dedupe_key:`eq.${n.dedupe_key}`,limit:1}).catch(()=>[]);if(!old.length)await post('notifications',{athlete_id:uid,...n})}return out}
async function coach(uid){const links=await get('coach_athletes',{select:'*',coach_id:`eq.${uid}`,active:'eq.true'}).catch(()=>[]);if(!links.length)return {links,profiles:[],notes:[]};const ids=links.map(x=>x.athlete_id);const profiles=await get('profiles',{select:'id,display_name,first_name,last_name,role',id:`in.(${ids.join(',')})`}).catch(()=>[]);const notes=await get('coach_notes',{select:'*',coach_id:`eq.${uid}`,order:'created_at.desc',limit:200}).catch(()=>[]);return {links,profiles,notes}}
async function uploadProgressPhoto(uid,file,type='front'){const c=config(),path=`progress/${uid}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;await request(`/storage/v1/object/exercise-media/${path}`,{method:'POST',body:file,raw:true,headers:{'Content-Type':file.type||'image/jpeg','x-upsert':'true'}});const publicUrl=`${c.url}/storage/v1/object/public/exercise-media/${path}`;return (await post('progress_photos',{athlete_id:uid,photo_date:new Date().toISOString().slice(0,10),photo_type:type,storage_path:path,public_url:publicUrl}))[0]}
async function techLog(uid,level,area,message,details={}){try{return await post('tech_logs',{athlete_id:uid||null,level,area,message,details,app_version:window.PTPRO_APP_VERSION||'PT-PRO-10',user_agent:navigator.userAgent})}catch{return null}}
window.PTAPI={request,get,post,patch,del,user,bootstrap,workout,exerciseCatalog,previousSets,startSession,activeSession,sessionSets,saveSet,finishSession,saveExerciseNote,substitute,progress,saveGoal,saveMeasurement,ensureNutritionPlan,nutrition,nutritionDay,createNutritionDay,setFoodPreference,mealAlternatives,generateShoppingList,calendar,syncWorkoutCalendar,createSmartNotifications,coach,uploadProgressPhoto,techLog};
})();
