(() => {
'use strict';
const api=window.PTAPI, app=document.getElementById('app');
const state={boot:null,view:'home',workout:null,session:null,startedAt:null,catalog:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toLocaleString('it-IT',{maximumFractionDigits:d}):'—';
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}
function top(){return `<div class="top"><div class="brand"><div class="logo"></div><div><b>PT-PRO</b><span>Smart Performance</span></div></div><div class="muted">Cloud</div></div>`}
function nav(){return `<nav class="bottom">${[['home','⌂','Home'],['workout','🏋️','Workout'],['progress','↗','Progressi'],['nutrition','🥗','Nutrizione'],['more','☰','Altro']].map(([v,i,l])=>`<button data-nav="${v}" class="${state.view===v?'active':''}"><b>${i}</b>${l}</button>`).join('')}</nav>`}
function shell(content){app.innerHTML=`<main class="app">${top()}${content}</main>${nav()}`;document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>go(b.dataset.nav))}
function loading(t='Caricamento…'){app.innerHTML=`<main class="app">${top()}<div class="loading">${esc(t)}</div></main>`}
function failure(e){shell(`<div class="card"><h2>Errore</h2><div class="error">${esc(e.message||e)}</div></div>`)}
function readiness(){const c=state.boot.checkins?.[0]||{};const vals=[c.recovery_score,c.sleep_score,c.energy_score].map(Number).filter(Number.isFinite);return vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):70}
async function home(){state.view='home';const b=state.boot,p=b.profile||{},plan=b.plan,days=b.days||[],sessions=b.sessions||[],measures=b.measures||[];const now=Date.now(),week=sessions.filter(s=>now-new Date(s.started_at).getTime()<7*864e5);const mins=week.reduce((a,s)=>a+Number(s.duration_minutes||0),0);const last=measures[0];const next=days[0];const ready=readiness();shell(`<section class="hero"><div class="card"><div class="eyebrow">${new Date().toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long'})}</div><h1>Ciao ${esc(p.display_name||p.first_name||'Vincenzo')}.</h1><p class="muted">${plan?`Scheda attiva: <b>${esc(plan.title)}</b>`:'Nessuna scheda attiva'}</p>${next?`<button class="btn primary full" id="startToday">▶ Inizia ${esc(next.name)}</button>`:''}</div><div class="kpis"><div class="kpi"><b>${week.length}</b><span>Allenamenti settimana</span></div><div class="kpi"><b>${last?.weight_kg?fmt(last.weight_kg)+' kg':'—'}</b><span>Peso</span></div><div class="kpi"><b>${ready}%</b><span>Prontezza</span></div><div class="kpi"><b>${mins}′</b><span>Minuti settimana</span></div></div></section><section class="section"><div class="sectionHead"><h2>Smart Coach</h2><span class="muted">dai tuoi dati</span></div><div class="coach"><b>${ready<55?'Recupero prioritario':ready<70?'Fatica moderata':'Pronto ad allenarti'}</b><p>${ready<55?'Riduci volume e intensità, evita il cedimento e cura il recupero.':ready<70?'Mantieni margine tecnico e valuta la risposta nei primi set.':'Programmazione regolare: puoi cercare una progressione controllata.'}</p></div></section><section class="section"><div class="sectionHead"><h2>Allenamenti</h2><span class="muted">${days.length} giorni</span></div><div class="dayGrid">${days.map(d=>`<button class="dayCard" data-day="${d.id}"><div><b>${esc(d.name)}</b><span>${esc(d.focus||'')}</span></div></button>`).join('')||'<div class="card empty">Nessun giorno programmato.</div>'}</div></section>`);document.querySelectorAll('[data-day]').forEach(x=>x.onclick=()=>openWorkout(x.dataset.day));if(document.getElementById('startToday'))document.getElementById('startToday').onclick=()=>openWorkout(next.id)}
async function workoutList(){state.view='workout';const days=state.boot.days||[];shell(`<div class="sectionHead"><div><div class="eyebrow">Scheda attiva</div><h1>${esc(state.boot.plan?.title||'Workout')}</h1></div><button class="btn secondary" id="exerciseLib">Esercizi</button></div><div class="dayGrid">${days.map(d=>`<button class="dayCard" data-day="${d.id}"><div><b>${esc(d.name)}</b><span>${esc(d.focus||'')}</span></div></button>`).join('')}</div>`);document.querySelectorAll('[data-day]').forEach(x=>x.onclick=()=>openWorkout(x.dataset.day));document.getElementById('exerciseLib').onclick=exerciseLibrary}
async function openWorkout(dayId){loading('Carico workout…');try{state.view='workout';state.workout=await api.workout(dayId);state.session=null;state.startedAt=null;await renderWorkout()}catch(e){failure(e)}}
async function renderWorkout(){const {day,items}=state.workout;const uid=state.boot.uid;const prev=await Promise.all(items.map(i=>api.previousSets(uid,i.exercise_id).catch(()=>[])));shell(`<div class="workoutHeader"><div><div class="eyebrow">${esc(day.focus||'Allenamento')}</div><h1>${esc(day.name)}</h1></div>${state.session?'<button class="btn danger" id="finish">Termina</button>':'<button class="btn primary" id="begin">Inizia</button>'}</div>${items.map((it,idx)=>{const e=it.exercise||{},last=prev[idx]||[];return `<details class="workoutExercise" open><summary><div class="exTitle">${e.image_url?`<img class="thumb" loading="lazy" src="${esc(e.image_url)}" alt="${esc(e.name)}">`:'<div class="thumb"></div>'}<div><div class="exName">${idx+1}. ${esc(e.name||'Esercizio')}</div><div class="exMeta">${esc(e.muscle_group||'')}${it.reps_text?' · '+esc(it.reps_text)+' rep':''}${it.rest_seconds?' · '+it.rest_seconds+' sec':''}</div></div></div><span class="muted">${it.sets} set</span></summary>${e.image_url?`<div class="exerciseMedia"><img loading="lazy" src="${esc(e.image_url)}" alt="${esc(e.name)}"></div>`:''}<div class="sets"><div class="setHead"><span>#</span><span>KG</span><span>REP</span><span>RIR</span><span>PREC.</span></div>${Array.from({length:it.sets||3},(_,s)=>{const p=last[s];return `<div class="setRow" data-item="${it.id}" data-ex="${it.exercise_id}" data-name="${esc(e.name||'Esercizio')}" data-set="${s+1}"><b>${s+1}</b><input inputmode="decimal" data-load placeholder="kg"><input inputmode="numeric" data-reps placeholder="rep"><input inputmode="decimal" data-rir placeholder="RIR"><button data-save title="${p?`${fmt(p.load)} kg × ${p.reps}`:'Nessun precedente'}">${p?fmt(p.load,0):'✓'}</button></div>`}).join('')}</div></details>`}).join('')}`);if(document.getElementById('begin'))document.getElementById('begin').onclick=startWorkout;if(document.getElementById('finish'))document.getElementById('finish').onclick=finishWorkout;document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>saveRow(b.closest('.setRow')))}
async function startWorkout(){try{const {day,items}=state.workout;state.session=await api.startSession(state.boot.uid,day.plan_id,day.id,items.length);state.startedAt=Date.now();toast('Allenamento iniziato');await renderWorkout()}catch(e){toast(e.message)}}
async function saveRow(row){if(!state.session){toast('Premi prima Inizia');return}const load=Number(row.querySelector('[data-load]').value||0),reps=Number(row.querySelector('[data-reps]').value||0),rir=row.querySelector('[data-rir]').value;try{await api.saveSet({athlete_id:state.boot.uid,session_id:state.session.id,plan_id:state.workout.day.plan_id,day_id:state.workout.day.id,workout_item_id:row.dataset.item,exercise_id:row.dataset.ex,exercise_name_snapshot:row.dataset.name,set_index:Number(row.dataset.set),load,reps,rir:rir===''?null:Number(rir)});row.querySelector('[data-save]').classList.add('done');row.querySelector('[data-save]').textContent='✓';toast('Set salvato')}catch(e){toast(e.message)}}
async function finishWorkout(){try{const rows=[...document.querySelectorAll('.setRow')],done=rows.filter(r=>r.querySelector('[data-save]').classList.contains('done')).length,pct=rows.length?Math.round(done/rows.length*100):0,dur=state.startedAt?Math.max(1,Math.round((Date.now()-state.startedAt)/60000)):null;await api.finishSession(state.session.id,{ended_at:new Date().toISOString(),duration_minutes:dur,completion_percent:pct,logged_exercises:new Set(rows.filter(r=>r.querySelector('[data-save]').classList.contains('done')).map(r=>r.dataset.ex)).size});toast(`Workout terminato · ${pct}%`);state.boot=await api.bootstrap();state.session=null;home()}catch(e){toast(e.message)}}
async function exerciseLibrary(){state.view='more';loading('Carico esercizi…');try{state.catalog=state.catalog||await api.exerciseCatalog();renderExerciseLibrary('')}catch(e){failure(e)}}
function renderExerciseLibrary(q){const list=(state.catalog||[]).filter(e=>!q||`${e.name} ${e.muscle_group||''} ${e.equipment||''}`.toLowerCase().includes(q.toLowerCase()));shell(`<div class="sectionHead"><div><h1>Esercizi</h1><span class="muted">${state.catalog.length} esercizi nel database</span></div></div><input id="exSearch" class="search" placeholder="Cerca esercizio o gruppo muscolare…" value="${esc(q)}"><div class="exerciseGrid">${list.map(e=>`<div class="exerciseCard">${e.image_url?`<img class="thumb" loading="lazy" src="${esc(e.image_url)}" alt="${esc(e.name)}">`:'<div class="thumb"></div>'}<div><b>${esc(e.name)}</b><span>${esc(e.muscle_group||'')}${e.equipment?' · '+esc(e.equipment):''}</span></div></div>`).join('')}</div>`);document.getElementById('exSearch').oninput=e=>renderExerciseLibrary(e.target.value)}
async function progress(){state.view='progress';const b=state.boot,m=b.measures||[],s=b.sessions||[],g=b.goals||[];const latest=m[0]||{};let prs=[];try{prs=await api.get('v_exercise_prs',{select:'*',athlete_id:`eq.${b.uid}`,limit:10})}catch{}shell(`<div class="sectionHead"><div><h1>Progressi</h1><span class="muted">Corpo, performance e obiettivi</span></div></div><div class="kpis"><div class="kpi"><b>${latest.weight_kg?fmt(latest.weight_kg)+' kg':'—'}</b><span>Peso</span></div><div class="kpi"><b>${latest.bmi?fmt(latest.bmi):'—'}</b><span>BMI</span></div><div class="kpi"><b>${s.length}</b><span>Sessioni registrate</span></div><div class="kpi"><b>${prs.length}</b><span>PR esercizi</span></div></div><section class="section"><div class="sectionHead"><h2>Ultime misure</h2></div><div class="card list">${m.slice(0,8).map(x=>`<div class="row"><span>${esc(x.measured_on)}</span><b>${x.weight_kg?fmt(x.weight_kg)+' kg':'—'}</b></div>`).join('')||'<div class="empty">Nessuna misura.</div>'}</div></section><section class="section"><div class="sectionHead"><h2>Obiettivi</h2></div><div class="card list">${g.map(x=>`<div class="row"><span>${esc(x.title||'Obiettivo')}</span><b>${esc(x.status||'attivo')}</b></div>`).join('')||'<div class="empty">Nessun obiettivo.</div>'}</div></section>`)}
async function nutrition(){state.view='nutrition';loading('Carico nutrizione…');try{const d=await api.nutrition(state.boot.uid),p=d.plans.find(x=>x.active)||d.plans[0]||{};shell(`<div class="sectionHead"><div><h1>Nutrizione</h1><span class="muted">Piano, ricette, dispensa e integratori</span></div></div><div class="kpis"><div class="kpi"><b>${fmt(p.kcal_target,0)}</b><span>Calorie obiettivo</span></div><div class="kpi"><b>${fmt(p.protein_g_target,0)} g</b><span>Proteine</span></div><div class="kpi"><b>${fmt(p.carbs_g_target,0)} g</b><span>Carboidrati</span></div><div class="kpi"><b>${fmt(p.fat_g_target,0)} g</b><span>Grassi</span></div></div><section class="section"><div class="dayGrid"><div class="card"><b>${d.recipes.length}</b><div class="muted">Ricette</div></div><div class="card"><b>${d.pantry.length}</b><div class="muted">Dispensa</div></div><div class="card"><b>${d.lists.length}</b><div class="muted">Liste spesa</div></div><div class="card"><b>${d.supp.length}</b><div class="muted">Integratori</div></div></div></section>`)}catch(e){failure(e)}}
async function more(){state.view='more';shell(`<div class="sectionHead"><div><h1>Altro</h1><span class="muted">Strumenti PT-PRO</span></div></div><div class="dayGrid"><button class="dayCard" id="lib"><div><b>🏋️ Esercizi</b><span>Libreria completa</span></div></button><button class="dayCard" id="reload"><div><b>↻ Aggiorna dati</b><span>Ricarica da Supabase</span></div></button></div>`);document.getElementById('lib').onclick=exerciseLibrary;document.getElementById('reload').onclick=async()=>{loading('Aggiorno dati…');state.boot=await api.bootstrap();home()}}
async function go(v){try{if(v==='home')home();else if(v==='workout')workoutList();else if(v==='progress')await progress();else if(v==='nutrition')await nutrition();else if(v==='more')more()}catch(e){failure(e)}}
async function init(){loading('Avvio PT-PRO 10…');try{state.boot=await api.bootstrap();home()}catch(e){failure(e)}}
init();
})();