(() => {
'use strict';
const A=window.PTAPP,{api,state,esc,shell,toast}=A;
const uid=()=>state.boot.uid;
const defaults={accent:'#635bff',fontScale:100,density:'comfortable',rounded:true,shadows:true,animations:true};
async function getPrefs(){const r=await api.get('user_preferences',{select:'*',athlete_id:`eq.${uid()}`,limit:1}).catch(()=>[]);return r[0]||null}
async function persist(theme,settings){try{const p=await getPrefs(),payload={theme_mode:theme,app_settings:settings};if(p)await api.patch('user_preferences',{athlete_id:`eq.${uid()}`},payload);else await api.post('user_preferences',{athlete_id:uid(),...payload});return true}catch(e){console.error('appearance persistence',e);toast('Aspetto applicato, salvataggio Cloud non riuscito','err');return false}}
function resolvedTheme(mode){if(mode==='auto')return window.matchMedia?.('(prefers-color-scheme: dark)').matches?'dark':'light';return mode}
function apply(theme,settings={}){const s={...defaults,...settings};const root=document.documentElement;root.dataset.theme=resolvedTheme(theme);root.style.setProperty('--accent',s.accent);root.style.setProperty('--ui-scale',String(s.fontScale/100));root.dataset.density=s.density;root.dataset.rounded=s.rounded?'on':'off';root.dataset.shadows=s.shadows?'on':'off';root.dataset.animations=s.animations?'on':'off';try{localStorage.setItem('ptpro-appearance',JSON.stringify({theme,settings:s}))}catch{}}
function cardToggle(label,desc,key,on,icon){return `<div class="appearanceRow"><div class="appearanceLabel"><span class="appearanceMiniIcon">${icon}</span><div><b>${label}</b><small>${desc}</small></div></div><button class="toggle ${on?'on':''}" data-toggle="${key}" aria-label="${esc(label)}"></button></div>`}
A.register('appearance',async()=>{state.view='more';const p=await getPrefs(),theme=p?.theme_mode||'auto',settings={...defaults,...(p?.app_settings||{})};apply(theme,settings);const accents=['#635bff','#7c3aed','#e11d8d','#ef312a','#ff7a00','#f4a900','#16b43c','#08b7ad','#2584ed','#718096'];shell(`<div class="appearancePanel"><div class="appearanceTitle"><div class="appearanceIcon">🎨</div><div><h1>Aspetto</h1><span class="muted">Personalizza l'aspetto dell'applicazione</span></div></div><div class="card"><div class="sectionHead"><h2>Tema dell'app</h2></div><div class="themeGrid">${[['auto','☀','Automatico','Segue ora/dispositivo'],['dark','◐','Scuro','Tema scuro'],['light','☀','Chiaro','Tema chiaro']].map(([v,i,l,s])=>`<button class="dayCard ${theme===v?'selected':''}" data-theme-mode="${v}"><div><div class="themeGlyph ${v}">${i}</div><b>${l}</b><span>${s}</span>${theme===v?'<i class="themeCheck">✓</i>':''}</div></button>`).join('')}</div></div><div class="card"><div class="sectionHead"><div><h2>Colore principale</h2><span class="muted">Scegli il colore di accento dell'interfaccia</span></div></div><div class="accentDots">${accents.map(c=>`<button class="accentDot ${settings.accent===c?'active':''}" data-accent="${c}" style="background:${c}" aria-label="Colore ${c}">${settings.accent===c?'✓':''}</button>`).join('')}</div></div><div class="card appearanceOptions"><div class="appearanceRow"><div class="appearanceLabel"><span class="appearanceMiniIcon">A</span><div><b>Dimensione testo</b><small>Regola la dimensione del testo nell'app</small></div></div><div class="fontScale"><button data-font="-10">A</button><b id="fontValue">${settings.fontScale}%</b><button data-font="10">A</button></div></div><div class="appearanceRow"><div class="appearanceLabel"><span class="appearanceMiniIcon">☷</span><div><b>Densità interfaccia</b><small>Regola la spaziatura e la densità degli elementi</small></div></div><div class="densityGroup">${[['compact','☰'],['comfortable','☷'],['relaxed','☷']].map(([v,i])=>`<button class="${settings.density===v?'active':''}" data-density="${v}">${i}</button>`).join('')}</div></div></div><div class="card"><div class="sectionHead"><h2>Opzioni visuali</h2></div>${cardToggle('Angoli arrotondati','Applica bordi arrotondati a card e pulsanti','rounded',settings.rounded,'▢')}${cardToggle('Ombre morbide','Abilita ombre per una maggiore profondità visiva','shadows',settings.shadows,'◼')}${cardToggle('Animazioni fluide','Abilita animazioni e transizioni fluide','animations',settings.animations,'☆')}</div></div>`);
const save=async()=>{apply(themeState,settings);await persist(themeState,settings)};let themeState=theme;
document.querySelectorAll('[data-theme-mode]').forEach(b=>b.onclick=async()=>{themeState=b.dataset.themeMode;apply(themeState,settings);await persist(themeState,settings);A.go('appearance')});
document.querySelectorAll('[data-accent]').forEach(b=>b.onclick=async()=>{settings.accent=b.dataset.accent;await save();A.go('appearance')});
document.querySelectorAll('[data-font]').forEach(b=>b.onclick=async()=>{settings.fontScale=Math.min(120,Math.max(85,settings.fontScale+Number(b.dataset.font)));document.getElementById('fontValue').textContent=settings.fontScale+'%';await save()});
document.querySelectorAll('[data-density]').forEach(b=>b.onclick=async()=>{settings.density=b.dataset.density;await save();A.go('appearance')});
document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=async()=>{const k=b.dataset.toggle;settings[k]=!settings[k];await save();A.go('appearance')});
});
window.PTPROAppearance={apply};
try{const raw=JSON.parse(localStorage.getItem('ptpro-appearance')||'null');if(raw)apply(raw.theme||'auto',raw.settings||{})}catch{}
})();