(() => {
'use strict';
const A=window.PTAPP,L=window.PTPROExerciseGuides;if(!A||!L)return;const {state,esc,shell,modal}=A;
const atlas=x=>x.atlas==='basic'?'/assets/exercise-guides/beginner-movements-atlas.png':'/assets/exercise-guides/sport-fundamentals-atlas.png';
const picture=x=>`<div class="guidePicture" role="img" aria-label="Dimostrazione ${esc(x.name)}" style="--guide-image:url('${atlas(x)}');--guide-x:${x.x};--guide-y:${x.y}"></div>`;
function detail(x){modal(x.name,`${picture(x)}<div class="guideMeta"><span>${esc(x.sport)}</span><span>${esc(x.category)}</span><span>${esc(x.level)}</span><span>${esc(x.equipment)}</span></div><div class="guideColumns"><section><h3>Come si esegue</h3><ol>${x.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></section><section><h3>Errori comuni</h3><ul>${x.errors.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></section></div><div class="coach"><div class="coachScore">✓</div><div><b>${esc(x.cue)}</b><p>${esc(x.safety)}</p></div></div>`)}
function render(q='',sport='Tutti'){const list=L.search(q).filter(x=>sport==='Tutti'||x.sport===sport),sports=['Tutti',...new Set(L.guides.map(x=>x.sport))];shell(`<div class="sectionHead"><div><div class="eyebrow">ARCHIVIO SPORT PRO</div><h1>Guide illustrate</h1><span class="muted">Tecnica semplice, immagini, errori comuni e sicurezza per iniziare bene.</span></div></div><div class="guideFilters"><input class="search" id="guideQ" placeholder="Cerca esercizio, sport o attrezzatura…" value="${esc(q)}"><select id="guideSport">${sports.map(s=>`<option ${s===sport?'selected':''}>${esc(s)}</option>`).join('')}</select></div><div class="guideGrid">${list.map(x=>`<button class="guideCard" data-guide="${x.id}">${picture(x)}<span class="guideCardBody"><b>${esc(x.name)}</b><small>${esc(x.sport)} · ${esc(x.category)}</small><em>${esc(x.cue)}</em></span></button>`).join('')||'<div class="card empty">Nessuna guida trovata.</div>'}</div>`);document.getElementById('guideQ').oninput=e=>render(e.target.value,document.getElementById('guideSport').value);document.getElementById('guideSport').onchange=e=>render(document.getElementById('guideQ').value,e.target.value);document.querySelectorAll('[data-guide]').forEach(b=>b.onclick=()=>detail(L.byId(b.dataset.guide)))}
A.register('exercise-guides',async()=>{state.view='more';render()});
})();
