(() => {
'use strict';
const A=window.PTAPP,{api,state,esc,fmt,shell,readiness,smartAdvice,go}=A;
function ymd(v){return new Date(v).toISOString().slice(0,10)}
function streak(sessions){const dates=new Set((sessions||[]).filter(x=>x.ended_at||Number(x.duration_minutes)>0).map(x=>ymd(x.started_at)));let d=new Date();d.setHours(12,0,0,0);if(!dates.has(d.toISOString().slice(0,10)))d.setDate(d.getDate()-1);let n=0;while(dates.has(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n}
A.register('home',async()=>{
 state.view='home';const b=state.boot,p=b.profile||{},plan=b.plan,days=b.days||[],sessions=b.sessions||[],m=b.measures||[],r=readiness(),ad=smartAdvice(r),now=Date.now(),week=sessions.filter(s=>now-new Date(s.started_at).getTime()<7*864e5),mins=week.reduce((a,s)=>a+Number(s.duration_minutes||0),0),last=m[0],prev=m[1],trend=last?.weight_kg&&prev?.weight_kg?Number(last.weight_kg)-Number(prev.weight_kg):null,next=adaptiveNext(days,sessions),nextEvent=(b.events||[]).find(e=>new Date(e.starts_at)>new Date());
 const [vols,prs,prefs,catalog,sportPrograms,activityLogs]=await Promise.all([api.get('v_weekly_training_volume',{select:'*',athlete_id:`eq.${b.uid}`,order:'week_start.desc',limit:2}).catch(()=>[]),api.get('v_exercise_prs',{select:'*',athlete_id:`eq.${b.uid}`,limit:6}).catch(()=>[]),api.get('user_preferences',{select:'*',athlete_id:`eq.${b.uid}`,limit:1}).catch(()=>[]),api.exerciseCatalog().catch(()=>[]),api.get('wellness_programs',{select:'*',athlete_id:`eq.${b.uid}`,status:'neq.archived',order:'created_at.desc',limit:50}).catch(()=>[]),api.get('activity_logs',{select:'*',athlete_id:`eq.${b.uid}`,order:'started_at.desc',limit:100}).catch(()=>[])]),vol=vols[0]?.total_volume||0,st=streak(sessions),qa=Array.isArray(prefs[0]?.quick_actions)&&prefs[0].quick_actions.length?prefs[0].quick_actions:['workout','wellness','progress','coach-smart'],em=new Map(catalog.map(x=>[x.id,x])),wellnessWeek=activityLogs.filter(x=>now-new Date(x.started_at).getTime()<7*864e5),wellnessMins=wellnessWeek.reduce((s,x)=>s+Number(x.duration_minutes||0),0);
 const labels={workout:['🏋️','Allenamento'],wellness:['✨','Wellness'],progress:['📈','Progressi'],nutrition:['🥗','Nutrizione'],search:['⌕','Ricerca'],calendar:['📅','Calendario'],notifications:['🔔','Notifiche'],'coach-smart':['🧠','Smart Coach'],'data-manager':['🧱','Schede'],school:['🎓','Area Docenti']};
 shell(`<section class="hero"><div class="card heroMain"><div class="eyebrow">${new Date().toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long'})}</div><h1>Ciao ${esc(p.display_name||p.first_name||'Vincenzo')}.</h1><p class="muted">${plan?`Scheda palestra: <b>${esc(plan.title)}</b>${plan.phase?' · '+esc(plan.phase):''}`:'Nessuna scheda palestra attiva'}${sportPrograms.length?` · ${sportPrograms.length} schede sport salvate`:''}</p>${next?`<button class="btn primary full" id="startToday">▶ ${esc(next.name)}</button>`:''}</div><div class="kpis"><div class="kpi"><b>${week.length+wellnessWeek.length}</b><span>Sessioni settimana</span></div><div class="kpi"><b>${last?.weight_kg?fmt(last.weight_kg)+' kg':'—'}</b><span>Peso</span></div><div class="kpi"><b>${st}</b><span>Streak giorni</span></div><div class="kpi"><b>${mins+wellnessMins}′</b><span>Minuti settimana</span></div></div></section>
 <section class="section"><div class="sectionHead"><h2>Azioni rapide</h2><button class="linkBtn" data-route="quick-actions">Personalizza</button></div><div class="quickGrid">${qa.slice(0,4).map(x=>`<button class="dayCard" data-route="${x}"><div><b>${labels[x]?.[0]||'•'} ${labels[x]?.[1]||esc(x)}</b></div></button>`).join('')}</div></section>
 ${sportPrograms.length?`<section class="section"><div class="sectionHead"><div><h2>Le mie attività</h2><span class="muted">Passa da una scheda all’altra senza perdere quelle già create.</span></div><button class="linkBtn" data-route="wellness">Gestisci</button></div><div class="dayGrid">${sportPrograms.map(x=>`<button class="dayCard" data-sport-program="${x.id}"><div><b>✨ ${esc(x.title)}</b><span>${x.weeks||4} settimane · ${x.days_per_week||3} giorni/settimana</span></div></button>`).join('')}</div></section>`:''}
 <section class="section"><div class="sectionHead"><h2>Smart Coach PRO</h2><button class="linkBtn" data-route="coach-smart">Analisi completa</button></div><div class="coach"><div class="coachScore">${r}</div><div><b>${ad[0]}</b><p>${ad[1]}</p></div></div><div class="insightGrid"><div class="miniCard"><b>${fmt(vol,0)}</b><span>volume settimana</span></div><div class="miniCard"><b>${trend===null?'—':(trend>=0?'+':'')+fmt(trend)+' kg'}</b><span>trend peso</span></div><div class="miniCard"><b>${prs.length}</b><span>PR/e1RM rilevati</span></div><div class="miniCard"><b>${(b.goals||[]).filter(g=>g.status==='active').length}</b><span>obiettivi attivi</span></div></div></section>
 ${prs.length?`<section class="section"><div class="sectionHead"><h2>Performance recenti</h2><button class="linkBtn" data-route="progress">Centro Progressi</button></div><div class="card list">${prs.slice(0,4).map(x=>{const e=em.get(x.exercise_id)||{};return `<div class="row"><span><b>${esc(e.name||'Esercizio')}</b><br><small>${esc(e.muscle_group||'')}</small></span><b>${x.best_load?fmt(x.best_load)+' kg':''}${x.best_e1rm?' · e1RM '+fmt(x.best_e1rm):''}</b></div>`}).join('')}</div></section>`:''}
 ${nextEvent?`<section class="section"><div class="sectionHead"><h2>Prossimo evento</h2><button class="linkBtn" data-route="calendar-pro">Calendario</button></div><button class="dayCard" data-route="calendar-pro"><div><b>${esc(nextEvent.title)}</b><span>${new Date(nextEvent.starts_at).toLocaleString('it-IT')}</span></div></button></section>`:''}
 <section class="section"><div class="sectionHead"><h2>Allenamenti palestra</h2><span class="muted">${days.length} giorni</span></div><div class="dayGrid">${days.map((d,i)=>`<button class="dayCard" data-day="${d.id}"><div><b>${i+1}. ${esc(d.name)}</b><span>${esc(d.focus||'')}</span></div></button>`).join('')||'<div class="card empty">Nessun giorno programmato.</div>'}</div></section>`);
 document.querySelectorAll('[data-day]').forEach(x=>x.onclick=()=>go('workout-day',x.dataset.day));document.querySelectorAll('[data-sport-program]').forEach(x=>x.onclick=()=>go('wellness-program',x.dataset.sportProgram));if(next)document.getElementById('startToday').onclick=()=>go('workout-day',next.id);A.bindRoutes();
});
function adaptiveNext(days,sessions){if(!days.length)return null;const done=(sessions||[]).filter(x=>x.ended_at||Number(x.duration_minutes)>0).sort((a,b)=>new Date(b.started_at)-new Date(a.started_at));if(!done.length)return days[0];const i=days.findIndex(d=>d.id===done[0].day_id);return i<0?days[0]:days[(i+1)%days.length]}
})();