(() => {
'use strict';
const A=window.PTAPP;if(!A)return;const {api,state,esc,shell,loading,toast,modal,fmt,today}=A;
const RULES_KEY='ptpro_automation_rules_v1',RUNS_KEY='ptpro_automation_runs_v1',DRAFTS_KEY='ptpro_drafts_v1',AI_KEY='ptpro_intelligence_history_v1';
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}},write=(key,value)=>{localStorage.setItem(key,JSON.stringify(value));return value};
const templates=[
 {id:'weekly-review',icon:'📊',title:'Riepilogo settimanale',area:'Analisi',description:'Prepara priorità e andamento ogni sette giorni.',cadence:'settimanale',enabled:true},
 {id:'recovery-guard',icon:'🛡️',title:'Protezione recupero',area:'Workout',description:'Segnala quando il recupero suggerisce di ridurre il carico.',cadence:'a ogni check-in',enabled:true},
 {id:'missed-workout',icon:'↻',title:'Recupero sedute saltate',area:'Workout',description:'Propone come riprogrammare una seduta non completata.',cadence:'giornaliera',enabled:true},
 {id:'nutrition-week',icon:'🥗',title:'Piano e spesa della settimana',area:'Nutrizione',description:'Ricorda di preparare menu e lista della spesa.',cadence:'settimanale',enabled:false},
 {id:'meal-alternative',icon:'⇄',title:'Alternative pasti',area:'Nutrizione',description:'Suggerisce sostituzioni quando mancano alimenti preferiti.',cadence:'su richiesta',enabled:true},
 {id:'school-followup',icon:'🎓',title:'Chiusura lezione',area:'Scuola',description:'Ricorda presenze, parte teorica, pratica e valutazione.',cadence:'dopo una lezione',enabled:true},
 {id:'class-progress',icon:'🧭',title:'Progressione classe',area:'Scuola',description:'Suggerisce il prossimo argomento per periodo e anno.',cadence:'settimanale',enabled:true},
 {id:'draft-protection',icon:'💾',title:'Protezione bozze',area:'Sistema',description:'Conserva temporaneamente i campi durante il lavoro.',cadence:'continua',enabled:true}
];
function rules(){const saved=read(RULES_KEY,{});return templates.map(x=>({...x,enabled:saved[x.id]??x.enabled}))}
function saveRule(id,enabled){const saved=read(RULES_KEY,{});saved[id]=enabled;write(RULES_KEY,saved)}
function schoolData(){return read('ptpro_school_planner_v1',{})}
function nutritionProfile(){return read('ptpro_nutrition_profile',{})}
function metrics(extra={}){const school=schoolData(),profile=nutritionProfile(),sessions=state.boot?.sessions||[],goals=(state.boot?.goals||[]).filter(x=>x.status==='active'),check=state.boot?.checkins?.[0]||{},readiness=A.readiness(),weekSessions=sessions.filter(x=>x.ended_at&&Date.now()-new Date(x.ended_at).getTime()<7*864e5);return{readiness,weekSessions:weekSessions.length,goals:goals.length,classes:(school.classes||[]).length,students:(school.students||[]).length,assignments:(school.assignments||[]).length,pending:(school.assignments||[]).filter(x=>x.status!=='Completata'&&!(x.theoryDone&&x.practiceDone)).length,nutritionGoal:profile.goal||'non impostato',...extra}}
function insights(m){const out=[];out.push(m.readiness<55?{tone:'warn',icon:'🛡️',title:'Recupero da proteggere',text:`Readiness ${m.readiness}/100: riduci volume e intensità, mantieni tecnica pulita.`,route:'coach-smart'}:{tone:'ok',icon:'⚡',title:'Carico gestibile',text:`Readiness ${m.readiness}/100: puoi seguire la programmazione con autoregolazione.`,route:'workout'});out.push(m.weekSessions?{tone:'ok',icon:'🏋️',title:`${m.weekSessions} sedute completate`,text:'Controlla progressione, volume e recupero nel Centro Progressi.',route:'progress'}:{tone:'warn',icon:'↻',title:'Settimana da avviare',text:'Non risultano sedute completate negli ultimi sette giorni.',route:'workout'});out.push(m.classes?{tone:m.pending?'warn':'ok',icon:'🎓',title:`${m.classes} classi · ${m.students} alunni`,text:m.pending?`${m.pending} attività scolastiche risultano ancora da completare.`:'Le attività scolastiche risultano aggiornate.',route:'school-planner'}:{tone:'neutral',icon:'🎓',title:'Registro da configurare',text:'Crea una classe per ricevere suggerimenti didattici contestuali.',route:'school-planner'});out.push({tone:m.nutritionGoal==='non impostato'?'warn':'ok',icon:'🥗',title:`Nutrizione: ${m.nutritionGoal}`,text:m.nutritionGoal==='non impostato'?'Completa obiettivo e dati personali per generare piani coerenti.':'Il profilo nutrizionale è disponibile per le prossime generazioni.',route:'nutrition'});return out}
function runDue(manual=false){const m=metrics(),enabled=rules().filter(x=>x.enabled),last=read(RUNS_KEY,[]),now=new Date().toISOString(),generated=[];for(const r of enabled){const previous=last.find(x=>x.ruleId===r.id),hours=previous?(Date.now()-new Date(previous.at).getTime())/36e5:Infinity,due=manual||(r.cadence==='continua'?hours>1:r.cadence==='giornaliera'||r.cadence==='a ogni check-in'?hours>20:r.cadence==='settimanale'?hours>144:false);if(!due)continue;let result='Controllo completato';if(r.id==='recovery-guard')result=m.readiness<55?'Recupero basso: valuta uno scarico del 25–35%.':'Recupero compatibile con la programmazione.';if(r.id==='weekly-review')result=`${m.weekSessions} sedute, ${m.goals} obiettivi attivi, ${m.pending} attività scolastiche aperte.`;if(r.id==='missed-workout')result=m.weekSessions?'Continuità rilevata: nessun recupero urgente.':'Nessuna seduta recente: pianifica una ripartenza graduale.';if(r.id==='nutrition-week')result=m.nutritionGoal==='non impostato'?'Completa prima il profilo nutrizionale.':'Prepara menu settimanale e lista della spesa.';if(r.id==='school-followup')result=m.pending?`${m.pending} attività attendono completamento o valutazione.`:'Nessuna attività scolastica arretrata.';if(r.id==='class-progress')result=m.classes?`Controlla la progressione periodica di ${m.classes} classi.`:'Crea la prima classe per attivare i suggerimenti.';generated.push({id:`run-${Date.now()}-${r.id}`,ruleId:r.id,title:r.title,result,at:now})}if(generated.length)write(RUNS_KEY,[...generated,...last].slice(0,80));return generated}
function assistant(area,request=''){const m=metrics(),q=request.trim(),plans={today:{title:'Priorità di oggi',items:[m.readiness<55?'Scegli una seduta leggera o tecnica.':'Completa la seduta prevista mantenendo il margine indicato.',m.nutritionGoal==='non impostato'?'Configura il profilo nutrizionale.':'Segui il piano e registra eventuali sostituzioni.',m.pending?`Completa o aggiorna ${m.pending} attività scolastiche.`:'Controlla calendario e obiettivi.']},workout:{title:'Indicazione allenamento',items:[`Readiness rilevata: ${m.readiness}/100.`,m.readiness<55?'Riduci volume 25–35% ed evita il cedimento.':'Mantieni il piano e aumenta solo se tecnica e recupero restano buoni.','Registra serie, RIR/RPE e sensazioni finali.']},nutrition:{title:'Indicazione nutrizione',items:[`Obiettivo disponibile: ${m.nutritionGoal}.`,'Genera la giornata dalla sezione Nutrizione PRO.','Controlla allergie, preferenze e sostituzioni prima di confermare.']},school:{title:'Indicazione scuola',items:[`${m.classes} classi e ${m.students} alunni disponibili.`,m.pending?`Rivedi ${m.pending} attività pianificate.`:'Scegli il prossimo contenuto dalla progressione annuale.','Abbina sempre parte teorica, pratica e criterio di valutazione.']}};const p=plans[area]||plans.today;if(q)p.items.push(`Richiesta considerata: ${q}`);return{...p,area,request:q,createdAt:new Date().toISOString(),disclaimer:'Suggerimento organizzativo: verifica sempre sicurezza, condizioni personali e contesto scolastico.'}}
function ask(){const m=modal('Assistente intelligente PT-PRO',`<label>Ambito<select id="aiArea"><option value="today">Giornata completa</option><option value="workout">Allenamento</option><option value="nutrition">Nutrizione</option><option value="school">Scuola</option></select></label><label>Cosa vuoi organizzare?<textarea id="aiRequest" class="plannerTextarea" placeholder="Es. Preparami le priorità per domani"></textarea></label><div class="intelligencePrivacy">🔒 Elaborazione locale: nomi degli alunni e dati personali non vengono inviati all’esterno.</div><button class="btn primary full" id="aiGenerate">Genera indicazione</button><div id="aiResult"></div>`);m.querySelector('#aiGenerate').onclick=()=>{const result=assistant(m.querySelector('#aiArea').value,m.querySelector('#aiRequest').value),history=read(AI_KEY,[]);write(AI_KEY,[result,...history].slice(0,30));m.querySelector('#aiResult').innerHTML=`<div class="aiAnswer"><h3>${esc(result.title)}</h3><ol>${result.items.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><small>${esc(result.disclaimer)}</small></div>`}}
function draftsPanel(){const drafts=Object.values(read(DRAFTS_KEY,{})).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))),m=modal('Bozze e ripristino',`<p class="muted">I campi di lavoro vengono conservati per sette giorni sul dispositivo.</p><div class="card list">${drafts.map(x=>`<div class="row"><span><b>${esc(x.label||x.field)}</b><small>${esc(x.route)} · ${new Date(x.updatedAt).toLocaleString('it-IT')}</small></span><span class="manageButtons"><button class="btn primary small" data-restore-draft="${esc(x.key)}">Ripristina</button><button class="btn secondary small" data-remove-draft="${esc(x.key)}">Elimina</button></span></div>`).join('')||'<div class="empty">Nessuna bozza in sospeso.</div>'}</div><button class="btn danger full" id="clearDrafts" ${drafts.length?'':'disabled'}>Elimina tutte le bozze</button>`);m.querySelectorAll('[data-restore-draft]').forEach(b=>b.onclick=async()=>{const draft=read(DRAFTS_KEY,{})[b.dataset.restoreDraft];if(!draft)return;m.remove();await A.go(draft.route);setTimeout(()=>{const field=document.getElementById(draft.field)||document.querySelector(`[name="${CSS.escape(draft.field)}"]`);if(!field)return toast('Apri il modulo originale per ripristinare questa bozza','err');field.value=draft.value;field.dispatchEvent(new Event('input',{bubbles:true}));field.focus();toast('Bozza ripristinata ✓')},80)});m.querySelectorAll('[data-remove-draft]').forEach(b=>b.onclick=()=>{const all=read(DRAFTS_KEY,{});delete all[b.dataset.removeDraft];write(DRAFTS_KEY,all);b.closest('.row').remove();toast('Bozza eliminata')});m.querySelector('#clearDrafts')?.addEventListener('click',()=>{write(DRAFTS_KEY,{});m.remove();toast('Bozze eliminate')})}
async function page(){state.view='intelligence';loading('Analizzo PT-PRO…');const extra={};try{const logs=await api.get('activity_logs',{select:'id,duration_minutes,started_at',athlete_id:`eq.${state.boot.uid}`,order:'started_at.desc',limit:30});extra.sportLogs=logs.length}catch{}const m=metrics(extra),cards=insights(m),history=read(RUNS_KEY,[]),active=rules().filter(x=>x.enabled).length;shell(`<div class="sectionHead intelligenceHead"><div><div class="eyebrow">INTELLIGENZA PT-PRO</div><h1>IA, analisi e automazioni</h1><span class="muted">Un unico centro per capire cosa fare e mantenere il lavoro sotto controllo.</span></div><button class="btn primary" id="askIntelligence">✦ Chiedi all’assistente</button></div><div class="kpis four"><div class="kpi"><b>${m.readiness}</b><span>Readiness</span></div><div class="kpi"><b>${m.weekSessions}</b><span>Sedute settimanali</span></div><div class="kpi"><b>${m.classes}</b><span>Classi</span></div><div class="kpi"><b>${active}/${templates.length}</b><span>Automazioni attive</span></div></div><section class="section"><div class="sectionHead"><h2>Analisi trasversale</h2><button class="btn secondary" id="openDrafts">Bozze e ripristino</button></div><div class="intelligenceGrid">${cards.map(x=>`<button class="intelligenceCard ${x.tone}" data-route="${x.route}"><span>${x.icon}</span><div><b>${esc(x.title)}</b><p>${esc(x.text)}</p></div><i>›</i></button>`).join('')}</div></section><section class="section"><div class="sectionHead"><div><h2>Automazioni</h2><span class="muted">Vengono eseguite quando apri PT-PRO; nessun dato sensibile lascia il dispositivo.</span></div><button class="btn primary" id="runAutomations">Esegui controlli</button></div><div class="automationGrid">${rules().map(x=>`<label class="automationCard"><span>${x.icon}</span><div><b>${esc(x.title)}</b><p>${esc(x.description)}</p><small>${esc(x.area)} · ${esc(x.cadence)}</small></div><input type="checkbox" data-rule="${x.id}" ${x.enabled?'checked':''}></label>`).join('')}</div></section><section class="section"><div class="sectionHead"><h2>Ultime attività automatiche</h2></div><div class="card list" id="automationRuns">${history.slice(0,12).map(x=>`<div class="row"><span><b>${esc(x.title)}</b><small>${esc(x.result)}</small></span><time>${new Date(x.at).toLocaleDateString('it-IT')}</time></div>`).join('')||'<div class="empty">Esegui i controlli per creare il primo riepilogo.</div>'}</div></section>`);A.bindRoutes();document.getElementById('askIntelligence').onclick=ask;document.getElementById('openDrafts').onclick=draftsPanel;document.querySelectorAll('[data-rule]').forEach(x=>x.onchange=()=>{saveRule(x.dataset.rule,x.checked);toast(x.checked?'Automazione attivata':'Automazione sospesa')});document.getElementById('runAutomations').onclick=()=>{const done=runDue(true);toast(`${done.length} controlli completati ✓`);page()}}
function captureDraft(e){const el=e.target;if(!el?.closest?.('#app')||!['INPUT','TEXTAREA','SELECT'].includes(el.tagName)||['password','email','file','checkbox','radio'].includes(el.type)||!el.value?.trim?.())return;const field=el.id||el.name;if(!field)return;const key=`${state.view}:${field}`,all=read(DRAFTS_KEY,{});all[key]={key,route:state.view,field,label:el.closest('label')?.firstChild?.textContent?.trim()||field,value:el.value,updatedAt:new Date().toISOString()};const cutoff=Date.now()-7*864e5;for(const [k,v] of Object.entries(all))if(new Date(v.updatedAt).getTime()<cutoff)delete all[k];write(DRAFTS_KEY,all)}
document.addEventListener('input',captureDraft);A.register('intelligence',page);window.PTPROIntelligence={metrics,insights,assistant,runDue,rules};setTimeout(()=>{if(state.boot)runDue(false)},2500);
})();
