(() => {
'use strict';
const api=window.PTAPI, app=document.getElementById('app');
const state={boot:null,view:'home',workout:null,session:null,startedAt:null,catalog:null,cache:new Map()};
const routes=new Map();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const fmt=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toLocaleString('it-IT',{maximumFractionDigits:d}):'—';
const today=()=>new Date().toISOString().slice(0,10);
function toast(text,type='ok'){const n=document.createElement('div');n.className='toast '+type;n.textContent=text;document.body.appendChild(n);setTimeout(()=>n.remove(),2400)}
function modal(title,body){const back=document.createElement('div');back.className='modalBack';back.innerHTML=`<div class="modal"><div class="modalHead"><h2>${esc(title)}</h2><button class="iconBtn" data-close>×</button></div>${body}</div>`;document.body.appendChild(back);back.querySelector('[data-close]').onclick=()=>back.remove();back.onclick=e=>{if(e.target===back)back.remove()};return back}
function criticalLayout(){return `<style id="ptpro-critical-layout">.appFrame{width:min(1480px,100%);margin:0 auto;display:grid;grid-template-columns:244px minmax(0,1fr);gap:28px;align-items:start;padding:20px 26px 120px}.appFrame>.app{width:100%;max-width:none;margin:0;padding:0}.sidebar{position:sticky;top:18px;height:calc(100vh - 36px);display:flex;flex-direction:column;background:var(--panel);border:1px solid var(--line);border-radius:24px;padding:17px 13px;box-shadow:var(--shadow);overflow:auto;z-index:95}.sideBrand{display:flex;align-items:center;gap:11px;width:100%;border:0;background:transparent;color:var(--text);padding:0 7px 15px;text-align:left;cursor:pointer}.sideBrand .logo{width:44px;height:44px;border-radius:14px;flex:0 0 auto}.sideBrand b{display:block;font-size:15px}.sideBrand span{display:block;color:var(--muted);font-size:10px;margin-top:3px}.sideDivider{height:1px;background:var(--line);margin:0 6px 13px}.sideGroup{display:grid;gap:3px;margin-bottom:16px}.sideTitle{font-size:9px;color:var(--accent);font-weight:850;letter-spacing:.08em;padding:4px 10px 7px}.sideItem{width:100%;display:flex;align-items:center;gap:10px;border:0;background:transparent;color:var(--text);border-radius:12px;padding:10px 11px;text-align:left;cursor:pointer;margin:1px 0}.sideItem b{font-size:12px;font-weight:650}.sideIcon{width:21px;text-align:center;color:#405071;font-size:14px}.sideItem:hover{background:var(--panel2)}.sideItem.active{background:linear-gradient(135deg,var(--accent),#4f7cff);color:#fff;box-shadow:0 7px 18px rgba(80,92,255,.2)}.sideItem.active .sideIcon{color:#fff}.userCard{margin-top:auto;width:100%;display:grid;grid-template-columns:38px 1fr auto;align-items:center;gap:9px;padding:10px;border-radius:16px;border:1px solid var(--line);background:var(--panel);color:var(--text);text-align:left;cursor:pointer;box-shadow:var(--shadow2)}.avatar{width:38px;height:38px;border-radius:12px;display:grid;place-items:center;background:linear-gradient(135deg,var(--accent),#287ddd);color:#fff;font-size:12px;font-weight:850}.userCard b{display:block;font-size:12px}.userCard small{display:block;color:var(--muted);font-size:9px;margin-top:2px}.userCard i{font-style:normal;font-size:22px;color:var(--muted)}.mobileBrand{display:none!important}.appFrame .top{justify-content:flex-end;margin:6px 0 28px}.bottom{z-index:90}@media(max-width:980px){.appFrame{display:block;padding:0}.sidebar{display:none!important}.appFrame>.app{width:min(1160px,100%);margin:auto;padding:20px 18px 110px}.mobileBrand{display:flex!important}.appFrame .top{justify-content:space-between}}@media(min-width:981px){.bottom{width:min(760px,calc(100% - 320px));left:calc(50% + 122px)}}</style>`}
function top(){const unread=(state.boot?.notifications||[]).filter(x=>!x.read_at).length;return `<div class="top"><div class="brand mobileBrand"><div class="logo"></div><div><b>PT-PRO</b><span>Wellness & Sport</span></div></div><button class="cloudPill" data-route="notifications">☁ Cloud${unread?` · 🔔 ${unread}`:''}</button></div>`}
const navItems=[['home','⌂','Home'],['workout','🏋️','Workout'],['wellness','✨','Wellness'],['progress','↗','Progressi'],['more','•••','Altro']];
function nav(){return `<nav class="bottom">${navItems.map(([v,i,l])=>`<button data-route="${v}" class="${state.view===v?'active':''}"><b>${i}</b>${l}</button>`).join('')}</nav>`}
const sideGroups=[['IMPOSTAZIONI',[['profile-pro','♙','Profilo'],['appearance','◉','Aspetto'],['notifications','♧','Notifiche'],['quick-actions','⚙','Preferenze'],['backup','☁','Backup & Dati']]],['WELLNESS & SPORT',[['wellness','✨','Attività & Sport'],['onboarding','◎','Il mio percorso'],['coach-smart','♜','Smart Coach'],['data-manager','▣','Builder Schede'],['progress','↗','Centro Progressi'],['nutrition','◉','Nutrizione PRO'],['calendar','▦','Calendario'],['reports','▥','Report & Analytics']]],['AMMINISTRAZIONE',[['admin-users','♛','Utenti & Attività']]],['SUPPORTO',[['guide','?','Guida & Tutorial'],['whats-new','✦','Novità'],['contact','✉','Contattaci']]]];
function sidebar(){const p=state.boot?.profile||{},name=p.display_name||p.first_name||'Utente',role=p.role||'athlete';return `<aside class="sidebar"><button class="sideBrand" data-route="home"><div class="logo"></div><div><b>PT-PRO 11</b><span>Wellness & Sport</span></div></button><div class="sideDivider"></div>${sideGroups.filter(([title])=>title!=='AMMINISTRAZIONE'||role==='admin').map(([title,items])=>`<section class="sideGroup"><div class="sideTitle">${title}</div>${items.map(([r,i,l])=>`<button data-route="${r}" class="sideItem ${state.view===r?'active':''}"><span class="sideIcon">${i}</span><b>${l}</b></button>`).join('')}</section>`).join('')}<button class="userCard" data-route="profile-pro"><span class="avatar">${esc(name).slice(0,2).toUpperCase()}</span><span><b>${esc(name)}</b><small>${esc(role==='admin'?'Admin':role==='coach'?'Coach':'Atleta')} • PRO</small></span><i>›</i></button></aside>`}
function bindRoutes(root=document){root.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route))}
function shell(content){app.innerHTML=`${criticalLayout()}<div class="appFrame">${sidebar()}<main class="app">${top()}${content}</main></div>${nav()}`;bindRoutes()}
function loading(t='Caricamento…'){app.innerHTML=`${criticalLayout()}<div class="appFrame">${sidebar()}<main class="app">${top()}<div class="loading"><div class="spinner"></div><span>${esc(t)}</span></div></main></div>`;bindRoutes()}
function failure(e){console.error(e);shell(`<div class="card"><h2>Errore</h2><div class="error">${esc(e?.message||e)}</div><button class="btn secondary" data-route="home">Torna alla Home</button></div>`)}
function register(name,fn){routes.set(name,fn)}
async function go(name,...args){state.view=name;const fn=routes.get(name);if(!fn){toast('Sezione non disponibile','err');return}try{await fn(...args)}catch(e){failure(e)}}
async function refresh(){state.boot=await api.bootstrap();return state.boot}
async function start(){loading('Avvio PT-PRO 11…');try{await refresh();await go('home')}catch(e){failure(e)}}
function readiness(){const c=state.boot?.checkins?.[0]||{};if(Number.isFinite(Number(c.recovery_score)))return Math.round(Number(c.recovery_score));const vals=[c.sleep,c.energy,c.motivation,c.stress!=null?10-Number(c.stress):null,c.doms!=null?10-Number(c.doms):null].map(Number).filter(Number.isFinite);return vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length*10):70}
function smartAdvice(r){return r<50?['Scarico consigliato','Riduci volume 30–40%, evita il cedimento e cura il recupero.']:r<65?['Fatica moderata','Mantieni margine tecnico e riduci leggermente volume o intensità.']:r>82?['Pronto a progredire','Recupero alto: puoi cercare una piccola progressione mantenendo tecnica pulita.']:['Programmazione regolare','Prosegui come previsto e usa il RIR per autoregolarti.']}
window.PTAPP={api,state,esc,fmt,today,toast,modal,shell,loading,failure,register,go,refresh,start,readiness,smartAdvice,bindRoutes};
})();