(() => {
'use strict';
const raw=[
['Avena','cereali',389,17,66,7,['glutine'],['vegan']],['Riso basmati','cereali',360,8,79,1,[],['vegan','senza_glutine']],['Riso integrale','cereali',360,8,76,3,[],['vegan','senza_glutine']],['Pasta di semola','cereali',353,13,71,2,['glutine'],['vegan']],['Pasta integrale','cereali',348,14,66,3,['glutine'],['vegan']],['Pane integrale','cereali',247,13,41,4,['glutine'],['vegan']],['Pane di segale','cereali',259,9,48,3,['glutine'],['vegan']],['Quinoa','cereali',368,14,64,6,[],['vegan','senza_glutine']],['Cous cous','cereali',376,13,77,1,['glutine'],['vegan']],['Patate','tuberi',77,2,17,.1,[],['vegan','senza_glutine']],
['Pollo','proteine',165,31,0,4,[],['onnivoro','senza_glutine','senza_lattosio']],['Tacchino','proteine',135,29,0,2,[],['onnivoro','senza_glutine','senza_lattosio']],['Manzo magro','proteine',190,27,0,8,[],['onnivoro','senza_glutine','senza_lattosio']],['Salmone','pesce',208,20,0,13,['pesce'],['onnivoro','senza_glutine','senza_lattosio']],['Tonno','pesce',116,26,0,1,['pesce'],['onnivoro','senza_glutine','senza_lattosio']],['Merluzzo','pesce',82,18,0,.7,['pesce'],['onnivoro','senza_glutine','senza_lattosio']],['Uova','proteine',143,13,1,10,['uova'],['onnivoro','vegetariano','senza_glutine','senza_lattosio']],['Albume','proteine',52,11,.7,.2,['uova'],['onnivoro','vegetariano','senza_glutine','senza_lattosio']],['Tofu','proteine vegetali',144,17,3,9,['soia'],['vegan','senza_glutine','senza_lattosio']],['Tempeh','proteine vegetali',193,20,8,11,['soia'],['vegan','senza_glutine','senza_lattosio']],
['Ceci','legumi',164,9,27,3,[],['vegan','senza_glutine']],['Lenticchie','legumi',116,9,20,.4,[],['vegan','senza_glutine']],['Fagioli rossi','legumi',127,9,23,.5,[],['vegan','senza_glutine']],['Piselli','legumi',81,5,14,.4,[],['vegan','senza_glutine']],['Yogurt greco','latticini',73,10,4,2,['latte'],['onnivoro','vegetariano','senza_glutine']],['Skyr','latticini',63,11,4,.2,['latte'],['onnivoro','vegetariano','senza_glutine']],['Latte','latticini',46,3,5,2,['latte'],['onnivoro','vegetariano','senza_glutine']],['Bevanda di soia','bevande',40,3,3,2,['soia'],['vegan','senza_glutine','senza_lattosio']],['Fiocchi di latte','latticini',98,12,3,4,['latte'],['onnivoro','vegetariano','senza_glutine']],['Parmigiano','latticini',402,32,0,30,['latte'],['onnivoro','vegetariano','senza_glutine']],
['Banana','frutta',89,1,23,.3,[],['vegan','senza_glutine']],['Mela','frutta',52,.3,14,.2,[],['vegan','senza_glutine']],['Pera','frutta',57,.4,15,.1,[],['vegan','senza_glutine']],['Arancia','frutta',47,.9,12,.1,[],['vegan','senza_glutine']],['Kiwi','frutta',61,1,15,.5,[],['vegan','senza_glutine']],['Fragole','frutta',32,.7,8,.3,[],['vegan','senza_glutine']],['Mirtilli','frutta',57,.7,14,.3,[],['vegan','senza_glutine']],['Ananas','frutta',50,.5,13,.1,[],['vegan','senza_glutine']],['Pesca','frutta',39,.9,10,.3,[],['vegan','senza_glutine']],['Avocado','frutta',160,2,9,15,[],['vegan','senza_glutine']],
['Zucchine','verdura',17,1,3,.3,[],['vegan','senza_glutine']],['Broccoli','verdura',34,3,7,.4,[],['vegan','senza_glutine']],['Spinaci','verdura',23,3,4,.4,[],['vegan','senza_glutine']],['Pomodori','verdura',18,.9,4,.2,[],['vegan','senza_glutine']],['Carote','verdura',41,.9,10,.2,[],['vegan','senza_glutine']],['Peperoni','verdura',31,1,6,.3,[],['vegan','senza_glutine']],['Melanzane','verdura',25,1,6,.2,[],['vegan','senza_glutine']],['Insalata','verdura',15,1,3,.2,[],['vegan','senza_glutine']],['Cavolfiore','verdura',25,2,5,.3,[],['vegan','senza_glutine']],['Funghi','verdura',22,3,3,.3,[],['vegan','senza_glutine']],
['Mandorle','grassi',579,21,22,50,['frutta a guscio'],['vegan','senza_glutine']],['Noci','grassi',654,15,14,65,['frutta a guscio'],['vegan','senza_glutine']],['Pistacchi','grassi',562,20,28,45,['frutta a guscio'],['vegan','senza_glutine']],['Burro di arachidi','grassi',588,25,20,50,['arachidi'],['vegan','senza_glutine']],['Olio EVO','grassi',884,0,0,100,[],['vegan','senza_glutine']],['Semi di chia','grassi',486,17,42,31,[],['vegan','senza_glutine']],['Semi di zucca','grassi',559,30,11,49,[],['vegan','senza_glutine']],['Mais','cereali',86,3,19,1,[],['vegan','senza_glutine']],['Gallette di riso','cereali',387,8,81,3,[],['vegan','senza_glutine']],['Cioccolato fondente','dolci',598,8,46,43,[],['vegan','senza_glutine']]
];
const forms=[['porzione piccola',80],['porzione standard',100],['porzione abbondante',125],['unità pratica',150]];
const foods=[];raw.forEach((f,i)=>forms.forEach((form,j)=>foods.push({id:`food-${i+1}-${j+1}`,name:`${f[0]} · ${form[0]}`,base_name:f[0],category:f[1],kcal_100:f[2],protein_100:f[3],carbs_100:f[4],fat_100:f[5],portion_g:form[1],portion_label:form[0],portion_kcal:Math.round(f[2]*form[1]/100),allergens:f[6],diet_modes:[...new Set([...(f[7]||[]),(f[7]||[]).includes('vegan')?'vegetariano':null,(f[7]||[]).includes('vegan')?'senza_lattosio':null].filter(Boolean))],active:true})));
const recipeBases=[
['Porridge energetico','Colazione',['Avena','Banana','Yogurt greco']],['Toast proteico','Colazione',['Pane integrale','Uova','Pomodori']],['Bowl yogurt e frutta','Colazione',['Yogurt greco','Mirtilli','Mandorle']],['Pancake avena','Colazione',['Avena','Uova','Banana']],['Chia pudding','Colazione',['Semi di chia','Bevanda di soia','Fragole']],['Riso pollo e verdure','Pranzo',['Riso basmati','Pollo','Zucchine']],['Pasta tonno e pomodoro','Pranzo',['Pasta di semola','Tonno','Pomodori']],['Quinoa ceci e ortaggi','Pranzo',['Quinoa','Ceci','Peperoni']],['Cous cous mediterraneo','Pranzo',['Cous cous','Tacchino','Melanzane']],['Insalata salmone e patate','Pranzo',['Salmone','Patate','Insalata']],['Bowl tofu e riso','Pranzo',['Tofu','Riso integrale','Broccoli']],['Lenticchie e cereali','Pranzo',['Lenticchie','Riso basmati','Spinaci']],['Tacchino patate e verdure','Cena',['Tacchino','Patate','Broccoli']],['Salmone quinoa e spinaci','Cena',['Salmone','Quinoa','Spinaci']],['Frittata alle verdure','Cena',['Uova','Zucchine','Spinaci']],['Tempeh con riso','Cena',['Tempeh','Riso basmati','Peperoni']],['Merluzzo e patate','Cena',['Merluzzo','Patate','Pomodori']],['Burger di ceci','Cena',['Ceci','Pane integrale','Insalata']],['Yogurt e frutta secca','Spuntino',['Yogurt greco','Mela','Noci']],['Banana e burro arachidi','Spuntino',['Banana','Burro di arachidi']],['Hummus e gallette','Spuntino',['Ceci','Gallette di riso']],['Skyr e mirtilli','Spuntino',['Skyr','Mirtilli']],['Frullato proteico','Spuntino',['Bevanda di soia','Banana','Avena']],['Cioccolato e mandorle','Spuntino',['Cioccolato fondente','Mandorle']]
];
const modes=[['onnivoro','Classica'],['vegetariano','Vegetariana'],['vegan','Vegana'],['senza_glutine','Senza glutine'],['senza_lattosio','Senza lattosio']];
const swaps={
 vegetariano:{Pollo:'Tofu',Tacchino:'Tempeh','Manzo magro':'Tofu',Salmone:'Uova',Tonno:'Uova',Merluzzo:'Tofu'},
 vegan:{Pollo:'Tofu',Tacchino:'Tempeh','Manzo magro':'Tofu',Salmone:'Tempeh',Tonno:'Tofu',Merluzzo:'Tofu',Uova:'Tofu',Albume:'Tofu','Yogurt greco':'Bevanda di soia',Skyr:'Bevanda di soia',Latte:'Bevanda di soia','Fiocchi di latte':'Tofu',Parmigiano:'Semi di zucca'},
 senza_glutine:{Avena:'Quinoa','Pasta di semola':'Riso basmati','Pasta integrale':'Riso integrale','Pane integrale':'Gallette di riso','Pane di segale':'Gallette di riso','Cous cous':'Quinoa'},
 senza_lattosio:{'Yogurt greco':'Bevanda di soia',Skyr:'Bevanda di soia',Latte:'Bevanda di soia','Fiocchi di latte':'Tofu',Parmigiano:'Semi di zucca'}
};
const ingredientFor=(name,mode)=>swaps[mode]?.[name]||name;
const recipes=[];
recipeBases.forEach((r,i)=>{
 modes.forEach((m,j)=>{
  const ingredients=r[2].map((name,k)=>({name:ingredientFor(name,m[0]),quantity:k?120:80,unit:'g'}));
  recipes.push({id:`recipe-${i+1}-${j+1}`,name:`${r[0]} · ${m[1]}`,category:r[1],diet_mode:m[0],servings:1,minutes:10+(i%4)*5,kcal:350+(i%6)*55,protein_g:18+(i%5)*5,carbs_g:35+(i%6)*7,fat_g:9+(i%4)*3,ingredients,allergens:[...new Set(ingredients.flatMap(x=>raw.find(f=>f[0]===x.name)?.[6]||[]))],steps:['Prepara e pesa gli ingredienti.','Cuoci gli alimenti che lo richiedono con metodi semplici.','Unisci, condisci e controlla la porzione.','Servi e conserva gli avanzi in modo sicuro.'],substitutions:['Scegli un alimento della stessa categoria con valori simili.','Adatta cereale o proteina alla modalità alimentare selezionata.']});
 });
});
const alternatives=(id,mode='',avoid=[])=>{const base=foods.find(x=>x.id===id||x.name===id||x.base_name===id);if(!base)return[];const blocked=(avoid||[]).map(x=>String(x).toLowerCase());return foods.filter(x=>x.id!==base.id&&x.category===base.category&&(!mode||x.diet_modes.includes(mode))&&!blocked.some(a=>`${x.name} ${x.allergens.join(' ')}`.toLowerCase().includes(a))).map(x=>({...x,match:Math.max(0,100-Math.abs(x.kcal_100-base.kcal_100)/3-Math.abs(x.protein_100-base.protein_100)*2)})).sort((a,b)=>b.match-a.match).slice(0,8)};
window.PTPRONutritionLibrary={foods,recipes,modes:modes.map(x=>x[0]),allergens:['glutine','latte','uova','pesce','soia','arachidi','frutta a guscio'],alternatives};
})();
