(() => {
'use strict';
const A=window.PTAPP,{api,state,esc,fmt,shell,loading,modal,toast,go,today}=A;
const uid=()=>state.boot.uid;
const asNum=v=>Number.isFinite(Number(v))?Number(v):0;
const dateOnly=v=>String(v||'').slice(0,10);
const monthKey=(d=new Date())=>d.toISOString().slice(0,7);

async function prefs(){const r=await api.get('user_preferences',{select:'*',athlete_id:`eq.${uid()}`,limit:1}).catch(()=>[]);return r[0]||null}
async function savePrefs(patch){const p=await prefs();if(p)return api.patch('user_preferences',{athlete_id:`eq.${uid()}`},patch);return api.post('user_preferences',{athlete_id:uid(),...patch})}

A.register('more',async()=>{state.view='more';shell(`<div class="sectionHead"><div><div class="eyebrow">PT-PRO 10 CLOUD</div><h1>Centro Controllo PRO</h1><span class="muted">Tutto PT-PRO, organizzato senza duplicati</span></div><button class="btn secondary" data-route="search">⌕ Cerca</button></div>
<div class="proSections">
<section><div class="sectionHead"><h2>Performance</h2></div><div class="toolGrid">${tools([
['coach-smart','🧠','Smart Coach PRO','Readiness, e1RM, RIR, trend e prescrizioni'],['reports','📊','Report & Analytics','Mensile, annuale e volume muscolare'],['progress','📈','Centro Progressi','Misure, PR, obiettivi, check-in e foto'],['calendar','📅','Calendario','Allenamenti, check-in ed eventi']])}</div></section>
<section><div class="sectionHead"><h2>Programmazione</h2></div><div class="toolGrid">${tools([
['data-manager','🧱','Gestione Schede','Crea, modifica, attiva e struttura schede'],['exercises','🏋️','Libreria Esercizi','Immagini, tecnica, gruppi e attrezzatura'],['nutrition','🥗','Nutrizione PRO','Oggi, piano, ricette, dispensa e integratori'],['nutrition-planner','🗓️','Planner Nutrizione','Settimana, mese e lista spesa']])}</div></section>
<section><div class="sectionHead"><h2>Account e strumenti</h2></div><div class="toolGrid">${tools([
['profile-pro','👤','Profilo','Dati personali e preferenze'],['appearance','◐','Aspetto','Auto, scuro o chiaro'],['notifications','🔔','Notifiche','Centro notifiche intelligente'],['quick-actions','⚡','Azioni rapide','Personalizza le scorciatoie'],['coach','👥','Modalità Coach','Atleti, note e permessi'],['trash','🗑️','Cestino','Elementi eliminati e ripristino'],['integrity','🛡️','Integrità','Controllo dati e relazioni'],['backup','↓','Backup completo','Esporta tutti i dati'],['system-pro','⚙️','Sistema','Versione, cloud e diagnostica']])}</div></section>
</div>`);A.bindRoutes()});
function tools(arr){return arr.map(([r,i,t,s])=>`<button class="dayCard" data-route="${r}"><div><b>${i} ${t}</b><span>${s}</span></div></button>`).join('')}

A.register('profile-pro',async()=>{state.view='more';const p=state.boot.profile||{},pr=await prefs();shell(`<div class="sectionHead"><div><h1>Profilo PRO</h1><span class="muted">Identità, allenamento e preferenze</span></div></div><div class="card"><div class="formGrid"><label>Nome visualizzato<input id="pfName" value="${esc(p.display_name||p.first_name||'')}"></label><label>Altezza cm<input id="pfHeight" type="number" value="${esc(p.height_cm||'')}"></label><label>Modalità sforzo<select id="pfEff"><option value="RIR" ${pr?.effort_mode==='RIR'?'selected':''}>RIR</option><option value="RPE" ${pr?.effort_mode==='RPE'?'selected':''}>RPE</option></select></label><label>Tema<select id="pfTheme"><option value="auto">Automatico</option><option value="dark">Scuro</option><option value="light">Chiaro</option></select></label></div><label>Note<textarea id="pfNotes" class="textarea">${esc(p.notes||'')}</textarea></label><button class="btn primary full" id="pfSave">Salva profilo</button></div>`);const t=document.getElementById('pfTheme');if(pr?.theme_mode)t.value=pr.theme_mode;document.getElementById('pfSave').onclick=async()=>{const name=document.getElementById('pfName').value.trim(),height=Number(document.getElementById('pfHeight').value||0),notes=document.getElementById('pfNotes').value;await api.patch('profiles',{id:`eq.${uid()}`},{display_name:name,height_cm:height||null,notes});await savePrefs({effort_mode:document.getElementById('pfEff').value,theme_mode:t.value});applyTheme(t.value);await A.refresh();toast('Profilo aggiornato ✓');go('profile-pro')}});

A.register('appearance',async()=>{state.view='more';const p=await prefs(),mode=p?.theme_mode||'auto';shell(`<div class="sectionHead"><div><h1>Aspetto</h1><span class="muted">Tema e leggibilità</span></div></div><div class="card"><div class="themeGrid">${[['auto','◐','Automatico'],['dark','●','Scuro'],['light','○','Chiaro']].map(([v,i,l])=>`<button class="dayCard ${mode===v?'selected':''}" data-theme="${v}"><div><b>${i} ${l}</b><span>${v==='auto'?'Segue ora/dispositivo':'Tema '+l.toLowerCase()}</span></div></button>`).join('')}</div></div>`);document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=async()=>{await savePrefs({theme_mode:b.dataset.theme});applyTheme(b.dataset.theme);toast('Aspetto aggiornato');go('appearance')})});
function applyTheme(mode){let m=mode;if(mode==='auto')m=window.matchMedia?.('(prefers-color-scheme: light)').matches?'light':'dark';document.documentElement.dataset.theme=m}

A.register('coach-smart',async()=>{state.view='more';loading('Smart Coach PRO analizza i tuoi dati…');const [sets,exercises,vols]=await Promise.all([api.get('workout_sets',{select:'exercise_id,exercise_name_snapshot,load,reps,rir,estimated_1rm,logged_at',athlete_id:`eq.${uid()}`,order:'logged_at.desc',limit:400}).catch(()=>[]),api.exerciseCatalog(),api.get('v_weekly_training_volume',{select:'*',athlete_id:`eq.${uid()}`,order:'week_start.desc',limit:12}).catch(()=>[])]);const em=new Map(exercises.map(x=>[x.id,x])),groups=new Map();for(const s of sets){if(!groups.has(s.exercise_id))groups.set(s.exercise_id,[]);groups.get(s.exercise_id).push(s)}const rows=[];for(const [id,arr] of groups){const recent=arr.slice(0,12),latest=recent.slice(0,4),older=recent.slice(4,8),best=a=>Math.max(0,...a.map(x=>asNum(x.estimated_1rm)||asNum(x.load)*(1+asNum(x.reps)/30))),a=best(latest),b=best(older),trend=b?((a-b)/b*100):0,rir=latest.map(x=>Number(x.rir)).filter(Number.isFinite),avg=rir.length?rir.reduce((x,y)=>x+y,0)/rir.length:null;let status='Mantieni',advice='Consolida tecnica e ripetizioni.';if(trend>2&&(avg==null||avg>=1.5)){status='Progressione';advice='Aumenta il carico circa 2–2,5% oppure aggiungi una ripetizione.'}else if(trend<-3||(avg!=null&&avg<0.75)){status='Recupero';advice='Riduci 2,5–5% e mantieni più margine.'}rows.push({id,name:em.get(id)?.name||recent[0]?.exercise_name_snapshot||'Esercizio',group:em.get(id)?.muscle_group||'',trend,avg,best:a,status,advice})}rows.sort((a,b)=>Math.abs(b.trend)-Math.abs(a.trend));const r=A.readiness(),ad=A.smartAdvice(r);shell(`<div class="sectionHead"><div><h1>Smart Coach PRO</h1><span class="muted">Storico, e1RM, RIR, recupero e volume in un'unica analisi</span></div></div><div class="coach big"><div class="coachScore">${r}</div><div><b>${ad[0]}</b><p>${ad[1]}</p></div></div><div class="kpis four"><div class="kpi"><b>${rows.filter(x=>x.status==='Progressione').length}</b><span>Progressioni</span></div><div class="kpi"><b>${rows.filter(x=>x.status==='Recupero').length}</b><span>Attenzioni</span></div><div class="kpi"><b>${sets.length}</b><span>Set analizzati</span></div><div class="kpi"><b>${vols[0]?.total_volume?fmt(vols[0].total_volume,0):'—'}</b><span>Volume settimana</span></div></div><section class="section"><div class="sectionHead"><h2>Prescrizioni esercizi</h2><span class="muted">ultimi dati disponibili</span></div><div class="card list">${rows.slice(0,30).map(x=>`<div class="proInsight"><div><b>${esc(x.name)}</b><span>${esc(x.group)} · e1RM ${fmt(x.best)} · RIR ${x.avg==null?'—':fmt(x.avg)}</span><small>${esc(x.advice)}</small></div><div class="trend ${x.trend>1?'up':x.trend<-1?'down':''}">${x.trend>=0?'+':''}${fmt(x.trend)}%</div></div>`).join('')||'<div class="empty">Registra più allenamenti per attivare l’analisi.</div>'}</div></section>`)});

A.register('reports',async()=>{state.view='more';loading('Genero report PRO…');const [sessions,sets,measures,vols,ex]=await Promise.all([api.get('workout_sessions',{select:'*',athlete_id:`eq.${uid()}`,order:'started_at.desc',limit:500}),api.get('workout_sets',{select:'*',athlete_id:`eq.${uid()}`,order:'logged_at.desc',limit:1500}),api.get('measurements',{select:'*',athlete_id:`eq.${uid()}`,order:'measured_on.desc',limit:200}),api.get('v_weekly_training_volume',{select:'*',athlete_id:`eq.${uid()}`,order:'week_start.desc',limit:60}).catch(()=>[]),api.exerciseCatalog()]);const mk=monthKey(),ms=sessions.filter(x=>dateOnly(x.started_at).startsWith(mk)),msets=sets.filter(x=>dateOnly(x.logged_at).startsWith(mk)),volume=msets.reduce((a,x)=>a+asNum(x.load)*asNum(x.reps),0),mins=ms.reduce((a,x)=>a+asNum(x.duration_minutes),0),completion=ms.length?Math.round(ms.reduce((a,x)=>a+asNum(x.completion_percent),0)/ms.length):0,year=new Date().getFullYear(),ys=sessions.filter(x=>dateOnly(x.started_at).startsWith(String(year))),monthCounts=Array.from({length:12},(_,i)=>ys.filter(x=>new Date(x.started_at).getMonth()===i).length),max=Math.max(1,...monthCounts),em=new Map(ex.map(x=>[x.id,x])),byMuscle={};for(const s of msets){const g=em.get(s.exercise_id)?.muscle_group||'Altro';byMuscle[g]=(byMuscle[g]||0)+asNum(s.load)*asNum(s.reps)}const weightNow=measures[0]?.weight_kg,weightOld=[...measures].reverse().find(x=>dateOnly(x.measured_on).startsWith(mk))?.weight_kg;shell(`<div class="sectionHead"><div><h1>Report & Analytics PRO</h1><span class="muted">Mensile, annuale e volume muscolare</span></div></div><div class="kpis four"><div class="kpi"><b>${ms.length}</b><span>Workout mese</span></div><div class="kpi"><b>${fmt(volume,0)} kg</b><span>Volume mese</span></div><div class="kpi"><b>${mins}′</b><span>Minuti mese</span></div><div class="kpi"><b>${completion}%</b><span>Completamento medio</span></div></div><section class="section"><div class="sectionHead"><h2>Dashboard annuale ${year}</h2></div><div class="bars">${monthCounts.map((v,i)=>`<div class="barCol"><div class="bar" style="height:${Math.max(4,Math.round(v/max*100))}%"></div><b>${v}</b><span>${['G','F','M','A','M','G','L','A','S','O','N','D'][i]}</span></div>`).join('')}</div></section><section class="section"><div class="sectionHead"><h2>Volume muscolare del mese</h2></div><div class="card list">${Object.entries(byMuscle).sort((a,b)=>b[1]-a[1]).map(([g,v])=>`<div class="row"><span>${esc(g)}</span><b>${fmt(v,0)} kg</b></div>`).join('')||'<div class="empty">Nessun volume disponibile.</div>'}</div></section><section class="section"><div class="card"><b>Trend peso</b><p class="muted">${weightNow&&weightOld?`${fmt(weightOld)} → ${fmt(weightNow)} kg (${asNum(weightNow)-asNum(weightOld)>=0?'+':''}${fmt(asNum(weightNow)-asNum(weightOld))} kg)`:'Dati insufficienti nel mese corrente.'}</p></div></section>`)});

A.register('data-manager',async()=>{state.view='more';loading('Carico gestione schede…');const plans=await api.get('workout_plans',{select:'*',athlete_id:`eq.${uid()}`,archived_at:'is.null',order:'active.desc,created_at.desc'});shell(`<div class="sectionHead"><div><h1>Gestione Schede PRO</h1><span class="muted">Builder completo Cloud</span></div><button class="btn primary" id="newPlan">+ Scheda</button></div><div class="card list">${plans.map(p=>`<div class="manageRow"><div><b>${esc(p.title)}</b><span>${esc(p.phase||'')} · ${esc(p.goal||'')}${p.active?' · ATTIVA':''}</span></div><div class="manageButtons"><button class="btn secondary" data-structure="${p.id}">Struttura</button>${!p.active?`<button class="btn secondary" data-active="${p.id}">Attiva</button>`:''}<button class="btn secondary dangerText" data-archive="${p.id}">Archivia</button></div></div>`).join('')||'<div class="empty">Nessuna scheda.</div>'}</div>`);document.getElementById('newPlan').onclick=newPlan;document.querySelectorAll('[data-structure]').forEach(b=>b.onclick=()=>go('plan-builder',b.dataset.structure));document.querySelectorAll('[data-active]').forEach(b=>b.onclick=async()=>{await api.patch('workout_plans',{athlete_id:`eq.${uid()}`,active:'eq.true'},{active:false});await api.patch('workout_plans',{id:`eq.${b.dataset.active}`},{active:true});await A.refresh();toast('Scheda attivata');go('data-manager')});document.querySelectorAll('[data-archive]').forEach(b=>b.onclick=async()=>{if(!confirm('Archiviare questa scheda?'))return;await api.patch('workout_plans',{id:`eq.${b.dataset.archive}`},{active:false,archived_at:new Date().toISOString()});await A.refresh();go('data-manager')})});
function newPlan(){const m=modal('Nuova scheda',`<label>Titolo<input id="npTitle" placeholder="Es. Fase 2 — Forza"></label><div class="formGrid"><label>Fase<input id="npPhase"></label><label>Obiettivo<input id="npGoal"></label><label>Giorni/settimana<input id="npDays" type="number" min="1" max="7" value="3"></label><label>Durata sessione<input id="npMin" type="number" value="60"></label></div><label>Note<textarea id="npNotes" class="textarea"></textarea></label><button class="btn primary full" id="npSave">Crea scheda</button>`);m.querySelector('#npSave').onclick=async()=>{const title=m.querySelector('#npTitle').value.trim();if(!title)return toast('Inserisci un titolo','err');await api.post('workout_plans',{athlete_id:uid(),title,phase:m.querySelector('#npPhase').value,goal:m.querySelector('#npGoal').value,days_per_week:Number(m.querySelector('#npDays').value||3),session_minutes:Number(m.querySelector('#npMin').value||60),notes:m.querySelector('#npNotes').value,active:false});m.remove();go('data-manager')}}

A.register('plan-builder',async(planId)=>{state.view='more';loading('Carico struttura scheda…');const [plans,days,catalog]=await Promise.all([api.get('workout_plans',{select:'*',id:`eq.${planId}`,limit:1}),api.get('workout_days',{select:'*',plan_id:`eq.${planId}`,archived_at:'is.null',order:'sort_order.asc'}),api.exerciseCatalog()]);const p=plans[0];if(!p)throw Error('Scheda non trovata');const dayItems={};for(const d of days)dayItems[d.id]=await api.get('workout_items',{select:'*',day_id:`eq.${d.id}`,archived_at:'is.null',order:'sort_order.asc'});const em=new Map(catalog.map(x=>[x.id,x]));shell(`<div class="sectionHead"><div><div class="eyebrow">Builder scheda</div><h1>${esc(p.title)}</h1><span class="muted">${esc(p.phase||'')} · ${esc(p.goal||'')}</span></div><button class="btn primary" id="addDay">+ Giorno</button></div><div class="builderDays">${days.map((d,di)=>`<section class="card builderDay"><div class="sectionHead"><div><b>${di+1}. ${esc(d.name)}</b><span>${esc(d.focus||'')}</span></div><button class="btn secondary" data-add-item="${d.id}">+ Esercizio</button></div><div class="list">${(dayItems[d.id]||[]).map((it,ii)=>{const e=em.get(it.exercise_id)||{};return `<div class="manageRow"><div><b>${ii+1}. ${esc(e.name||'Esercizio')}</b><span>${it.sets} × ${esc(it.reps_text||'')} · recupero ${it.rest_seconds||'—'}s · ${esc(it.technique_type||'standard')}</span></div><button class="iconBtn dangerText" data-remove-item="${it.id}">✕</button></div>`}).join('')||'<div class="empty">Nessun esercizio.</div>'}</div></section>`).join('')||'<div class="card empty">Aggiungi il primo giorno.</div>'}</div>`);document.getElementById('addDay').onclick=()=>addDay(planId,days.length);document.querySelectorAll('[data-add-item]').forEach(b=>b.onclick=()=>addItem(planId,b.dataset.addItem,catalog,(dayItems[b.dataset.addItem]||[]).length));document.querySelectorAll('[data-remove-item]').forEach(b=>b.onclick=async()=>{await api.patch('workout_items',{id:`eq.${b.dataset.removeItem}`},{archived_at:new Date().toISOString()});go('plan-builder',planId)})});
function addDay(planId,n){const m=modal('Nuovo giorno',`<label>Nome<input id="dName" placeholder="Giorno A — Petto + Spalle"></label><label>Focus<input id="dFocus" placeholder="push"></label><button class="btn primary full" id="dSave">Aggiungi</button>`);m.querySelector('#dSave').onclick=async()=>{await api.post('workout_days',{athlete_id:uid(),plan_id:planId,name:m.querySelector('#dName').value.trim()||`Giorno ${n+1}`,focus:m.querySelector('#dFocus').value,sort_order:n+1});m.remove();go('plan-builder',planId)}}
function addItem(planId,dayId,catalog,n){const m=modal('Aggiungi esercizio',`<input class="search" id="pickSearch" placeholder="Cerca esercizio…"><div id="pickList" class="pickerList"></div>`);const draw=q=>{const list=catalog.filter(e=>!q||`${e.name} ${e.muscle_group||''}`.toLowerCase().includes(q.toLowerCase())).slice(0,80);m.querySelector('#pickList').innerHTML=list.map(e=>`<button class="pickRow" data-pick="${e.id}">${e.image_url?`<img src="${esc(e.image_url)}" loading="lazy">`:''}<span><b>${esc(e.name)}</b><small>${esc(e.muscle_group||'')} · ${esc(e.equipment||'')}</small></span></button>`).join('');m.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>configureItem(dayId,b.dataset.pick,n,m))};m.querySelector('#pickSearch').oninput=e=>draw(e.target.value);draw('')}
function configureItem(dayId,exerciseId,n,old){old.remove();const m=modal('Configura esercizio',`<div class="formGrid"><label>Serie<input id="iSets" type="number" value="3"></label><label>Ripetizioni<input id="iReps" value="8–10"></label><label>Recupero sec<input id="iRest" type="number" value="90"></label><label>RIR target<input id="iRir" type="number" step="0.5" value="2"></label><label>Tecnica<select id="iTech"><option value="standard">Standard</option><option value="superset">Superset</option><option value="dropset">Dropset</option><option value="rest_pause">Rest-pause</option></select></label><label>Tempo<input id="iTempo" placeholder="3-1-1"></label></div><button class="btn primary full" id="iSave">Aggiungi</button>`);m.querySelector('#iSave').onclick=async()=>{await api.post('workout_items',{athlete_id:uid(),day_id:dayId,exercise_id:exerciseId,sort_order:n+1,sets:Number(m.querySelector('#iSets').value||3),reps_text:m.querySelector('#iReps').value,rest_seconds:Number(m.querySelector('#iRest').value||90),target_rir:Number(m.querySelector('#iRir').value||2),technique_type:m.querySelector('#iTech').value,tempo:m.querySelector('#iTempo').value,warmup_enabled:true});m.remove();const d=(await api.get('workout_days',{select:'plan_id',id:`eq.${dayId}`,limit:1}))[0];go('plan-builder',d.plan_id)}}

A.register('nutrition-planner',async()=>{state.view='more';loading('Carico planner nutrizione…');const d=await api.nutrition(uid()),p=d.plans.find(x=>x.active)||d.plans[0]||{};shell(`<div class="sectionHead"><div><h1>Planner Nutrizione PRO</h1><span class="muted">Giorno, settimana, mese e lista spesa</span></div></div><div class="card"><div class="formGrid"><label>Tipo giorni ON<input id="onDays" value="1,3,5"></label><label>Modalità<select id="planMode"><option value="week">Settimana</option><option value="month">Mese</option></select></label></div><button class="btn primary full" id="generatePlan">Genera piano</button></div><div id="plannerResult"></div>`);document.getElementById('generatePlan').onclick=async()=>{const mode=document.getElementById('planMode').value,count=mode==='week'?7:new Date(new Date().getFullYear(),new Date().getMonth()+1,0).getDate(),base=new Date(),days=[];toast('Genero piano…');for(let i=0;i<count;i++){const dt=new Date(base);dt.setDate(base.getDate()+i);const ds=dt.toISOString().slice(0,10),dow=dt.getDay()===0?7:dt.getDay(),on=document.getElementById('onDays').value.split(',').map(Number).includes(dow);await api.createNutritionDay(uid(),p,ds,on?'ON':'OFF');days.push({date:ds,type:on?'ON':'OFF'})}document.getElementById('plannerResult').innerHTML=`<section class="section"><div class="sectionHead"><h2>${mode==='week'?'Settimana':'Mese'} generato</h2><button class="btn secondary" id="shopFromPlan">Lista spesa</button></div><div class="monthGrid">${days.map(x=>`<div class="monthDay ${x.type.toLowerCase()}"><b>${esc(x.date)}</b><span>${x.type}</span></div>`).join('')}</div></section>`;document.getElementById('shopFromPlan').onclick=()=>shoppingFromDays(days)}});
async function shoppingFromDays(days){const names=new Map();for(const d of days){const nd=await api.nutritionDay(uid(),d.date).catch(()=>null);for(const m of nd?.meals||[])for(const i of m.items||[]){const key=i.food_name_snapshot||'Alimento';names.set(key,(names.get(key)||0)+asNum(i.quantity))}}const list=[...names.entries()];modal('Lista spesa',`<div class="list">${list.map(([n,q])=>`<div class="row"><span>${esc(n)}</span><b>${fmt(q,0)} g</b></div>`).join('')||'<div class="empty">Le giornate non contengono ancora alimenti assegnati.</div>'}</div>`)}

A.register('quick-actions',async()=>{state.view='more';const p=await prefs(),cur=Array.isArray(p?.quick_actions)?p.quick_actions:[];const opts=[['workout','🏋️ Allenamento'],['progress','📈 Progressi'],['nutrition','🥗 Nutrizione'],['search','⌕ Ricerca'],['calendar','📅 Calendario'],['notifications','🔔 Notifiche'],['coach-smart','🧠 Smart Coach'],['data-manager','🧱 Schede']];shell(`<div class="sectionHead"><div><h1>Azioni rapide</h1><span class="muted">Scegli fino a 4 scorciatoie</span></div></div><div class="card">${opts.map(([v,l])=>`<label class="checkRow"><input type="checkbox" value="${v}" ${cur.includes(v)?'checked':''}><span>${l}</span></label>`).join('')}<button class="btn primary full" id="qaSave">Salva</button></div>`);document.getElementById('qaSave').onclick=async()=>{const vals=[...document.querySelectorAll('.checkRow input:checked')].slice(0,4).map(x=>x.value);await savePrefs({quick_actions:vals});toast('Azioni rapide salvate')}});

A.register('trash',async()=>{state.view='more';const rows=await api.get('trash',{select:'*',athlete_id:`eq.${uid()}`,restored_at:'is.null',order:'deleted_at.desc',limit:100}).catch(()=>[]);shell(`<div class="sectionHead"><div><h1>Cestino</h1><span class="muted">Conservazione 30 giorni</span></div></div><div class="card list">${rows.map(x=>`<div class="row"><span><b>${esc(x.entity_type)}</b><br><small>${new Date(x.deleted_at).toLocaleString('it-IT')}</small></span><b>${esc(x.entity_id||'')}</b></div>`).join('')||'<div class="empty">Cestino vuoto.</div>'}</div>`)});

A.register('integrity',async()=>{state.view='more';loading('Controllo integrità…');const [plans,days,items,ex,sessions,sets]=await Promise.all([api.get('workout_plans',{select:'id,athlete_id',athlete_id:`eq.${uid()}`}),api.get('workout_days',{select:'id,plan_id,athlete_id',athlete_id:`eq.${uid()}`}),api.get('workout_items',{select:'id,day_id,exercise_id,athlete_id',athlete_id:`eq.${uid()}`}),api.exerciseCatalog(),api.get('workout_sessions',{select:'id,day_id,plan_id',athlete_id:`eq.${uid()}`,limit:1000}),api.get('workout_sets',{select:'id,session_id,exercise_id',athlete_id:`eq.${uid()}`,limit:3000})]);const ps=new Set(plans.map(x=>x.id)),ds=new Set(days.map(x=>x.id)),es=new Set(ex.map(x=>x.id)),ss=new Set(sessions.map(x=>x.id));const issues=[['Giorni senza scheda',days.filter(x=>!ps.has(x.plan_id)).length],['Esercizi workout senza giorno',items.filter(x=>!ds.has(x.day_id)).length],['Riferimenti esercizio mancanti',items.filter(x=>!es.has(x.exercise_id)).length],['Set senza sessione',sets.filter(x=>!ss.has(x.session_id)).length],['Set con esercizio mancante',sets.filter(x=>!es.has(x.exercise_id)).length]];const total=issues.reduce((a,x)=>a+x[1],0);shell(`<div class="sectionHead"><div><h1>Integrità dati</h1><span class="muted">Controllo relazioni Cloud</span></div></div><div class="coach big"><div class="coachScore">${total?'!':'✓'}</div><div><b>${total?`${total} anomalie da verificare`:'Database coerente'}</b><p>${total?'Nessun dato viene modificato automaticamente.':'Tutti i controlli principali sono superati.'}</p></div></div><div class="card list">${issues.map(([n,v])=>`<div class="row"><span>${n}</span><b>${v}</b></div>`).join('')}</div>`)});

A.register('system-pro',async()=>{state.view='more';const c=JSON.parse(localStorage.getItem('ptpro10_supabase_config')||'{}'),s=JSON.parse(localStorage.getItem('ptpro10_session')||'{}');shell(`<div class="sectionHead"><div><h1>Sistema</h1><span class="muted">Diagnostica PT-PRO 10 Cloud</span></div></div><div class="card list"><div class="row"><span>Versione runtime</span><b>${esc(window.PTPRO_APP_VERSION||'10')}</b></div><div class="row"><span>Supabase</span><b>${c.url?'Connesso':'Non configurato'}</b></div><div class="row"><span>Sessione</span><b>${s.access_token?'Autenticata':'Assente'}</b></div><div class="row"><span>Utente</span><b>${esc(state.boot.profile?.display_name||state.boot.profile?.first_name||'PT-PRO')}</b></div><div class="row"><span>Esercizi</span><b>${state.catalog?.length||'caricamento su richiesta'}</b></div></div><button class="btn primary full" id="sysReload">Ricarica dati Cloud</button>`);document.getElementById('sysReload').onclick=async()=>{loading('Aggiorno…');await A.refresh();toast('Dati aggiornati');go('system-pro')}});

setTimeout(async()=>{try{const p=await prefs();if(p?.theme_mode)applyTheme(p.theme_mode)}catch{}},300);
})();