(() => {
'use strict';
const A=window.PTAPP;if(!A)return;const {state,esc,shell,toast,modal}=A;
const LS={assess:'ptpro11_school_assessments',tests:'ptpro11_school_test_results'};
const lessons=[
{school:'I grado',sport:'Atletica',title:'Velocità e staffette',goal:'Coordinazione, rapidità, collaborazione',steps:['Riscaldamento ludico 10′','Andature e skip 10′','Sprint 20–30 m 10′','Staffette 20′','Defaticamento 5′']},
{school:'I grado',sport:'Pallavolo',title:'Bagher e palleggio',goal:'Fondamentali e cooperazione',steps:['Mobilità 8′','Palleggio a coppie 12′','Bagher a bersaglio 15′','Servizio dal basso 10′','Mini-volley 15′']},
{school:'I grado',sport:'Basket',title:'Palleggio e passaggio',goal:'Controllo palla e orientamento',steps:['Gioco attivazione 8′','Circuito palleggio 12′','Passaggi 10′','Arresto + terzo tempo 10′','3 contro 3 20′']},
{school:'I grado',sport:'Calcio',title:'Guida, passaggio e tiro',goal:'Dominio palla e collaborazione',steps:['Conduzione libera 8′','Slalom 10′','Passaggio a coppie 12′','Tiro a bersaglio 10′','Partita 4v4 20′']},
{school:'I grado',sport:'Badminton',title:'Racchetta e traiettorie',goal:'Coordinazione occhio-mano',steps:['Mobilità 8′','Presa e palleggi 10′','Servizio 10′','Scambi a metà campo 15′','Mini-partite 15′']},
{school:'II grado',sport:'Calcio',title:'Tecnica + small sided games',goal:'Tecnica, decision making, intensità',steps:['Rondo 10′','Tecnica analitica 10′','1v1/2v2 15′','4v4 20′','Mobilità 5′']},
{school:'II grado',sport:'Atletica',title:'Resistenza e pacing',goal:'Gestione dello sforzo e autonomia',steps:['Warm-up 10′','Tecnica 8′','Intervalli 6×2′/1′','Pacing finale 8′','Defaticamento 8′']},
{school:'II grado',sport:'Fitness',title:'Circuit training scolastico',goal:'Forza generale e autoregolazione',steps:['Mobilità 8′','Circuito 8 stazioni × 35″/25″','Recupero 3′','Secondo giro','Stretching 6′']},
{school:'II grado',sport:'Pallavolo',title:'Ricezione, alzata e attacco',goal:'Sequenza tecnica e gioco di squadra',steps:['Warm-up 8′','Ricezione a zone 12′','Alzata 10′','Rincorsa e attacco 12′','4v4 18′']},
{school:'II grado',sport:'Basket',title:'Transizione e tiro',goal:'Velocità decisionale e precisione',steps:['Warm-up con palla 8′','Contropiede 3 corsie 12′','Tiro in arresto 12′','1v1 da vantaggio 10′','4v4 18′']}
];
const fundamentals={
'Atletica':['skip e andature','partenza','accelerazione','corsa ritmica','stacco e atterraggio','lancio'],
'Calcio':['guida palla','passaggio','ricezione orientata','dribbling','tiro','smarcamento'],
'Basket':['palleggio','passaggio','arresto','terzo tempo','tiro','difesa individuale'],
'Pallavolo':['palleggio','bagher','servizio','ricezione','rincorsa','attacco'],
'Tennis':['presa','diritto','rovescio','servizio','volée','spostamenti'],
'Padel':['diritto','rovescio','servizio','volée','bandeja','uso pareti'],
'Badminton':['presa','clear','drop','servizio','smash','footwork'],
'Nuoto':['assetto','respirazione','presa','trazione','battuta gambe','virata'],
'Ginnastica/Fitness':['squat','affondo','push-up','plank','hip hinge','mobilità'],
'Ultimate':['presa','lancio dritto','lancio rovescio','pivot','smarcamento','fair play']
};
const tests=[
{name:'30 m sprint',capacity:'Velocità',unit:'s',protocol:'Partenza alta, 30 m lineari, 2 prove con recupero completo; registra la migliore.'},
{name:'Salto in lungo da fermo',capacity:'Potenza arti inferiori',unit:'cm',protocol:'Piedi paralleli dietro la linea, slancio libero, misura dal tallone più arretrato.'},
{name:'Shuttle 10×5 m',capacity:'Agilità',unit:'s',protocol:'Due linee a 5 m, 10 percorrenze totali con cambi direzione; cronometra il tempo.'},
{name:'Cooper 12 minuti',capacity:'Resistenza',unit:'m',protocol:'Percorri la massima distanza sostenibile in 12 minuti su tracciato misurato.'},
{name:'Sit and reach',capacity:'Mobilità',unit:'cm',protocol:'Ginocchia estese, avanzamento lento delle mani; evita molleggi.'},
{name:'Plank',capacity:'Core endurance',unit:'s',protocol:'Allineamento testa-tronco-bacino; termina quando la tecnica non è più mantenuta.'}
];
const games=[
{name:'Palla prigioniera evoluta',focus:'Reazione, lancio, collaborazione',rule:'Chi viene colpito svolge un compito motorio breve e rientra: nessuna eliminazione lunga.'},
{name:'Rubabandiera motorio',focus:'Velocità e decisione',rule:'Associa a ogni numero un compito: corsa, skip, laterale o slalom prima della conquista.'},
{name:'Circuito semaforo',focus:'Coordinazione e attenzione',rule:'Verde=corsa, giallo=andatura tecnica, rosso=equilibrio; cambia segnale rapidamente.'},
{name:'Caccia ai coni',focus:'Rapidità e orientamento',rule:'Squadre raccolgono un cono alla volta; varianti con colori, direzioni e gesti tecnici.'},
{name:'Ultimate semplificato',focus:'Spazi, smarcamento e fair play',rule:'Non si corre con il disco/palla; punto dopo ricezione in zona meta.'},
{name:'Memory motorio',focus:'Anatomia + movimento',rule:'Abbina carta-muscolo e carta-funzione; dopo l’abbinamento esegui un gesto collegato.'},
{name:'Torre dei passaggi',focus:'Cooperazione e precisione',rule:'La squadra conquista un punto dopo 6 passaggi consecutivi senza intercetto.'},
{name:'Bingo motorio',focus:'Varietà motoria',rule:'Ogni casella contiene un compito: equilibrio, salto, lancio, mobilità o sprint breve.'}
];
const anatomy=[
{q:'Quadricipite',a:'Estende il ginocchio',wrong:['Flette il gomito','Muove principalmente la spalla','Ruota il polso']},
{q:'Bicipite femorale',a:'Flette il ginocchio e contribuisce all’estensione dell’anca',wrong:['Estende il gomito','Eleva la scapola','Flette il polso']},
{q:'Glutei',a:'Estendono e stabilizzano l’anca',wrong:['Estendono il gomito','Flettono le dita','Muovono principalmente la mandibola']},
{q:'Polpacci',a:'Contribuiscono alla spinta della caviglia',wrong:['Estendono il polso','Flettono il gomito','Ruotano la spalla']},
{q:'Deltoide',a:'Partecipa ai movimenti della spalla',wrong:['Estende il ginocchio','Flette le dita del piede','Muove la mandibola']},
{q:'Core',a:'Stabilizza tronco e bacino',wrong:['Produce solo movimenti del collo','Serve solo alla respirazione','Muove esclusivamente le dita']},
{q:'Tricipite',a:'Estende il gomito',wrong:['Flette il ginocchio','Estende la caviglia','Ruota il bacino']},
{q:'Gran dorsale',a:'Contribuisce a tirare il braccio verso il corpo',wrong:['Estende il ginocchio','Flette la caviglia','Muove solo le dita']}
];
const safeJSON=(key)=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}};
const cardList=(arr,fn)=>`<div class="toolGrid">${arr.map(fn).join('')}</div>`;
A.register('school',()=>{state.view='school';const aCount=safeJSON(LS.assess).length,tCount=safeJSON(LS.tests).length;shell(`<div class="sectionHead"><div><div class="eyebrow">PT-PRO SCUOLA</div><h1>Area Docenti</h1><span class="muted">Secondaria di I e II grado · lezioni, sport, test, valutazioni, giochi e anatomia interattiva.</span></div><button class="btn primary" id="lessonBuilder">Genera lezione</button></div><div class="kpis four"><div class="kpi"><b>${lessons.length}</b><span>Lezioni pronte</span></div><div class="kpi"><b>${tests.length}</b><span>Test motori</span></div><div class="kpi"><b>${aCount}</b><span>Valutazioni salvate</span></div><div class="kpi"><b>${tCount}</b><span>Risultati test</span></div></div><section class="section"><div class="sectionHead"><h2>Lezioni e unità didattiche</h2></div>${cardList(lessons,(x,i)=>`<button class="dayCard" data-lesson="${i}"><div><b>${esc(x.sport)} · ${esc(x.title)}</b><span>${esc(x.school)} · ${esc(x.goal)}</span></div></button>`)}</section><section class="section"><div class="sectionHead"><h2>Fondamentali per sport</h2></div>${cardList(Object.entries(fundamentals),([sport,items])=>`<button class="dayCard" data-fund="${esc(sport)}"><div><b>🏅 ${esc(sport)}</b><span>${esc(items.join(' · '))}</span></div></button>`)}</section><section class="section"><div class="sectionHead"><h2>Test atletici e motori</h2><div class="manageButtons"><button class="btn secondary" id="openEval">Scheda valutazione</button><button class="btn secondary" id="historyEval">Storico</button></div></div>${cardList(tests,(x,i)=>`<button class="dayCard" data-test="${i}"><div><b>${esc(x.name)}</b><span>${esc(x.capacity)} · ${esc(x.unit)}</span></div></button>`)}</section><section class="section"><div class="sectionHead"><h2>Giochi ludico-motori</h2></div>${cardList(games,(x,i)=>`<button class="dayCard" data-game="${i}"><div><b>🎲 ${esc(x.name)}</b><span>${esc(x.focus)}</span></div></button>`)}</section><section class="section"><div class="sectionHead"><h2>Anatomia semplice · gioco interattivo</h2><button class="btn primary" id="quizAnatomy">Avvia quiz</button></div><div class="card"><p class="muted">Domande casuali su muscoli e funzioni, utili per ripasso rapido alla LIM o da smartphone.</p></div></section>`);document.getElementById('lessonBuilder').onclick=lessonBuilder;document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>showLesson(lessons[+b.dataset.lesson]));document.querySelectorAll('[data-fund]').forEach(b=>b.onclick=()=>showFundamentals(b.dataset.fund));document.querySelectorAll('[data-test]').forEach(b=>b.onclick=()=>testInfo(+b.dataset.test));document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>showGame(+b.dataset.game));document.getElementById('openEval').onclick=assessment;document.getElementById('historyEval').onclick=history;document.getElementById('quizAnatomy').onclick=quiz});
function showLesson(x){if(!x)return;modal(x.title,`<p><b>${esc(x.school)} · ${esc(x.sport)}</b></p><p class="muted">Obiettivo: ${esc(x.goal)}</p><div class="list">${x.steps.map((s,i)=>`<div class="row"><span><b>${i+1}. ${esc(s)}</b></span></div>`).join('')}</div><div class="card" style="margin-top:12px"><b>Inclusione</b><p class="muted">Riduci distanza, velocità o complessità; usa coppie cooperative e compiti a livelli per mantenere tutti attivi.</p></div>`)}
function showFundamentals(sport){const items=fundamentals[sport]||[];modal(`Fondamentali · ${sport}`,`<div class="list">${items.map((x,i)=>`<div class="row"><span><b>${i+1}. ${esc(x)}</b><small>Dal gesto semplice alla situazione di gioco.</small></span></div>`).join('')}</div>`)}
function showGame(i){const x=games[i];if(!x)return;modal(x.name,`<div class="card"><p><b>Obiettivo:</b> ${esc(x.focus)}</p><p>${esc(x.rule)}</p><p class="muted">Adatta spazio, durata, numero di partecipanti e materiale alla classe.</p></div>`)}
function lessonBuilder(){const sports=Object.keys(fundamentals),box=modal('Generatore lezione',`<div class="formGrid"><label class="field">Scuola<select id="lbSchool"><option>I grado</option><option>II grado</option></select></label><label class="field">Sport<select id="lbSport">${sports.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label class="field">Durata minuti<input id="lbMin" type="number" min="30" max="120" value="60"></label><label class="field">Classe numerosa<select id="lbLarge"><option value="no">No</option><option value="yes">Sì</option></select></label></div><button class="btn primary full" id="lbGo">Crea lezione</button>`);box.querySelector('#lbGo').onclick=()=>{const school=box.querySelector('#lbSchool').value,sport=box.querySelector('#lbSport').value,mins=Math.max(30,+box.querySelector('#lbMin').value||60),large=box.querySelector('#lbLarge').value==='yes',f=fundamentals[sport]||[],warm=Math.round(mins*.15),tech=Math.round(mins*.3),game=Math.round(mins*.4),cool=Math.max(5,mins-warm-tech-game);box.remove();modal(`Lezione ${sport} · ${school}`,`<div class="list"><div class="row"><span><b>1. Attivazione · ${warm}′</b><small>Gioco breve + mobilità dinamica.</small></span></div><div class="row"><span><b>2. Fondamentali · ${tech}′</b><small>${esc(f.slice(0,3).join(', '))}.</small></span></div><div class="row"><span><b>3. Situazione / gioco · ${game}′</b><small>${large?'Organizza 3–4 stazioni per ridurre attese.':'Usa coppie, piccoli gruppi o mini-partite.'}</small></span></div><div class="row"><span><b>4. Defaticamento · ${cool}′</b><small>Mobilità, respirazione e feedback finale.</small></span></div></div>`)}}
function testInfo(i){const x=tests[i];if(!x)return;const box=modal(x.name,`<div class="card"><p><b>Capacità:</b> ${esc(x.capacity)}</p><p><b>Unità:</b> ${esc(x.unit)}</p><p>${esc(x.protocol)}</p></div><div class="formGrid"><label class="field">Studente<input id="trName"></label><label class="field">Classe<input id="trClass"></label><label class="field">Risultato<input id="trValue" type="number" step="0.01"></label><label class="field">Data<input id="trDate" type="date" value="${new Date().toISOString().slice(0,10)}"></label></div><button class="btn primary full" id="trSave">Salva risultato</button>`);box.querySelector('#trSave').onclick=()=>{const rec={test:x.name,capacity:x.capacity,unit:x.unit,name:box.querySelector('#trName').value.trim(),class:box.querySelector('#trClass').value.trim(),value:+box.querySelector('#trValue').value,date:box.querySelector('#trDate').value};if(!rec.name||!Number.isFinite(rec.value))return toast('Inserisci studente e risultato','err');const arr=safeJSON(LS.tests);arr.unshift(rec);localStorage.setItem(LS.tests,JSON.stringify(arr.slice(0,2000)));box.remove();toast('Risultato test salvato ✓')}}
function assessment(){const box=modal('Scheda di valutazione',`<div class="formGrid"><label class="field">Studente<input id="scName"></label><label class="field">Classe<input id="scClass"></label><label class="field">Tecnica 1–10<input id="scTech" type="number" min="1" max="10"></label><label class="field">Impegno 1–10<input id="scEff" type="number" min="1" max="10"></label><label class="field">Collaborazione 1–10<input id="scTeam" type="number" min="1" max="10"></label><label class="field">Autonomia 1–10<input id="scAuto" type="number" min="1" max="10"></label></div><label class="field">Note<textarea id="scNotes"></textarea></label><button class="btn primary full" id="scSave">Salva localmente</button>`);box.querySelector('#scSave').onclick=()=>{const vals=['#scTech','#scEff','#scTeam','#scAuto'].map(s=>+box.querySelector(s).value||null),rec={name:box.querySelector('#scName').value.trim(),class:box.querySelector('#scClass').value.trim(),tech:vals[0],effort:vals[1],team:vals[2],autonomy:vals[3],average:vals.filter(Boolean).length?+(vals.filter(Boolean).reduce((a,b)=>a+b,0)/vals.filter(Boolean).length).toFixed(1):null,notes:box.querySelector('#scNotes').value,at:new Date().toISOString()};if(!rec.name)return toast('Inserisci il nome dello studente','err');const arr=safeJSON(LS.assess);arr.unshift(rec);localStorage.setItem(LS.assess,JSON.stringify(arr.slice(0,2000)));box.remove();toast('Valutazione salvata ✓')}}
function history(){const a=safeJSON(LS.assess),t=safeJSON(LS.tests);modal('Storico scuola',`<div class="tabs"><button class="btn secondary">Valutazioni ${a.length}</button><button class="btn secondary">Test ${t.length}</button></div><div class="sectionHead"><h2>Ultime valutazioni</h2></div><div class="card list">${a.slice(0,20).map(x=>`<div class="row"><span><b>${esc(x.name)} · ${esc(x.class||'')}</b><small>${new Date(x.at).toLocaleDateString('it-IT')} · tecnica ${x.tech??'—'} · impegno ${x.effort??'—'} · collaborazione ${x.team??'—'}</small></span><b>${x.average??'—'}/10</b></div>`).join('')||'<div class="empty">Nessuna valutazione.</div>'}</div><div class="sectionHead" style="margin-top:18px"><h2>Ultimi test</h2></div><div class="card list">${t.slice(0,20).map(x=>`<div class="row"><span><b>${esc(x.name)} · ${esc(x.test)}</b><small>${esc(x.class||'')} · ${esc(x.date||'')}</small></span><b>${x.value} ${esc(x.unit)}</b></div>`).join('')||'<div class="empty">Nessun test registrato.</div>'}</div>`)}
function quiz(){const q=anatomy[Math.floor(Math.random()*anatomy.length)],alts=[q.a,...q.wrong].sort(()=>Math.random()-.5),box=modal(`A cosa serve: ${q.q}?`,`<div class="list">${alts.map((a,i)=>`<button class="btn secondary full" data-answer="${i}">${esc(a)}</button>`).join('')}</div>`);box.querySelectorAll('[data-answer]').forEach((b,i)=>b.onclick=()=>{const ok=alts[i]===q.a;toast(ok?'Risposta corretta ✓':'Riprova',ok?'ok':'err');if(ok)setTimeout(()=>{box.remove();quiz()},450)})}
})();