(() => {
'use strict';
const A=window.PTAPP;if(!A)return;const {state,esc,shell,modal,toast}=A;
const structures=[
['Deltoide','spalla','Abduzione e controllo del braccio','Spalla'],['Gran pettorale','torace','Spinta e adduzione del braccio','Spalla'],['Gran dorsale','dorso','Trazione e adduzione del braccio','Spalla'],['Trapezio','dorso superiore','Controllo e movimento della scapola','Scapola'],['Bicipite brachiale','braccio anteriore','Flessione del gomito','Gomito'],['Tricipite brachiale','braccio posteriore','Estensione del gomito','Gomito'],['Retto addominale','addome','Flessione e controllo del tronco','Colonna'],['Obliqui','addome laterale','Rotazione e stabilità del tronco','Colonna'],['Erettori spinali','schiena','Estensione e stabilità della colonna','Colonna'],['Grande gluteo','anca posteriore','Estensione dell’anca','Anca'],['Gluteo medio','anca laterale','Abduzione e stabilità del bacino','Anca'],['Ileopsoas','anca anteriore','Flessione dell’anca','Anca'],['Adduttori','coscia interna','Adduzione e controllo dell’anca','Anca'],['Quadricipite','coscia anteriore','Estensione del ginocchio','Ginocchio'],['Ischiocrurali','coscia posteriore','Flessione del ginocchio ed estensione dell’anca','Ginocchio'],['Gastrocnemio','polpaccio','Flessione plantare e spinta','Caviglia'],['Soleo','polpaccio profondo','Flessione plantare e postura','Caviglia'],['Tibiale anteriore','gamba anteriore','Dorsiflessione del piede','Caviglia'],['Cuffia dei rotatori','spalla profonda','Stabilità della testa omerale','Spalla'],['Diaframma','torace','Principale muscolo inspiratorio','Respirazione'] ];
const anatomy=[];structures.forEach((s,i)=>{const wrong=structures.filter((_,j)=>j!==i).slice((i+3)%structures.length,(i+3)%structures.length+3).map(x=>x[2]);anatomy.push({level:'I grado',topic:'Muscoli',q:`Qual è la funzione principale di ${s[0]}?`,a:s[2],wrong});anatomy.push({level:'I grado',topic:'Localizzazione',q:`Dove si trova principalmente ${s[0]}?`,a:s[1],wrong:['avambraccio','collo','pianta del piede'].filter(x=>x!==s[1])});anatomy.push({level:'II grado',topic:'Biomeccanica',q:`Quale articolazione è maggiormente collegata a ${s[0]}?`,a:s[3],wrong:['Polso','Mandibola','Dita'].filter(x=>x!==s[3])})});
const test=(name,capacity,unit,equipment,setup,protocol,errors,safety,score,image)=>({name,capacity,unit,equipment,setup,protocol,errors,safety,score,image});
const tests=[
test('Sprint 30 m','Velocità','s','Cronometro, coni','Tracciato piano di 40 m con zona di decelerazione','Riscaldamento completo; partenza alta; 2 prove con 4 minuti di recupero; registra la migliore.','Partenza anticipata, cronometro non allineato, rallentare prima della linea.','Scarpe adatte, superficie asciutta, uscita libera.','Tempo minore = prestazione migliore.',6),
test('Salto in lungo da fermo','Potenza arti inferiori','cm','Metro, nastro a terra','Linea di stacco e area di atterraggio non scivolosa','Piedi dietro la linea; contromovimento libero; salta e atterra a due piedi; 3 prove.','Superare la linea, cadere indietro, misurare dal piede avanzato.','Spazio libero e atterraggio stabile.','Misura dalla linea al tallone più arretrato.',7),
test('Shuttle 10×5 m','Agilità','s','Coni, cronometro','Due linee parallele a 5 m','Completa 10 navette toccando o superando ogni linea; 2 prove con recupero.','Curve larghe, non raggiungere la linea, superficie diversa tra prove.','Frenata progressiva, distanza di sicurezza.',8),
test('Cooper 12 minuti','Resistenza aerobica','m','Pista misurata, cronometro','Circuito noto con giri conteggiabili','Dopo riscaldamento percorri la massima distanza sostenibile in 12 minuti.','Partenza troppo veloce, conteggio giri errato, ostacolare altri.','Escludere condizioni acute; idratazione e meteo adeguati.','Distanza totale percorsa; confronto nel tempo.',9),
test('Sit and reach','Mobilità catena posteriore','cm','Box o righello','Seduto, ginocchia estese, piedi contro il box','Sovrapponi le mani e avanza lentamente; mantieni 2 secondi; 3 prove.','Molleggiare, piegare le ginocchia, trattenere il respiro.','Nessun dolore lombare o posteriore acuto.','Migliore distanza raggiunta.',10),
test('Lancio palla medica','Potenza arti superiori','m','Palla medica 1–3 kg, metro','Seduto con schiena al muro o in piedi secondo protocollo','Lancio frontale dal petto; 3 prove; stessa palla e posizione.','Staccare la schiena, cambiare peso, oltrepassare la linea.','Zona di lancio libera e recupero palla laterale.','Migliore distanza valida.',11),
test('Equilibrio monopodalico','Equilibrio statico','s','Cronometro','Area piana vicino a un appoggio','Mani ai fianchi, un piede sollevato; massimo 60 s; entrambi i lati.','Saltellare, appoggiare il piede, spostare le mani.','Assistenza vicina per chi è instabile.','Tempo fino al primo errore.',12),
test('Plank tecnico','Resistenza del core','s','Tappetino, cronometro','Gomiti sotto spalle, corpo allineato','Mantieni finché perdi due volte la posizione dopo richiamo.','Bacino basso o alto, apnea, spalle chiuse.','Stop a dolore lombare o alla spalla.','Tempo con tecnica valida.',5),
test('Push-up 30 secondi','Forza resistente','ripetizioni','Tappetino','Mani sotto o poco oltre le spalle','Conta ripetizioni complete in 30 s; variante ginocchia dichiarata.','Range ridotto, bacino che cede, rimbalzo.','Variante adeguata al livello.','Solo ripetizioni tecnicamente valide.',1),
test('Illinois agility','Agilità e cambio direzione','s','8 coni, cronometro','Rettangolo 10×5 m con slalom centrale','Segui il percorso standard; 2 prove con recupero completo.','Percorso errato, coni spostati, tagliare le curve.','Scarpe e fondo adeguati.',8),
test('Yo-Yo IR1 adattato','Resistenza intermittente','m','Audio, coni','Linee a 20 m più zona recupero','Navette al segnale con 10 s di recupero attivo; termina dopo due errori.','Partire prima, non raggiungere linea, audio non udibile.','Progressivo; osservazione docente continua.','Livello e distanza completati.',9),
test('Test dei 6 minuti','Capacità aerobica','m','Circuito, cronometro','Percorso piano misurato','Cammina o corri 6 minuti autoregolando il ritmo.','Conteggio impreciso, partenza eccessiva, percorso affollato.','Adatto anche a livelli iniziali con supervisione.','Distanza totale.',9),
test('T-test','Agilità multidirezionale','s','4 coni, cronometro','Coni a T: 10 m avanti e 5 m laterali','Sprint avanti, scivolamenti laterali e ritorno senza incrociare i piedi.','Incrociare, girare il busto, toccare con mano errata.','Tecnica laterale prima della velocità.',8),
test('Salto verticale','Potenza verticale','cm','Parete graduata o jump mat','Piano stabile accanto alla misura','Misura reach in piedi, poi salto con contromovimento; 3 prove.','Misura reach errata, passo prima del salto, atterraggio instabile.','Area libera e atterraggio morbido.','Differenza tra reach e quota toccata.',7),
test('Handgrip','Forza di presa','kg','Dinamometro','Braccio lungo il fianco senza appoggio','Regola impugnatura; stringi 3–5 s; 2 prove per mano.','Piegare polso, trattenere respiro, misura non regolata.','Evitare in dolore acuto a mano/polso.','Miglior valore per lato.',2),
test('Mobilità spalla','Mobilità scapolo-omerale','cm','Metro','In piedi con una mano sopra e una sotto la schiena','Avvicina le dita senza forzare; misura distanza o sovrapposizione; entrambi i lati.','Inarcare molto, forzare, spostare le mani dopo misura.','Range senza dolore.',14),
test('Mobilità caviglia knee-to-wall','Dorsiflessione caviglia','cm','Metro, parete','Piede perpendicolare alla parete','Avanza il ginocchio alla parete senza sollevare il tallone; trova distanza massima.','Tallone sollevato, arco che collassa, piede ruotato.','Movimento lento e controllato.','Distanza alluce-parete per lato.',15),
test('Repeated sprint 6×20 m','Capacità anaerobica','s','Cronometro/fotocellule, coni','Rettifilo 30 m','6 sprint di 20 m con 20 s di recupero; registra ogni tempo.','Recupero variabile, decelerazione precoce, partenza diversa.','Solo dopo preparazione adeguata.','Tempo totale e calo percentuale.',6),
test('Test della cicogna','Equilibrio','s','Cronometro','Piede libero contro il ginocchio, mani ai fianchi','Solleva il tallone e mantieni; 3 tentativi.','Piede che scende, mani che si muovono, saltelli.','Appoggio vicino.',12),
test('Back saver sit and reach','Mobilità posteriore','cm','Box','Una gamba distesa e una flessa','Avanza con mani sovrapposte; 2 prove per lato.','Ruotare bacino, molleggiare, ginocchio esteso che si piega.','Alternativa scolastica controllata.',10)
];
const sports=['Atletica','Calcio','Basket','Pallavolo','Tennis','Badminton','Nuoto','Fitness','Ultimate','Rugby educativo','Orienteering','Danza','Mobilità','Ginnastica','Circuit training'];
const lessons=[];['I grado','II grado'].forEach(level=>sports.forEach((sport,i)=>lessons.push({level,sport,title:`${sport}: tecnica e competenze`,objective:level==='I grado'?'Sviluppare schemi motori, collaborazione e regole':'Consolidare tecnica, autonomia, tattica e autoregolazione',duration:level==='I grado'?55:60,equipment:['coni','cinesini','palloni o attrezzi dello sport','pettorine','cronometro'],blocks:[{name:'Accoglienza e sicurezza',minutes:5,work:'Obiettivi, spazi, regole e controllo del materiale.'},{name:'Attivazione',minutes:10,work:'Gioco dinamico, mobilità e andature collegate allo sport.'},{name:'Tecnica guidata',minutes:15,work:`Tre esercizi progressivi sui fondamentali di ${sport}, da semplice a situazione.`},{name:'Circuito applicativo',minutes:15,work:'4 stazioni: tecnica, coordinazione, decisione e condizionamento.'},{name:'Gioco o prova autentica',minutes:10,work:'Piccoli gruppi, ruoli chiari e punteggio orientato alla collaborazione.'},{name:'Defaticamento e verifica',minutes:5,work:'Respirazione, mobilità, autovalutazione e domanda finale.'}],assessment:['Esegue il gesto con controllo','Rispetta regole e sicurezza','Collabora e assume ruoli','Riconosce intensità e recupero'],inclusion:'Riduci spazio, velocità e complessità; usa attrezzi più leggeri, segnali visivi, tutoraggio tra pari e obiettivi a livelli.',homework:`Breve scheda: descrivi due fondamentali di ${sport} e una regola di sicurezza.`})));
const pic=i=>`<div class="catalogPicture" role="img" aria-label="Illustrazione del test" style="--catalog-image:url('/assets/exercise-guides/athletic-tests-photo-atlas.webp');--catalog-x:${i%4};--catalog-y:${Math.floor(i%16/4)}"></div>`;
function showTest(i){const x=tests[i],m=modal(x.name,`${pic(x.image)}<div class="guideMeta"><span>${esc(x.capacity)}</span><span>${esc(x.unit)}</span><span>${esc(x.equipment)}</span></div><div class="catalogDetailList"><div><b>Preparazione</b><br>${esc(x.setup)}</div><div><b>Protocollo passo-passo</b><br>${esc(x.protocol)}</div><div><b>Errori comuni</b><br>${esc(x.errors)}</div><div><b>Sicurezza</b><br>${esc(x.safety)}</div><div><b>Valutazione</b><br>${esc(x.score)}</div></div><div class="formGrid"><label>Studente<input id="spName"></label><label>Classe<input id="spClass"></label><label>Risultato<input id="spValue" type="number" step="0.01"></label><label>Data<input id="spDate" type="date" value="${new Date().toISOString().slice(0,10)}"></label></div><button class="btn primary full" id="spSave">Salva risultato</button>`);m.querySelector('#spSave').onclick=()=>{const rec={test:x.name,capacity:x.capacity,unit:x.unit,name:m.querySelector('#spName').value.trim(),class:m.querySelector('#spClass').value.trim(),value:+m.querySelector('#spValue').value,date:m.querySelector('#spDate').value};if(!rec.name||!Number.isFinite(rec.value))return toast('Inserisci studente e risultato','err');let a=[];try{a=JSON.parse(localStorage.getItem('ptpro11_school_test_results')||'[]')}catch{}a.unshift(rec);localStorage.setItem('ptpro11_school_test_results',JSON.stringify(a.slice(0,2000)));m.remove();toast('Risultato salvato ✓')}}
function showLesson(x){modal(x.title,`<div class="guideMeta"><span>${esc(x.level)}</span><span>${esc(x.sport)}</span><span>${x.duration} minuti</span></div><p><b>Obiettivo:</b> ${esc(x.objective)}</p><p><b>Materiali:</b> ${esc(x.equipment.join(', '))}</p><div class="list">${x.blocks.map((b,i)=>`<div class="row"><span><b>${i+1}. ${esc(b.name)} · ${b.minutes}′</b><small>${esc(b.work)}</small></span></div>`).join('')}</div><div class="guideColumns"><section><h3>Valutazione</h3><ul>${x.assessment.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></section><section><h3>Inclusione</h3><p>${esc(x.inclusion)}</p></section></div><div class="card"><b>Compito / consolidamento</b><p>${esc(x.homework)}</p></div>`)}
function builder(){const m=modal('Genera lezione completa',`<div class="formGrid"><label>Grado<select id="slLevel"><option>I grado</option><option>II grado</option></select></label><label>Sport<select id="slSport">${sports.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>Durata<select id="slMin"><option>45</option><option selected>60</option><option>90</option></select></label><label>Classe<select id="slClass"><option>Standard</option><option>Numerosa</option><option>Inclusiva / BES</option></select></label></div><button class="btn primary full" id="slMake">Crea lezione</button>`);m.querySelector('#slMake').onclick=()=>{const level=m.querySelector('#slLevel').value,sport=m.querySelector('#slSport').value,mins=+m.querySelector('#slMin').value,kind=m.querySelector('#slClass').value,base=lessons.find(x=>x.level===level&&x.sport===sport);m.remove();const scale=mins/base.duration,x={...base,duration:mins,blocks:base.blocks.map(b=>({...b,minutes:Math.max(3,Math.round(b.minutes*scale))})),inclusion:`${base.inclusion} Per classe “${kind}”: ${kind==='Numerosa'?'usa 5–6 stazioni e gruppi fissi per ridurre le attese.':kind.includes('BES')?'prevedi consegne brevi, dimostrazione visiva, scelta tra varianti e compagno tutor.':'mantieni progressioni a tre livelli.'}`};showLesson(x)}}
function anatomyQuiz(level='Tutti'){let score=0,total=0;const next=()=>{const pool=level==='Tutti'?anatomy:anatomy.filter(x=>x.level===level),q=pool[Math.floor(Math.random()*pool.length)],answers=[q.a,...q.wrong].sort(()=>Math.random()-.5),m=modal(`Anatomia · ${q.topic}`,`<div class="kpis four"><div class="kpi"><b>${score}/${total}</b><span>Punteggio</span></div><div class="kpi"><b>${esc(q.level)}</b><span>Livello</span></div></div><h3>${esc(q.q)}</h3><div class="list">${answers.map((a,i)=>`<button class="btn secondary full" data-sa="${i}">${esc(a)}</button>`).join('')}</div>`);m.querySelectorAll('[data-sa]').forEach((b,i)=>b.onclick=()=>{total++;const ok=answers[i]===q.a;if(ok)score++;toast(ok?'Risposta corretta ✓':`Risposta corretta: ${q.a}`,ok?'ok':'err');setTimeout(()=>{m.remove();next()},550)})};next()}
A.register('school',()=>{state.view='school';shell(`<div class="sectionHead"><div><div class="eyebrow">PT-PRO SCUOLA PRO</div><h1>Didattica, anatomia e test motori</h1><span class="muted">Secondaria di I e II grado: lezioni complete, protocolli illustrati e verifiche interattive.</span></div><button class="btn primary" id="schoolBuild">Genera lezione completa</button></div><div class="kpis four"><div class="kpi"><b>${lessons.length}</b><span>Lezioni complete</span></div><div class="kpi"><b>${tests.length}</b><span>Test illustrati</span></div><div class="kpi"><b>${anatomy.length}</b><span>Domande anatomia</span></div><div class="kpi"><b>2</b><span>Gradi scolastici</span></div></div><section class="section"><div class="sectionHead"><h2>Test anatomici</h2><div class="manageButtons"><button class="btn secondary" data-aq="I grado">Quiz I grado</button><button class="btn secondary" data-aq="II grado">Quiz II grado</button></div></div><div class="card"><p>Muscoli, localizzazione, funzione e biomeccanica con domande differenziate per grado scolastico. Il quiz fornisce correzione immediata e punteggio progressivo.</p></div></section><section class="section"><div class="sectionHead"><h2>Test atletici illustrati</h2><span class="muted">Protocollo, errori, sicurezza e registrazione</span></div><div class="guideGrid">${tests.map((x,i)=>`<button class="guideCard" data-st="${i}">${pic(x.image)}<span class="guideCardBody"><b>${esc(x.name)}</b><small>${esc(x.capacity)} · ${esc(x.unit)}</small><em>${esc(x.equipment)}</em></span></button>`).join('')}</div></section><section class="section"><div class="sectionHead"><h2>Lezioni e unità didattiche</h2><span class="muted">${lessons.length} percorsi pronti</span></div><div class="toolGrid">${lessons.map((x,i)=>`<button class="dayCard" data-sl="${i}"><div><b>${esc(x.sport)} · ${esc(x.title)}</b><span>${esc(x.level)} · ${x.duration}′ · completa di esercizi e valutazione</span></div></button>`).join('')}</div></section>`);document.getElementById('schoolBuild').onclick=builder;document.querySelectorAll('[data-aq]').forEach(b=>b.onclick=()=>anatomyQuiz(b.dataset.aq));document.querySelectorAll('[data-st]').forEach(b=>b.onclick=()=>showTest(+b.dataset.st));document.querySelectorAll('[data-sl]').forEach(b=>b.onclick=()=>showLesson(lessons[+b.dataset.sl]))});
window.PTPROSchoolLibrary={structures,anatomy,tests,lessons};
})();
