(() => {
'use strict';
const A=window.PTAPP;if(!A)return;const {state,esc,shell,toast,modal}=A;
const lessons=[
{school:'I grado',sport:'Atletica',title:'Velocità e staffette',goal:'Coordinazione, rapidità, collaborazione',steps:['Riscaldamento 10′','Andature 10′','Staffette 20′','Gioco finale 10′','Defaticamento 5′']},
{school:'I grado',sport:'Pallavolo',title:'Bagher e palleggio',goal:'Fondamentali e cooperazione',steps:['Mobilità 8′','Palleggio a coppie 12′','Bagher a bersaglio 15′','Mini-volley 20′']},
{school:'I grado',sport:'Basket',title:'Palleggio e passaggio',goal:'Controllo palla e orientamento',steps:['Gioco attivazione 8′','Circuito palleggio 12′','Passaggi 10′','3 contro 3 20′']},
{school:'II grado',sport:'Calcio',title:'Tecnica + small sided games',goal:'Tecnica, decision making, intensità',steps:['Rondo 10′','Tecnica analitica 10′','1v1/2v2 15′','4v4 20′']},
{school:'II grado',sport:'Atletica',title:'Resistenza e pacing',goal:'Gestione dello sforzo e autonomia',steps:['Warm-up 10′','Tecnica 8′','Intervalli 6×2′/1′','Defaticamento 8′']},
{school:'II grado',sport:'Fitness',title:'Circuit training scolastico',goal:'Forza generale e autoregolazione',steps:['Mobilità 8′','Circuito 8 stazioni × 35″/25″','Recupero 3′','Secondo giro','Stretching 6′']}
];
const tests=[['30 m sprint','Velocità','Tempo (s)'],['Salto in lungo da fermo','Potenza arti inferiori','Distanza (cm)'],['Shuttle 10×5 m','Agilità','Tempo (s)'],['Cooper 12 minuti','Resistenza','Distanza (m)'],['Sit and reach','Mobilità','Distanza (cm)'],['Plank','Core endurance','Tempo (s)']];
const games=[['Palla prigioniera evoluta','Reazione, lancio, collaborazione'],['Rubabandiera motorio','Velocità e decisione'],['Circuito semaforo','Coordinazione e attenzione'],['Caccia ai coni','Rapidità e orientamento'],['Ultimate semplificato','Spazi, smarcamento e fair play'],['Memory motorio','Anatomia + movimento']];
const anatomy=[['Quadricipite','Estende il ginocchio'],['Bicipite femorale','Flette il ginocchio e contribuisce all’estensione dell’anca'],['Glutei','Estensione e stabilità dell’anca'],['Polpacci','Spinta della caviglia'],['Deltoide','Movimenti della spalla'],['Core','Stabilizza tronco e bacino']];
function cardList(arr,fn){return `<div class="toolGrid">${arr.map(fn).join('')}</div>`}
A.register('school',()=>{state.view='school';shell(`<div class="sectionHead"><div><div class="eyebrow">PT-PRO SCUOLA</div><h1>Area Docenti</h1><span class="muted">Secondaria di I e II grado · lezioni, test, valutazioni, giochi e anatomia.</span></div></div><div class="kpis four"><div class="kpi"><b>${lessons.length}</b><span>Lezioni pronte</span></div><div class="kpi"><b>${tests.length}</b><span>Test motori</span></div><div class="kpi"><b>${games.length}</b><span>Giochi ludici</span></div><div class="kpi"><b>${anatomy.length}</b><span>Quiz anatomia</span></div></div><section class="section"><div class="sectionHead"><h2>Lezioni e unità didattiche</h2></div>${cardList(lessons,x=>`<button class="dayCard" data-lesson="${esc(x.title)}"><div><b>${esc(x.sport)} · ${esc(x.title)}</b><span>${esc(x.school)} · ${esc(x.goal)}</span></div></button>`)}</section><section class="section"><div class="sectionHead"><h2>Test atletici e motori</h2><button class="btn secondary" id="openEval">Scheda valutazione</button></div>${cardList(tests,(x,i)=>`<button class="dayCard" data-test="${i}"><div><b>${esc(x[0])}</b><span>${esc(x[1])} · ${esc(x[2])}</span></div></button>`)}</section><section class="section"><div class="sectionHead"><h2>Giochi ludico-motori</h2></div>${cardList(games,x=>`<div class="dayCard"><div><b>${esc(x[0])}</b><span>${esc(x[1])}</span></div></div>`)}</section><section class="section"><div class="sectionHead"><h2>Anatomia semplice · gioco interattivo</h2><button class="btn primary" id="quizAnatomy">Avvia quiz</button></div><div class="card"><p class="muted">Quiz casuali su muscoli e funzioni, pensati per ripasso rapido in classe.</p></div></section>`);document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>{const x=lessons.find(v=>v.title===b.dataset.lesson);if(!x)return;modal(x.title,`<p><b>${esc(x.school)} · ${esc(x.sport)}</b></p><p class="muted">${esc(x.goal)}</p><div class="list">${x.steps.map((s,i)=>`<div class="row"><span><b>${i+1}. ${esc(s)}</b></span></div>`).join('')}</div>`) });document.getElementById('openEval').onclick=assessment;document.getElementById('quizAnatomy').onclick=quiz;document.querySelectorAll('[data-test]').forEach(b=>b.onclick=()=>testInfo(+b.dataset.test))});
function testInfo(i){const x=tests[i];modal(x[0],`<div class="card"><p><b>Capacità:</b> ${esc(x[1])}</p><p><b>Dato da registrare:</b> ${esc(x[2])}</p><p class="muted">Esegui protocollo identico tra rilevazioni e annota condizioni rilevanti per rendere il confronto coerente.</p></div>`)}
function assessment(){const box=modal('Scheda di valutazione',`<div class="formGrid"><label class="field">Studente<input id="scName"></label><label class="field">Classe<input id="scClass"></label><label class="field">Tecnica 1–10<input id="scTech" type="number" min="1" max="10"></label><label class="field">Impegno 1–10<input id="scEff" type="number" min="1" max="10"></label><label class="field">Collaborazione 1–10<input id="scTeam" type="number" min="1" max="10"></label><label class="field">Autonomia 1–10<input id="scAuto" type="number" min="1" max="10"></label></div><label class="field">Note<textarea id="scNotes"></textarea></label><button class="btn primary full" id="scSave">Salva localmente</button>`);box.querySelector('#scSave').onclick=()=>{const rec={name:box.querySelector('#scName').value,class:box.querySelector('#scClass').value,tech:+box.querySelector('#scTech').value||null,effort:+box.querySelector('#scEff').value||null,team:+box.querySelector('#scTeam').value||null,autonomy:+box.querySelector('#scAuto').value||null,notes:box.querySelector('#scNotes').value,at:new Date().toISOString()};const key='ptpro11_school_assessments',arr=JSON.parse(localStorage.getItem(key)||'[]');arr.unshift(rec);localStorage.setItem(key,JSON.stringify(arr.slice(0,500)));box.remove();toast('Valutazione salvata ✓')}}
function quiz(){const q=anatomy[Math.floor(Math.random()*anatomy.length)],alts=anatomy.map(x=>x[1]).sort(()=>Math.random()-.5).slice(0,3);if(!alts.includes(q[1]))alts[0]=q[1];alts.sort(()=>Math.random()-.5);const box=modal(`A cosa serve: ${q[0]}?`,`<div class="list">${alts.map((a,i)=>`<button class="btn secondary full" data-answer="${i}">${esc(a)}</button>`).join('')}</div>`);box.querySelectorAll('[data-answer]').forEach((b,i)=>b.onclick=()=>{toast(alts[i]===q[1]?'Risposta corretta ✓':'Riprova',''+(alts[i]===q[1]?'ok':'err'));if(alts[i]===q[1])setTimeout(()=>{box.remove();quiz()},500)})}
})();