(() => {
'use strict';
const block=(title,kind,prescription,instructions)=>({title,kind,prescription,instructions});
const common={warmup:()=>block('Riscaldamento dinamico','warmup',{minutes:8},'Mobilità, attivazione e aumento progressivo della temperatura.'),cooldown:()=>block('Defaticamento e mobilità','cooldown',{minutes:6},'Respirazione, mobilità dolce e ritorno graduale alla calma.')};
const strength=()=>[common.warmup(),block('Squat / accosciata','strength',{sets:3,reps:'8-12',rir:2},'Tecnica controllata e range di movimento adatto.'),block('Spinta orizzontale','strength',{sets:3,reps:'8-12',rir:2},'Piegamenti, chest press o variante disponibile.'),block('Tirata orizzontale','strength',{sets:3,reps:'8-12',rir:2},'Rematore con elastico, manubrio o macchina.'),block('Hip hinge','strength',{sets:3,reps:'8-10',rir:2},'Stacco rumeno, kettlebell deadlift o variante educativa.'),block('Core anti-estensione','core',{sets:3,seconds:30},'Plank o variante mantenendo bacino neutro.'),common.cooldown()];
const running=()=>[common.warmup(),block('Tecnica di corsa','technique',{drills:['skip A','calciata','corsa balzata'],distance_m:20,rounds:2},'Qualità prima della velocità.'),block('Corsa facile','endurance',{minutes:25,rpe:4},'Ritmo conversazionale.'),block('Progressioni','speed',{reps:6,distance_m:80,recovery_s:60},'Accelera gradualmente senza sprint massimale.'),block('Core runner','core',{rounds:3},'Dead bug, side plank e ponte glutei.'),common.cooldown()];
const hiking=()=>[common.warmup(),block('Cammino progressivo','endurance',{minutes:35,rpe:4},'Passo regolare e respirazione controllata.'),block('Salite tecniche','conditioning',{sets:5,minutes:3,recovery_min:2,rpe:6},'Accorcia il passo e mantieni postura stabile.'),block('Step-up','strength',{sets:3,reps:10},'Spinta completa e controllo in discesa.'),block('Equilibrio monopodalico','balance',{sets:3,seconds:30},'Appoggio stabile e sguardo avanti.'),common.cooldown()];
const stairs=()=>[common.warmup(),block('Salita continua facile','endurance',{minutes:12,rpe:4},'Ritmo uniforme.'),block('Ripetute sulle scale','conditioning',{sets:6,seconds:45,recovery_s:75,rpe:7},'Salita controllata, discesa facile.'),block('Step-up alternato','strength',{sets:3,reps:12},'Controlla ginocchio e appoggio.'),common.cooldown()];
const football=()=>[common.warmup(),block('Guida palla e cambi direzione','technique',{minutes:10},'Usa entrambi i piedi e varia ritmo.'),block('Passaggio e primo controllo','technique',{sets:4,reps:8},'Precisione, orientamento del corpo e ricezione aperta.'),block('1 contro 1 / finte','skill',{rounds:6,seconds:30},'Alterna attacco e recupero.'),block('RSA calcistico','conditioning',{sets:2,reps:5,distance_m:20,recovery_s:25},'Sprint submassimali, recupero completo tra i set.'),block('Prevenzione arti inferiori','strength',{sets:3},'Affondo, ponte glutei, polpacci e controllo monopodalico.'),common.cooldown()];
const basketball=()=>[common.warmup(),block('Ball handling','technique',{minutes:8},'Palleggio destro/sinistro, cambi mano e protezione palla.'),block('Passaggi in movimento','technique',{sets:4,reps:10},'Petto, schiacciato e baseball pass.'),block('Arresti, partenze e lay-up','skill',{rounds:5},'Alterna lato destro e sinistro.'),block('Agilità 5-10-5','conditioning',{reps:5,recovery_s:60},'Frena con controllo e riparti esplosivo.'),block('Forza elastica arti inferiori','strength',{sets:3,reps:'6-8'},'Squat jump controllato e atterraggi morbidi.'),common.cooldown()];
const volleyball=()=>[common.warmup(),block('Bagher e palleggio','technique',{sets:5,reps:12},'Piattaforma stabile e precisione.'),block('Servizio','skill',{sets:5,reps:6},'Routine costante e bersagli progressivi.'),block('Passi di rincorsa e stacco','technique',{sets:4,reps:5},'Coordina braccia e piedi senza ricerca massimale.'),block('Atterraggi e prevenzione','strength',{sets:3,reps:8},'Ginocchia allineate e assorbimento controllato.'),common.cooldown()];
const racket=()=>[common.warmup(),block('Split step e appoggi','footwork',{rounds:6,seconds:30},'Posizione pronta e passi rapidi.'),block('Diritto / rovescio','technique',{sets:5,reps:10},'Impatto davanti al corpo e recupero posizione.'),block('Servizio / battuta','skill',{sets:5,reps:6},'Precisione prima della potenza.'),block('Navetta multidirezionale','conditioning',{sets:4,seconds:40,recovery_s:60},'Cambi direzione controllati.'),common.cooldown()];
const tableTennis=()=>[common.warmup(),block('Palleggio diritto-rovescio','technique',{sets:6,reps:20},'Controlla angolo della racchetta.'),block('Servizio corto/lungo','skill',{sets:5,reps:8},'Varia rotazione e profondità.'),block('Footwork laterale','footwork',{sets:6,seconds:30,recovery_s:30},'Passi piccoli e baricentro basso.'),common.cooldown()];
const swimming=()=>[block('Attivazione a secco','warmup',{minutes:6},'Mobilità spalle, torace e caviglie.'),block('Tecnica nuotata','technique',{meters:400},'Drill di presa, allineamento e respirazione.'),block('Serie aerobica','endurance',{sets:6,meters:100,recovery_s:30},'Ritmo sostenibile e regolare.'),block('Serie velocità','speed',{sets:8,meters:25,recovery_s:35},'Alta qualità senza deteriorare la tecnica.'),block('Defaticamento','cooldown',{meters:200},'Nuotata facile e rilassata.')];
const aqua=()=>[block('Mobilità in acqua','warmup',{minutes:8},'Cammino in acqua e mobilità articolare.'),block('Corsa in acqua','conditioning',{sets:5,minutes:2,recovery_min:1},'Mantieni postura alta e ritmo regolare.'),block('Spinte e tirate in acqua','strength',{sets:4,reps:15},'Movimenti ampi e controllati.'),block('Equilibrio e core','balance',{sets:4,seconds:40},'Controllo del tronco.'),common.cooldown()];
const cycling=()=>[common.warmup(),block('Cadenza tecnica','technique',{sets:4,minutes:3,rpm:'90-100'},'Pedalata fluida e stabile.'),block('Fondo aerobico','endurance',{minutes:35,rpe:4},'Intensità facile-moderata.'),block('Ripetute tempo','conditioning',{sets:4,minutes:4,recovery_min:2,rpe:7},'Mantieni cadenza e controllo.'),common.cooldown()];
const rowing=()=>[common.warmup(),block('Tecnica di voga','technique',{minutes:10,stroke_rate:'18-22'},'Sequenza gambe-tronco-braccia e ritorno controllato.'),block('Fondo al remoergometro','endurance',{minutes:25,rpe:5},'Ritmo uniforme.'),block('Intervalli 500 m','conditioning',{sets:5,meters:500,recovery_min:2,rpe:7},'Mantieni split stabile.'),block('Core e catena posteriore','strength',{sets:3,reps:10},'Hip hinge, rematore e plank.'),common.cooldown()];
const elliptical=()=>[common.warmup(),block('Cardio continuo','endurance',{minutes:30,rpe:5},'Passo fluido senza rimbalzi.'),block('Intervalli inclinazione/resistenza','conditioning',{sets:6,minutes:2,recovery_min:1,rpe:7},'Alterna blocchi intensi e recupero.'),common.cooldown()];
const jumpRope=()=>[common.warmup(),block('Salto base','technique',{sets:5,seconds:60,recovery_s:30},'Salti bassi e polsi rilassati.'),block('Alternato / boxer step','skill',{sets:5,seconds:45,recovery_s:30},'Ritmo regolare.'),block('Intervalli veloci','conditioning',{sets:8,seconds:30,recovery_s:30,rpe:7},'Mantieni tecnica pulita.'),block('Polpacci e tibiale','strength',{sets:3,reps:15},'Controlla salita e discesa.'),common.cooldown()];
const hiit=()=>[common.warmup(),block('Circuito forza-cardio','conditioning',{rounds:4,work_s:40,recovery_s:20},'Squat, push-up facilitato, mountain climber e hip hinge.'),block('Intervalli brevi','conditioning',{sets:8,seconds:30,recovery_s:30,rpe:8},'Intensità alta ma controllata.'),block('Core finale','core',{rounds:3,seconds:30},'Plank e side plank.'),common.cooldown()];
const lowImpact=()=>[common.warmup(),block('Sit-to-stand','strength',{sets:3,reps:10},'Alzati e siediti con controllo.'),block('Marcia sul posto','endurance',{sets:5,minutes:2,recovery_min:1},'Ritmo moderato.'),block('Step touch laterale','coordination',{sets:4,seconds:45},'Movimento fluido senza impatto.'),block('Equilibrio assistito','balance',{sets:3,seconds:30},'Usa un supporto se necessario.'),common.cooldown()];
const mobility=()=>[block('Respirazione e centratura','mind-body',{minutes:4},'Respirazione lenta e regolare.'),block('Mobilità colonna e anche','mobility',{rounds:2,reps:8},'Movimenti lenti e senza dolore.'),block('Mobilità spalle','mobility',{rounds:2,reps:8},'Controlla scapole e respirazione.'),block('Sequenza principale','mobility',{minutes:20},'Mantieni qualità del movimento e ampiezza confortevole.'),common.cooldown()];
const dance=()=>[common.warmup(),block('Passi base e ritmo','technique',{minutes:10},'Lavora su tempo musicale e coordinazione.'),block('Sequenza coreografica','skill',{rounds:5,minutes:3},'Memorizza e combina blocchi progressivi.'),block('Cardio dance','endurance',{minutes:20,rpe:6},'Mantieni continuità e controllo.'),common.cooldown()];
const combat=()=>[common.warmup(),block('Guardia e spostamenti','technique',{rounds:4,minutes:2},'Assetto, distanza e ritorno in guardia.'),block('Combinazioni tecniche','skill',{rounds:5,minutes:2},'Esecuzione pulita, non massimale.'),block('Condizionamento a round','conditioning',{rounds:5,minutes:2,recovery_s:60},'Alterna lavoro tecnico e cardio.'),block('Core rotazionale','strength',{sets:3,reps:10},'Controllo del tronco e bacino stabile.'),common.cooldown()];
const skiing=()=>[common.warmup(),block('Squat isometrico','strength',{sets:4,seconds:40},'Mantieni allineamento ginocchio-piede.'),block('Affondi laterali','strength',{sets:3,reps:10},'Controlla spostamento laterale.'),block('Equilibrio monopodalico','balance',{sets:4,seconds:30},'Stabilità di caviglia e anca.'),block('Intervalli cardio','conditioning',{sets:6,minutes:2,recovery_min:1,rpe:7},'Simula richieste intermittenti.'),common.cooldown()];
const crossCountrySki=()=>[common.warmup(),block('Tecnica braccia-gambe','technique',{minutes:10},'Coordina spinta e trasferimento del peso.'),block('Fondo aerobico','endurance',{minutes:35,rpe:5},'Ritmo regolare.'),block('Salite a intervalli','conditioning',{sets:5,minutes:3,recovery_min:2,rpe:7},'Mantieni gesto efficiente.'),common.cooldown()];
const skating=()=>[common.warmup(),block('Scivolamento e postura','technique',{minutes:10},'Baricentro basso e sguardo avanti.'),block('Curve e frenate','skill',{sets:6,reps:5},'Progressione da bassa a media velocità.'),block('Spinte laterali','strength',{sets:3,reps:12},'Controlla anca e ginocchio.'),block('Giri continui','endurance',{minutes:20,rpe:5},'Ritmo regolare.'),common.cooldown()];
const climbing=()=>[common.warmup(),block('Mobilità spalle e anche','mobility',{minutes:8},'Preparazione specifica senza forzare.'),block('Tecnica piedi','technique',{minutes:12},'Appoggi precisi e spinta dalle gambe.'),block('Traversi facili','skill',{sets:6,minutes:2,recovery_min:2},'Qualità tecnica e presa rilassata.'),block('Tirata e core','strength',{sets:3,reps:'6-10'},'Rematore, scapular pull e hollow hold.'),common.cooldown()];
const golf=()=>[common.warmup(),block('Mobilità toracica e anche','mobility',{minutes:8},'Rotazioni controllate.'),block('Swing tecnico','technique',{sets:6,reps:8},'Sequenza e contatto prima della potenza.'),block('Approcci e putt','skill',{minutes:20},'Lavoro su precisione e routine.'),block('Cammino attivo','endurance',{minutes:25,rpe:4},'Passo regolare.'),common.cooldown()];
const senior=()=>[block('Mobilità dolce','warmup',{minutes:8},'Movimenti confortevoli e respirazione regolare.'),block('Sit-to-stand','strength',{sets:3,reps:8},'Usa appoggio se necessario.'),block('Cammino controllato','endurance',{minutes:15,rpe:3},'Ritmo comodo.'),block('Equilibrio assistito','balance',{sets:4,seconds:20},'Supporto vicino per sicurezza.'),block('Spinta e tirata con elastico','strength',{sets:2,reps:12},'Movimenti lenti e controllati.'),common.cooldown()];
const reconditioning=()=>[block('Mobilità generale','warmup',{minutes:8},'Riprendi confidenza con movimenti semplici.'),block('Cammino facile','endurance',{minutes:15,rpe:3},'Ritmo conversazionale.'),block('Circuito base','strength',{rounds:2,reps:8},'Sit-to-stand, push-up al muro, ponte glutei, bird dog.'),block('Respirazione e recupero','cooldown',{minutes:6},'Ritorno alla calma e percezione dello sforzo.')];
const activeBreaks=()=>[block('Mobilità cervicale e spalle','mobility',{minutes:2},'Movimenti piccoli e controllati.'),block('Alzati e cammina','activity',{minutes:5},'Interrompi la sedentarietà.'),block('Squat alla sedia','strength',{sets:2,reps:10},'Controlla la discesa.'),block('Respirazione','mind-body',{minutes:2},'Respiri lenti e profondi.')];
const dailySteps=()=>[block('Passeggiata facile','endurance',{minutes:20,steps:3000,rpe:3},'Ritmo conversazionale.'),block('Blocco passi attivo','endurance',{minutes:15,steps:2000,rpe:5},'Passo più sostenuto.'),block('Passeggiata serale','recovery',{minutes:10,steps:1000,rpe:2},'Ritmo rilassato.')];
const breathing=()=>[block('Respirazione diaframmatica','mind-body',{minutes:5},'Inspira dal naso e lascia espandere l’addome.'),block('Respirazione lenta 4-6','mind-body',{minutes:6},'4 secondi inspirazione, 6 espirazione.'),block('Body scan','mind-body',{minutes:8},'Porta attenzione alle tensioni e rilasciale gradualmente.')];
const generic=()=>[common.warmup(),block('Tecnica specifica','technique',{minutes:15},'Esegui i fondamentali della disciplina con qualità.'),block('Blocco principale','activity',{minutes:25,rpe:6},'Volume progressivo compatibile con il livello.'),block('Condizionamento generale','conditioning',{rounds:4,minutes:2},'Alterna lavoro e recupero.'),block('Forza complementare','strength',{sets:3,reps:'8-12'},'Scegli movimenti utili alla disciplina e all’attrezzatura disponibile.'),common.cooldown()];
function baseSession(activity){const s=String(activity?.slug||''),c=String(activity?.category||'');if(/gym|strength|hypertrophy|bodyweight|home-equipment|functional-training|cross-training/.test(s)||c==='strength'||c==='home')return strength();if(/running|trail-running/.test(s))return running();if(s==='hiking')return hiking();if(s==='stairs')return stairs();if(/football|futsal/.test(s))return football();if(s==='basketball')return basketball();if(s==='volleyball')return volleyball();if(/tennis|padel|badminton/.test(s))return racket();if(s==='table-tennis')return tableTennis();if(s==='swimming')return swimming();if(s==='aqua-fitness')return aqua();if(/cycling|mtb/.test(s))return cycling();if(s==='rowing')return rowing();if(s==='elliptical')return elliptical();if(s==='jump-rope')return jumpRope();if(s==='hiit')return hiit();if(s==='low-impact-circuit')return lowImpact();if(/mobility|stretching|yoga|pilates/.test(s))return mobility();if(/dance/.test(s)||c==='dance')return dance();if(/boxing|martial/.test(s)||c==='combat')return combat();if(s==='skiing')return skiing();if(s==='cross-country-ski')return crossCountrySki();if(s==='skating')return skating();if(s==='climbing')return climbing();if(s==='golf')return golf();if(s==='senior-fitness')return senior();if(s==='beginner-reconditioning')return reconditioning();if(s==='active-breaks')return activeBreaks();if(s==='daily-steps')return dailySteps();if(s==='breathing-relaxation')return breathing();if(c==='racket')return racket();if(c==='aquatic')return swimming();if(c==='cycling')return cycling();if(c==='mobility'||c==='mind-body')return mobility();return generic()}
function phaseName(week,total=4){const ratio=week/Math.max(1,total);if(week%4===0)return'Recupero e consolidamento';if(ratio<=.25)return'Adattamento e tecnica';if(ratio<=.65)return'Sviluppo specifico';if(ratio<=.9)return'Intensificazione';return'Prestazione e verifica'}
function periodize(blocks,activity,context={},index=0,week=1){const phase=phaseName(week,context.totalWeeks||4),technical=/Adattamento/.test(phase),peak=/Intensificazione|Prestazione/.test(phase),recovery=/Recupero/.test(phase),first=blocks[0],last=blocks[blocks.length-1],middle=blocks.slice(1,-1),variant=index%3;if(variant===1)middle.sort((a,b)=>Number(/conditioning|speed|endurance/.test(b.kind))-Number(/conditioning|speed|endurance/.test(a.kind)));if(variant===2)middle.sort((a,b)=>Number(/technique|skill|footwork/.test(b.kind))-Number(/technique|skill|footwork/.test(a.kind)));return[first,...middle,last].filter(Boolean).map((b,i)=>{const p={...(b.prescription||{}),phase,variant:variant+1,sport:activity?.slug||activity?.name};if(technical&&/technique|skill|footwork/.test(b.kind))p.quality='precisione prima della velocità';if(peak&&/conditioning|speed|strength/.test(b.kind))p.intensity_focus='alta qualità, recupero completo';if(recovery){for(const k of ['sets','rounds','reps','minutes','meters'])if(Number.isFinite(Number(p[k])))p[k]=Math.max(1,Math.round(Number(p[k])*.72));p.recovery_week=true}return{...b,title:i===0?`${phase} · ${b.title}`:b.title,prescription:p}})}
function session(activity,context={},index=0,week=1){return periodize(baseSession(activity),activity,context,index,week)}
window.PTPROSportLibrary={session,phaseName,periodize};
})();
