(() => {
'use strict';
const block=(title,kind,prescription,instructions)=>({title,kind,prescription,instructions});
const common={warmup:()=>block('Riscaldamento dinamico','warmup',{minutes:8},'Mobilità, attivazione e aumento progressivo della temperatura.'),cooldown:()=>block('Defaticamento e mobilità','cooldown',{minutes:6},'Respirazione, mobilità dolce e ritorno graduale alla calma.')};
const strength=()=>[common.warmup(),block('Squat / accosciata','strength',{sets:3,reps:'8-12',rir:2},'Tecnica controllata e range di movimento adatto.'),block('Spinta orizzontale','strength',{sets:3,reps:'8-12',rir:2},'Piegamenti, chest press o variante disponibile.'),block('Tirata orizzontale','strength',{sets:3,reps:'8-12',rir:2},'Rematore con elastico, manubrio o macchina.'),block('Hip hinge','strength',{sets:3,reps:'8-10',rir:2},'Stacco rumeno, kettlebell deadlift o variante educativa.'),block('Core anti-estensione','core',{sets:3,seconds:30},'Plank o variante mantenendo bacino neutro.'),common.cooldown()];
const running=()=>[common.warmup(),block('Tecnica di corsa','technique',{drills:['skip A','calciata','corsa balzata'],distance_m:20,rounds:2},'Qualità prima della velocità.'),block('Corsa facile','endurance',{minutes:25,rpe:4},'Ritmo conversazionale.'),block('Progressioni','speed',{reps:6,distance_m:80,recovery_s:60},'Accelera gradualmente senza sprint massimale.'),block('Core runner','core',{rounds:3},'Dead bug, side plank e ponte glutei.'),common.cooldown()];
const football=()=>[common.warmup(),block('Guida palla e cambi direzione','technique',{minutes:10},'Usa entrambi i piedi e varia ritmo.'),block('Passaggio e primo controllo','technique',{sets:4,reps:8},'Precisione, orientamento del corpo e ricezione aperta.'),block('1 contro 1 / finte','skill',{rounds:6,seconds:30},'Alterna attacco e recupero.'),block('RSA calcistico','conditioning',{sets:2,reps:5,distance_m:20,recovery_s:25},'Sprint submassimali, recupero completo tra i set.'),block('Prevenzione arti inferiori','strength',{sets:3},'Affondo, ponte glutei, polpacci e controllo monopodalico.'),common.cooldown()];
const basketball=()=>[common.warmup(),block('Ball handling','technique',{minutes:8},'Palleggio destro/sinistro, cambi mano e protezione palla.'),block('Passaggi in movimento','technique',{sets:4,reps:10},'Petto, schiacciato e baseball pass.'),block('Arresti, partenze e lay-up','skill',{rounds:5},'Alterna lato destro e sinistro.'),block('Agilità 5-10-5','conditioning',{reps:5,recovery_s:60},'Frena con controllo e riparti esplosivo.'),block('Forza elastica arti inferiori','strength',{sets:3,reps:'6-8'},'Squat jump controllato e atterraggi morbidi.'),common.cooldown()];
const volleyball=()=>[common.warmup(),block('Bagher e palleggio','technique',{sets:5,reps:12},'Piattaforma stabile e precisione.'),block('Servizio','skill',{sets:5,reps:6},'Routine costante e bersagli progressivi.'),block('Passi di rincorsa e stacco','technique',{sets:4,reps:5},'Coordina braccia e piedi senza ricerca massimale.'),block('Atterraggi e prevenzione','strength',{sets:3,reps:8},'Ginocchia allineate e assorbimento controllato.'),common.cooldown()];
const racket=()=>[common.warmup(),block('Split step e appoggi','footwork',{rounds:6,seconds:30},'Posizione pronta e passi rapidi.'),block('Fondamentale tecnico','technique',{sets:5,reps:10},'Alterna diritto/rovescio o gesto specifico della disciplina.'),block('Servizio / battuta','skill',{sets:5,reps:6},'Precisione prima della potenza.'),block('Navetta multidirezionale','conditioning',{sets:4,seconds:40,recovery_s:60},'Cambi direzione controllati.'),common.cooldown()];
const swimming=()=>[block('Attivazione a secco','warmup',{minutes:6},'Mobilità spalle, torace e caviglie.'),block('Tecnica nuotata','technique',{meters:400},'Drill di presa, allineamento e respirazione.'),block('Serie aerobica','endurance',{sets:6,meters:100,recovery_s:30},'Ritmo sostenibile e regolare.'),block('Serie velocità','speed',{sets:8,meters:25,recovery_s:35},'Alta qualità senza deteriorare la tecnica.'),block('Defaticamento','cooldown',{meters:200},'Nuotata facile e rilassata.')];
const cycling=()=>[common.warmup(),block('Cadenza tecnica','technique',{sets:4,minutes:3,rpm:'90-100'},'Pedalata fluida e stabile.'),block('Fondo aerobico','endurance',{minutes:35,rpe:4},'Intensità facile-moderata.'),block('Ripetute tempo','conditioning',{sets:4,minutes:4,recovery_min:2,rpe:7},'Mantieni cadenza e controllo.'),common.cooldown()];
const mobility=()=>[block('Respirazione e centratura','mind-body',{minutes:4},'Respirazione lenta e regolare.'),block('Mobilità colonna e anche','mobility',{rounds:2,reps:8},'Movimenti lenti e senza dolore.'),block('Mobilità spalle','mobility',{rounds:2,reps:8},'Controlla scapole e respirazione.'),block('Sequenza principale','mobility',{minutes:20},'Mantieni qualità del movimento e ampiezza confortevole.'),common.cooldown()];
const combat=()=>[common.warmup(),block('Guardia e spostamenti','technique',{rounds:4,minutes:2},'Assetto, distanza e ritorno in guardia.'),block('Combinazioni tecniche','skill',{rounds:5,minutes:2},'Esecuzione pulita, non massimale.'),block('Condizionamento a round','conditioning',{rounds:5,minutes:2,recovery_s:60},'Alterna lavoro tecnico e cardio.'),block('Core rotazionale','strength',{sets:3,reps:10},'Controllo del tronco e bacino stabile.'),common.cooldown()];
const generic=()=>[common.warmup(),block('Tecnica specifica','technique',{minutes:15},'Esegui i fondamentali della disciplina con qualità.'),block('Blocco principale','activity',{minutes:25,rpe:6},'Volume progressivo compatibile con il livello.'),block('Condizionamento generale','conditioning',{rounds:4,minutes:2},'Alterna lavoro e recupero.'),block('Forza complementare','strength',{sets:3,reps:'8-12'},'Scegli movimenti utili alla disciplina e all’attrezzatura disponibile.'),common.cooldown()];
function session(activity){const s=String(activity?.slug||''),c=String(activity?.category||'');if(/gym|strength|hypertrophy|bodyweight|home-equipment|functional|cross-training/.test(s)||c==='strength'||c==='home')return strength();if(/running|trail/.test(s))return running();if(/football|futsal/.test(s))return football();if(/basketball/.test(s))return basketball();if(/volleyball/.test(s))return volleyball();if(/tennis|padel|badminton|table-tennis/.test(s)||c==='racket')return racket();if(/swimming|aqua/.test(s)||c==='aquatic')return swimming();if(/cycling|mtb/.test(s)||c==='cycling')return cycling();if(/mobility|stretching|yoga|pilates|breathing/.test(s)||c==='mobility'||c==='mind-body')return mobility();if(/boxing|martial/.test(s)||c==='combat')return combat();return generic()}
window.PTPROSportLibrary={session};
})();