(() => {
'use strict';
const groups={
strength:[
['Squat','Fitness','Forza','Quadricipiti e glutei'],['Goblet squat','Palestra','Ipertrofia','Quadricipiti e glutei'],['Front squat','Palestra','Forza','Quadricipiti e core'],['Stacco rumeno','Palestra','Ipertrofia','Femorali e glutei'],['Hip thrust','Palestra','Ipertrofia','Glutei'],['Affondo avanti','Fitness','Forza','Gambe e glutei'],['Affondo laterale','Fitness','Mobilità attiva','Adduttori e glutei'],['Step-up','Fitness','Forza','Gambe e glutei'],['Calf raise','Fitness','Forza','Polpacci'],['Push-up','Corpo libero','Forza','Petto e tricipiti'],['Chest press','Palestra','Ipertrofia','Petto e tricipiti'],['Shoulder press','Palestra','Forza','Spalle e tricipiti'],['Alzata laterale','Palestra','Ipertrofia','Deltoidi'],['Rematore','Palestra','Ipertrofia','Dorsali e bicipiti'],['Lat machine','Palestra','Ipertrofia','Gran dorsale'],['Pulley','Palestra','Ipertrofia','Dorso'],['Curl bicipiti','Palestra','Ipertrofia','Bicipiti'],['Estensione tricipiti','Palestra','Ipertrofia','Tricipiti'],['Farmer carry','Functional','Forza','Presa e core'],['Kettlebell swing','Functional','Potenza','Catena posteriore'] ],
body:[
['Plank frontale','Corpo libero','Core','Addome'],['Plank laterale','Corpo libero','Core','Obliqui'],['Dead bug','Corpo libero','Stabilità','Core'],['Bird dog','Corpo libero','Stabilità','Core e schiena'],['Ponte glutei','Corpo libero','Forza','Glutei'],['Mountain climber','Corpo libero','Condizionamento','Core e anche'],['Burpee','Corpo libero','Condizionamento','Total body'],['Bear crawl','Corpo libero','Coordinazione','Total body'],['Superman','Corpo libero','Postura','Erettori spinali'],['Hollow hold','Corpo libero','Core','Addome'],['Dip su panca','Corpo libero','Forza','Tricipiti e petto'],['Inverted row','Corpo libero','Forza','Dorso e bicipiti'] ],
mobility:[
['Mobilità caviglia al muro','Mobilità','Mobilità','Caviglie'],['90/90 anche','Mobilità','Mobilità','Anche'],['Cat-cow','Mobilità','Mobilità','Colonna'],['Rotazione toracica','Mobilità','Mobilità','Colonna toracica'],['Wall slide','Mobilità','Postura','Spalle'],['Dislocazioni con elastico','Mobilità','Mobilità','Spalle'],['Stretch flessori anca','Mobilità','Recupero','Flessori anca'],['Mobilità ischiocrurali','Mobilità','Recupero','Femorali'],['Squat hold assistito','Mobilità','Mobilità','Anche e caviglie'],['Respirazione diaframmatica','Mobilità','Recupero','Diaframma e core'],['Scapular push-up','Mobilità','Postura','Scapole'],['CARS anca','Mobilità','Mobilità','Anche'] ],
rehab:[
['Sit to stand','Ripresa leggera','Autonomia','Gambe'],['Wall push-up','Ripresa leggera','Forza','Petto e braccia'],['Rematore elastico','Ripresa leggera','Postura','Dorso'],['Clamshell','Ripresa leggera','Stabilità','Gluteo medio'],['Terminal knee extension','Ripresa leggera','Controllo','Quadricipite'],['Equilibrio monopodalico','Ripresa leggera','Equilibrio','Caviglia e anca'],['Heel slide','Ripresa leggera','Mobilità','Ginocchio'],['External rotation elastico','Ripresa leggera','Stabilità','Cuffia rotatori'],['Pallof press','Ripresa leggera','Stabilità','Core'],['Camminata laterale elastico','Ripresa leggera','Stabilità','Gluteo medio'] ],
sport:[
['Skip A','Atletica','Tecnica','Anche e caviglie'],['Partenza sprint','Atletica','Velocità','Total body'],['Salto in lungo didattico','Atletica','Potenza','Gambe'],['Passaggio interno piede','Calcio','Tecnica','Gambe'],['Guida palla slalom','Calcio','Tecnica','Coordinazione'],['Tiro di collo','Calcio','Tecnica','Gambe'],['Palleggio controllato','Basket','Tecnica','Coordinazione'],['Passaggio petto','Basket','Tecnica','Braccia e core'],['Terzo tempo','Basket','Tecnica','Total body'],['Bagher','Pallavolo','Tecnica','Gambe e spalle'],['Palleggio pallavolo','Pallavolo','Tecnica','Spalle e gambe'],['Servizio dal basso','Pallavolo','Tecnica','Spalle'],['Diritto base','Tennis e Padel','Tecnica','Total body'],['Rovescio base','Tennis e Padel','Tecnica','Total body'],['Servizio tennis','Tennis e Padel','Tecnica','Spalle e core'],['Bracciata stile libero a secco','Nuoto','Tecnica','Spalle e dorsali'],['Battuta gambe a secco','Nuoto','Tecnica','Anche e core'],['Pedalata agile','Ciclismo','Resistenza','Gambe'],['Posizione in sella','Ciclismo','Tecnica','Core e schiena'],['Jab e guardia','Boxe fitness','Tecnica','Spalle e core'],['Diretto-cross','Boxe fitness','Tecnica','Total body'],['Vogata tecnica','Canottaggio','Tecnica','Gambe e dorso'],['Appoggio piedi','Arrampicata','Tecnica','Piedi e gambe'],['Passo laterale ritmico','Danza','Coordinazione','Total body'],['Passaggio rugby','Rugby','Tecnica','Braccia e core'],['Lancio rovescio disco','Ultimate','Tecnica','Spalle e core'] ]
};
const variants=[
 {suffix:'base',level:'Principiante',equipment:'Nessuna o supporto',location:'Casa',tempo:'2-1-2'},
 {suffix:'assistito',level:'Principiante',equipment:'Elastico o supporto',location:'Casa o palestra',tempo:'3-1-2'},
 {suffix:'controllato',level:'Intermedio',equipment:'Attrezzatura leggera',location:'Palestra o campo',tempo:'3-1-3'},
 {suffix:'progressione',level:'Avanzato',equipment:'Attrezzatura specifica',location:'Palestra o campo',tempo:'Esplosivo controllato'}
];
const categoryNames={strength:'Forza e palestra',body:'Corpo libero',mobility:'Mobilità',rehab:'Ripresa leggera',sport:'Sport'};
const imageIndex={strength:0,body:5,mobility:14,rehab:12,sport:8};
const slug=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const exercises=[];
Object.entries(groups).forEach(([category,items])=>items.forEach((b,bi)=>variants.forEach((v,vi)=>{
 const isSport=category==='sport',name=`${b[0]} · ${v.suffix}`,idx=(imageIndex[category]+bi+vi)%16;
 exercises.push({id:`catalog-${slug(b[0])}-${vi+1}`,name,sport:b[1],category:categoryNames[category],goal:b[2],level:v.level,muscle_group:b[3],equipment:isSport?(vi<2?'Attrezzatura dello sport':v.equipment):v.equipment,location:isSport?'Campo o palestra':v.location,image_url:'/assets/exercise-guides/pro-movement-test-atlas.webp',image_x:idx%4,image_y:Math.floor(idx/4),breathing:isSport?'Respira in modo continuo; espira nella fase di maggiore sforzo.':'Inspira nella preparazione, espira nella fase attiva senza trattenere il respiro.',steps:[`Prepara spazio e attrezzatura per ${b[0].toLowerCase()}.`,`Assumi una posizione stabile e allinea le articolazioni.`,`Esegui la fase principale con ritmo ${v.tempo}.`,`Ritorna sotto controllo e ripeti mantenendo la qualità.`],errors:['Accelerare perdendo la posizione','Compensare con schiena o spalle','Usare un carico o una difficoltà non adeguati'],cue:`Qualità prima della velocità: ${b[3].toLowerCase()} attivi.`,safety:category==='rehab'?'Movimento leggero e senza dolore; in caso di infortunio segui le indicazioni del professionista sanitario.':'Interrompi in caso di dolore anomalo e scegli la variante più semplice.',alternatives:[]});
})));
const byFamily=new Map();exercises.forEach(x=>{const k=x.id.replace(/-\d+$/,'');if(!byFamily.has(k))byFamily.set(k,[]);byFamily.get(k).push(x.id)});exercises.forEach(x=>x.alternatives=(byFamily.get(x.id.replace(/-\d+$/,''))||[]).filter(id=>id!==x.id));
window.PTPROUniversalCatalog={exercises,filters:{sport:[...new Set(exercises.map(x=>x.sport))],goal:[...new Set(exercises.map(x=>x.goal))],level:[...new Set(exercises.map(x=>x.level))],muscle:[...new Set(exercises.map(x=>x.muscle_group))],equipment:[...new Set(exercises.map(x=>x.equipment))],location:[...new Set(exercises.map(x=>x.location))]},byId:id=>exercises.find(x=>x.id===id)};
})();
