(() => {
'use strict';
const A=window.PTAPP;if(!A)return;const {api,state,esc,modal,toast,go}=A;
const currentId=()=>state.view==='wellness'&&document.querySelector('.eyebrow')?.textContent.includes('SCHEDA SPORTIVA')?state.routeArgs?.[0]:null;
async function rename(id){const rows=await api.get('wellness_programs',{select:'id,title',id:`eq.${id}`,limit:1}),program=rows[0];if(!program)return toast('Scheda non disponibile','err');const m=modal('Modifica scheda',`<label>Nome della routine<input id="wmTitle" value="${esc(program.title)}"></label><p class="muted">La routine è già salvata nel Cloud. Puoi rinominarla senza perdere giornate o attività completate.</p><button class="btn primary full" id="wmSave">Salva modifiche</button>`);m.querySelector('#wmSave').onclick=async()=>{const title=m.querySelector('#wmTitle').value.trim();if(!title)return toast('Inserisci un nome per la scheda','err');await api.patch('wellness_programs',{id:`eq.${id}`},{title});m.remove();toast('Scheda aggiornata e salvata ✓');go('wellness-program',id)}}
async function archive(id){if(!confirm('Archiviare questa scheda? Potrai continuare a conservare lo storico delle attività già registrate.'))return;await api.patch('wellness_programs',{id:`eq.${id}`},{active:false,status:'archived'});toast('Scheda archiviata ✓');go('wellness')}
function enhance(){const id=currentId(),head=document.querySelector('.sectionHead .manageButtons');if(!id||!head||head.querySelector('[data-wellness-manage]'))return;const saved=document.createElement('span');saved.className='plannerStatus completata';saved.textContent='☁ Salvata';saved.dataset.wellnessManage='1';const edit=document.createElement('button');edit.className='btn secondary';edit.textContent='Rinomina';edit.onclick=()=>rename(id);const archiveButton=document.createElement('button');archiveButton.className='btn secondary';archiveButton.textContent='Archivia';archiveButton.onclick=()=>archive(id);head.prepend(saved,edit,archiveButton)}
new MutationObserver(enhance).observe(document.getElementById('app'),{childList:true,subtree:true});enhance();
})();
