(() => {
'use strict';
const A=window.PTAPP;if(!A)return;const {api,state,esc,modal,toast,go}=A;
const currentId=()=>state.view==='wellness'&&document.querySelector('.eyebrow')?.textContent.includes('SCHEDA SPORTIVA')?state.routeArgs?.[0]:null;
async function rename(id){const rows=await api.get('wellness_programs',{select:'id,title',id:`eq.${id}`,limit:1}),program=rows[0];if(!program)return toast('Scheda non disponibile','err');const m=modal('Modifica scheda',`<label>Nome della routine<input id="wmTitle" value="${esc(program.title)}"></label><p class="muted">La routine è già salvata nel Cloud. Puoi rinominarla senza perdere giornate o attività completate.</p><button class="btn primary full" id="wmSave">Salva modifiche</button>`);m.querySelector('#wmSave').onclick=async()=>{const title=m.querySelector('#wmTitle').value.trim();if(!title)return toast('Inserisci un nome per la scheda','err');await api.patch('wellness_programs',{id:`eq.${id}`},{title});m.remove();toast('Scheda aggiornata e salvata ✓');go('wellness-program',id)}}
async function archive(id){if(!confirm('Archiviare questa scheda? Potrai continuare a conservare lo storico delle attività già registrate.'))return;await api.patch('wellness_programs',{id:`eq.${id}`},{active:false,status:'archived'});toast('Scheda archiviata ✓');go('wellness')}
const datePlus=(iso,days)=>{const d=new Date(`${iso}T12:00:00`);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};
async function snapshot(id){const program=(await api.get('wellness_programs',{select:'*',id:`eq.${id}`,limit:1}))[0],days=await api.get('wellness_program_days',{select:'*',program_id:`eq.${id}`,order:'sort_order.asc'});for(const d of days)d.items=await api.get('wellness_program_items',{select:'*',program_day_id:`eq.${d.id}`,order:'sort_order.asc'});return{program,days}}
async function duplicate(id){const s=await snapshot(id);if(!s.program)return toast('Programma non disponibile','err');A.loading('Duplico il programma…');const old=s.program,{id:ignore,created_at,updated_at,...base}=old,program=(await api.post('wellness_programs',{...base,athlete_id:state.boot.uid,created_by:state.boot.uid,title:`${old.title} · Copia`,status:'draft',active:false,starts_on:null,ends_on:null,generation_context:{...(old.generation_context||{}),duplicated_from:id}}))?.[0];if(!program)throw Error('Duplicazione non riuscita');const dayPayloads=s.days.map(d=>({program_id:program.id,athlete_id:state.boot.uid,week_index:d.week_index,day_index:d.day_index,day_name:d.day_name,focus:d.focus,planned_date:null,sort_order:d.sort_order,notes:d.notes})),newDays=await api.post('wellness_program_days',dayPayloads),byOrder=new Map(newDays.map(d=>[d.sort_order,d])),items=[];for(const d of s.days){const nd=byOrder.get(d.sort_order);if(!nd)continue;for(const x of d.items||[])items.push({program_day_id:nd.id,athlete_id:state.boot.uid,activity_id:x.activity_id,item_type:x.item_type,title:x.title,instructions:x.instructions,prescription:x.prescription,target_intensity:x.target_intensity,target_rpe:x.target_rpe,duration_minutes:x.duration_minutes,distance_km:x.distance_km,steps_target:x.steps_target,sort_order:x.sort_order,optional:x.optional})}if(items.length)await api.post('wellness_program_items',items);toast('Programma duplicato ✓');go('wellness-program',program.id)}
async function activate(id){await api.patch('wellness_programs',{athlete_id:`eq.${state.boot.uid}`,active:'eq.true'},{active:false});await api.patch('wellness_programs',{id:`eq.${id}`},{active:true,status:'active'});await A.refresh();toast('Programma impostato come principale ✓');go('wellness-program',id)}
async function reschedule(id){const s=await snapshot(id),m=modal('Pianifica nel calendario',`<label>Nuova data di inizio<input id="wmStart" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Ora abituale<input id="wmTime" type="time" value="18:00"></label><p class="muted">Le giornate verranno ridistribuite mantenendo settimane, ordine e recuperi.</p><button class="btn primary full" id="wmSchedule">Aggiorna programma e calendario</button>`);m.querySelector('#wmSchedule').onclick=async()=>{const start=m.querySelector('#wmStart').value,time=m.querySelector('#wmTime').value;if(!start)return toast('Scegli una data','err');const days=s.days||[],end=datePlus(start,Math.max(0,(s.program.weeks||4)*7-1));m.remove();A.loading('Aggiorno il calendario…');for(let i=0;i<days.length;i+=12)await Promise.all(days.slice(i,i+12).map((d,j)=>{const offset=(d.week_index-1)*7+Math.round((d.day_index-1)*7/Math.max(1,s.program.days_per_week||3)),planned=datePlus(start,offset);d.planned_date=planned;return api.patch('wellness_program_days',{id:`eq.${d.id}`},{planned_date:planned})}));await api.patch('wellness_programs',{id:`eq.${id}`},{starts_on:start,ends_on:end,status:'active'});const existing=await api.get('calendar_events',{select:'id',athlete_id:`eq.${state.boot.uid}`,related_plan_id:`eq.${id}`,event_type:'eq.wellness-plan',limit:500}).catch(()=>[]);for(const e of existing)await api.del('calendar_events',{id:`eq.${e.id}`}).catch(()=>{});const events=days.map(d=>({athlete_id:state.boot.uid,title:`${s.program.title} · ${d.day_name}`,starts_at:new Date(`${d.planned_date}T${time}:00`).toISOString(),event_type:'wellness-plan',related_plan_id:id,notes:d.focus||''}));if(events.length)await api.post('calendar_events',events).catch(()=>[]);toast('Programma pianificato nel calendario ✓');go('wellness-program',id)}}
function enhance(){const id=currentId(),head=document.querySelector('.sectionHead .manageButtons');if(!id||!head||head.querySelector('[data-wellness-manage]'))return;const saved=document.createElement('span');saved.className='plannerStatus completata';saved.textContent='☁ Salvata';saved.dataset.wellnessManage='1';const controls=[['Rinomina',()=>rename(id)],['Duplica',()=>duplicate(id)],['Rendi principale',()=>activate(id)],['Pianifica',()=>reschedule(id)],['Archivia',()=>archive(id)]];for(const [label,action] of controls){const b=document.createElement('button');b.className='btn secondary';b.textContent=label;b.onclick=action;head.prepend(b)}head.prepend(saved)}
A.register('wellness-archive',async()=>{state.view='wellness';A.loading('Carico programmi archiviati…');const rows=await api.get('wellness_programs',{select:'*',athlete_id:`eq.${state.boot.uid}`,status:'eq.archived',order:'created_at.desc',limit:100}).catch(()=>[]);A.shell(`<div class="sectionHead"><div><div class="eyebrow">ARCHIVIO WELLNESS</div><h1>Programmi archiviati</h1><span class="muted">Conservano struttura e storico delle attività.</span></div><button class="btn secondary" data-route="wellness">← Programmi attivi</button></div><div class="dayGrid">${rows.map(x=>`<div class="dayCard"><div><b>${esc(x.title)}</b><span>${x.weeks||4} settimane · ${x.days_per_week||3} giorni</span></div><button class="btn primary" data-restore-program="${x.id}">Ripristina</button></div>`).join('')||'<div class="card empty">Nessun programma archiviato.</div>'}</div>`);A.bindRoutes();document.querySelectorAll('[data-restore-program]').forEach(b=>b.onclick=async()=>{await api.patch('wellness_programs',{id:`eq.${b.dataset.restoreProgram}`},{status:'active',active:false});toast('Programma ripristinato ✓');go('wellness')})});
function enhanceList(){if(state.view!=='wellness'||document.querySelector('[data-wellness-archive]')||document.querySelector('.eyebrow')?.textContent.includes('SCHEDA SPORTIVA'))return;const head=[...document.querySelectorAll('.sectionHead')].find(x=>x.querySelector('h1')?.textContent==='Wellness & Sport');if(!head)return;const b=document.createElement('button');b.className='btn secondary';b.dataset.wellnessArchive='1';b.dataset.route='wellness-archive';b.textContent='Archivio';head.appendChild(b);A.bindRoutes(head)}
const observe=()=>{enhance();enhanceList()};new MutationObserver(observe).observe(document.getElementById('app'),{childList:true});observe();
})();
