(() => {
'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const ageFromBirth=b=>{if(!b)return null;const d=new Date(b),n=new Date();let a=n.getFullYear()-d.getFullYear();if(n.getMonth()<d.getMonth()||(n.getMonth()===d.getMonth()&&n.getDate()<d.getDate()))a--;return a>0&&a<120?a:null};
function ageBand(age){if(age==null)return 'adult';if(age<14)return 'child';if(age<18)return 'teen';if(age<40)return 'adult';if(age<60)return 'midlife';if(age<75)return 'senior';return 'older'}
function modifiers({age,level='beginner',goal='wellness'}){const band=ageBand(age);let volume=1,intensity=1,recovery=1;if(level==='beginner'){volume*=.75;intensity*=.85;recovery*=1.15}else if(level==='advanced'){volume*=1.12;intensity*=1.05}if(band==='child'){volume*=.7;intensity*=.75;recovery*=1.2}else if(band==='teen'){volume*=.85;intensity*=.9}else if(band==='midlife'){recovery*=1.08}else if(band==='senior'){volume*=.78;intensity*=.82;recovery*=1.25}else if(band==='older'){volume*=.62;intensity*=.72;recovery*=1.4}if(goal==='weight_loss')volume*=1.05;if(goal==='strength')intensity*=1.06;if(goal==='recovery'){volume*=.7;intensity*=.72;recovery*=1.3}if(goal==='wellness'){intensity*=.9}return {band,volume:clamp(volume,.5,1.3),intensity:clamp(intensity,.6,1.15),recovery:clamp(recovery,.9,1.6)}}
function sessionMinutes(base,ctx){const m=modifiers(ctx);return Math.max(10,Math.round((Number(base)||45)*m.volume/5)*5)}
function targetRpe(ctx){const m=modifiers(ctx),base=ctx.goal==='performance'?7:ctx.goal==='strength'?7:ctx.goal==='recovery'?4:6;return clamp(Math.round(base*m.intensity),3,8)}
function walking(ctx){const mins=sessionMinutes(ctx.minutes,ctx),rpe=targetRpe(ctx),steps=Math.round((ctx.level==='beginner'?5500:7500)*modifiers(ctx).volume/500)*500;return {minutes:mins,rpe,steps,intensity:rpe<=4?'low':'moderate',prescription:{steps,pace:rpe<=4?'facile/conversazionale':'sostenuto ma controllato'}}}
function running(ctx){const mins=sessionMinutes(ctx.minutes,ctx),rpe=targetRpe(ctx);return {minutes:mins,rpe,intensity:rpe>=7?'high':rpe>=5?'moderate':'low',prescription:{structure:ctx.level==='beginner'?'corsa/cammino alternati':'corsa continua o intervalli controllati',rpe}}}
function strength(ctx){const m=modifiers(ctx),sets=clamp(Math.round((ctx.level==='beginner'?2:3)*m.volume),1,4),rpe=targetRpe(ctx);return {minutes:sessionMinutes(ctx.minutes,ctx),rpe,intensity:rpe>=7?'high':'moderate',prescription:{sets,reps:ctx.goal==='strength'?'5-8':'8-12',rir:ctx.level==='beginner'||m.band==='senior'||m.band==='older'?3:2}}}
function mobility(ctx){return {minutes:Math.min(45,sessionMinutes(ctx.minutes,ctx)),rpe:3,intensity:'low',prescription:{quality:'controllata',breathing:true}}}
function teamSport(ctx){const rpe=targetRpe(ctx);return {minutes:sessionMinutes(ctx.minutes,ctx),rpe,intensity:rpe>=7?'high':'moderate',prescription:{technical_block:true,conditioning_block:true,rpe}}}
function generic(ctx){const rpe=targetRpe(ctx);return {minutes:sessionMinutes(ctx.minutes,ctx),rpe,intensity:rpe>=7?'high':rpe>=5?'moderate':'low',prescription:{progression:'graduale',rpe}}}
function prescribe(activity,context={}){const slug=String(activity?.slug||''),ctx={...context,age:context.age??ageFromBirth(context.birthDate)};let out;if(/walking|daily-steps|hiking/.test(slug))out=walking(ctx);else if(/running|trail/.test(slug))out=running(ctx);else if(/gym|strength|hypertrophy|bodyweight|home-equipment/.test(slug))out=strength(ctx);else if(/mobility|stretching|yoga|pilates|breathing/.test(slug))out=mobility(ctx);else if(/football|futsal|basketball|volleyball|tennis|padel|badminton/.test(slug))out=teamSport(ctx);else out=generic(ctx);return {...out,ageBand:ageBand(ctx.age),modifiers:modifiers(ctx)}}
function safeguards(context={}){const age=context.age??ageFromBirth(context.birthDate),band=ageBand(age),notes=[];if(band==='child'||band==='teen')notes.push('Priorità a tecnica, varietà e progressione graduale; evitare massimali non supervisionati.');if(band==='senior'||band==='older')notes.push('Progressione conservativa, recuperi più ampi e priorità a forza funzionale, equilibrio e mobilità.');if(context.goal==='recovery')notes.push('Il percorso è di ricondizionamento generale e non sostituisce indicazioni cliniche o riabilitative.');return notes}
window.PTPROWellnessEngine={ageFromBirth,ageBand,modifiers,prescribe,safeguards};
})();