(() => {
'use strict';
const A=window.PTAPP;
if(!A||!window.PTPROWellnessEngine)return;
const {api,state,esc,fmt,shell,loading,toast,modal,go,today}=A;
const E=window.PTPROWellnessEngine;
const uid=()=>state.boot?.uid;
const goals={weight_loss:'Dimagrimento',maintenance:'Mantenimento',muscle_gain:'Massa muscolare',strength:'Forza',fitness:'Forma fisica',endurance:'Resistenza',performance:'Performance sportiva',mobility:'Mobilità',recovery:'Recupero / ripresa',wellness:'Benessere generale'};
const goalName=k=>goals[k]||k||'Benessere generale';
const n=v=>Number.isFinite(Number(v))?Number(v):null;
const datePlus=(iso,days)=>{const d=new Date(`${iso}T12:00:00`);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
async function activities(){return api.get('activities',{select:'*',active:'eq.true',order:'category.asc,name.asc',limit:300}).catch(()=>[])}
async function activityProfile(){const r=await api.get('user_activity_profiles',{select:'*',athlete_id:`eq.${uid()}`,limit:1}).catch(()=>[]);return r[0]||null}
async function activeProgram(){const r=await api.get('wellness_programs',{select:'*',athlete_id:`eq.${uid()}`,active:'eq.true',order:'created_at.desc',limit:1}).catch(()=>[]);return r[0]||null}
async function recentLogs(limit=12){return api.get('activity_logs',{select:'*',athlete_id:`eq.${uid()}`,order:'started_at.desc',limit}).catch(()=>[])}
function readinessFactor(){const r=typeof A.readiness==='function'?A.readiness():70;return r<50?.78:r<65?.9:r>84?1.05:1}
function buildSession(activity,ctx,index,week){const base=E.prescribe(activity,ctx),rf=readinessFactor(),progress=1+Math.min(.12,(week-1)*.04),deload=week===4?.92:1;let minutes=Math.max(10,Math.round((base.minutes||ctx.minutes||45)*rf*deload/5)*5),rpe=clamp(Math.round((base.rpe||6)*(rf<1?rf:1)*10)/10,3,8),steps=base.steps?Math.round(base.steps*progress*deload/500)*500:null;const prescription={...(base.prescription||{}),week,progression_factor:+(progress*deload).toFixed(2),readiness_factor:rf};let title=activity.name,focus=goalName(ctx.goal);const slug=String(activity.slug||'');if(/walking|daily-steps|hiking/.test(slug))title=index%2?'Camminata facile':'Camminata attiva';else if(/running|trail/.test(slug))title=index%3===1?'Corsa + progressioni':index%3===2?'Recupero attivo':'Corsa facile';else if(/gym|strength|hypertrophy|bodyweight|home-equipment/.test(slug))title=`Forza / Full Body ${index%2?'B':'A'}`;else if(/mobility|stretching|yoga|pilates|breathing/.test(slug))title=`${activity.name} · Routine ${index+1}`;else if(/football|futsal|basketball|volleyball|tennis|padel|badminton/.test(slug))title=index%2?`${activity.name} · Condizionamento`:`${activity.name} · Tecnica`;const safeguards=E.safeguards(ctx);return {focus,title,type:'activity',minutes,rpe,steps,intensity:base.intensity||'moderate',prescription,instructions:[`Sessione adattata a livello, età, obiettivo e recupero corrente.`,...safeguards,'Interrompi in caso di dolore anomalo o sintomi non abituali.'].join(' ')} }
async function generateProgram(){const [list,p]=await Promise.all([activities(),activityProfile()]);if(!p?.primary_activity_id)return toast('Completa prima Il mio percorso','err');const primary=list.find(x=>x.id===p.primary_activity_id);if(!primary)return toast('Attività principale non trovata','err');const profile=state.boot?.profile||{},days=clamp(+p.available_days||3,1,7),minutes=Math.max(10,+p.session_minutes||45),goal=p.main_goal||'wellness',start=today(),birthDate=profile.birth_date||null,age=E.ageFromBirth(birthDate),ctx={birthDate,age,level:p.experience_level||'beginner',goal,minutes,locations:p.locations||[],equipment:p.equipment||[]};loading('Genero il programma PT-PRO 11…');await api.patch('wellness_programs',{athlete_id:`eq.${uid()}`,active:'eq.true'},{active:false,status:'archived'}).catch(()=>[]);const end=datePlus(start,27);const created=await api.post('wellness_programs',{athlete_id:uid(),created_by:uid(),title:`${primary.name} · ${goalName(goal)}`,goal,status:'active',starts_on:start,ends_on:end,weeks:4,days_per_week:days,activity_mix:[{activity_id:primary.id,weight:1}],generation_context:{...ctx,age_band:E.ageBand(age),engine:'PTPROWellnessEngine',readiness:A.readiness?.()??null},notes:E.safeguards(ctx).join(' '),active:true});const prog=created?.[0];if(!prog)throw Error('Creazione programma non riuscita');for(let w=1;w<=4;w++){for(let i=0;i<days;i++){const x=buildSession(primary,ctx,i,w),planned=datePlus(start,(w-1)*7+Math.round(i*7/days));const dr=await api.post('wellness_program_days',{program_id:prog.id,athlete_id:uid(),week_index:w,day_index:i+1,day_name:`Settimana ${w} · Giorno ${i+1}`,focus:x.focus,planned_date:planned,sort_order:(w-1)*days+i+1});const d=dr?.[0];if(!d)continue;await api.post('wellness_program_items',{program_day_id:d.id,athlete_id:uid(),activity_id:primary.id,item_type:x.type,title:x.title,instructions:x.instructions,prescription:x.prescription,target_intensity:x.intensity,target_rpe:x.rpe,duration_minutes:x.minutes,steps_target:x.steps||null,sort_order:1})}}
toast('Programma di 4 settimane creato ✓');go('wellness-program',prog.id)}
function metricRow(log){const bits=[];if(log.duration_minutes)bits.push(`${log.duration_minutes} min`);if(log.distance_km)bits.push(`${fmt(log.distance_km,1)} km`);if(log.steps)bits.push(`${fmt(log.steps,0)} passi`);if(log.rpe)bits.push(`RPE ${fmt(log.rpe,1)}`);return bits.join(' · ')||'Attività registrata'}
A.register('wellness',async()=>{state.view='wellness';loading('Carico Wellness & Sport…');const [list,p,prog,logs]=await Promise.all([activities(),activityProfile(),activeProgram(),recentLogs(8)]),primary=list.find(x=>x.id===p?.primary_activity_id),mins=logs.reduce((s,x)=>s+(n(x.duration_minutes)||0),0),steps=logs.reduce((s,x)=>s+(n(x.steps)||0),0);shell(`<div class="sectionHead wellnessHeroHead"><div><div class="eyebrow">PT-PRO 11</div><h1>Wellness & Sport</h1><span class="muted">Allenamento, sport e benessere in un unico percorso adattivo.</span></div><button class="btn primary" data-route="onboarding">Personalizza</button></div><div class="kpis four"><div class="kpi"><b>${esc(primary?.icon||'✨')} ${esc(primary?.name||'Da scegliere')}</b><span>Attività principale</span></div><div class="kpi"><b>${esc(goalName(p?.main_goal))}</b><span>Obiettivo</span></div><div class="kpi"><b>${logs.length}</b><span>Attività recenti</span></div><div class="kpi"><b>${fmt(mins,0)}′</b><span>Minuti registrati</span></div></div>${prog?`<section class="section"><div class="card"><div class="sectionHead"><div><div class="eyebrow">PROGRAMMA ATTIVO</div><h2>${esc(prog.title)}</h2><span class="muted">${prog.weeks||4} settimane · ${prog.days_per_week||3} giorni/settimana</span></div><button class="btn secondary" id="openActiveProgram">Apri</button></div></div></section>`:''}<section class="section"><div class="sectionHead"><h2>Riepilogo attività</h2><span class="muted">${steps?fmt(steps,0)+' passi registrati':''}</span></div><div class="card list">${logs.map(x=>`<div class="row"><span><b>${new Date(x.started_at).toLocaleDateString('it-IT')}</b><small>${esc(metricRow(x))}</small></span><b>${x.enjoyment?`☺ ${fmt(x.enjoyment,0)}`:'✓'}</b></div>`).join('')||'<div class="empty">Nessuna attività registrata ancora.</div>'}</div></section><section class="section"><button class="btn primary full" id="generateWellness">✨ Genera / rigenera programma personalizzato</button></section>`);A.bindRoutes();document.getElementById('generateWellness').onclick=generateProgram;if(prog)document.getElementById('openActiveProgram').onclick=()=>go('wellness-program',prog.id)});
async function logActivity(item,program){const box=modal('Completa attività',`<div class="formGrid"><label class="field">Minuti<input id="wlMin" type="number" min="1" max="600" value="${item.duration_minutes||45}"></label><label class="field">RPE 1–10<input id="wlRpe" type="number" min="1" max="10" step="1" value="${item.target_rpe||6}"></label><label class="field">Passi<input id="wlSteps" type="number" min="0" step="100" value="${item.steps_target||''}"></label><label class="field">Distanza km<input id="wlKm" type="number" min="0" step="0.1"></label><label class="field">Piacere 1–5<input id="wlEnjoy" type="number" min="1" max="5" value="4"></label><label class="field">Dolore 0–10<input id="wlPain" type="number" min="0" max="10" value="0"></label></div><label class="field">Note<textarea id="wlNotes" placeholder="Come è andata?"></textarea></label><button class="btn primary full" id="wlSave">Salva attività</button>`);box.querySelector('#wlSave').onclick=async()=>{const started=new Date(),mins=Math.max(1,+box.querySelector('#wlMin').value||item.duration_minutes||45),ended=new Date(started.getTime()+mins*60000),payload={athlete_id:uid(),activity_id:item.activity_id||null,program_item_id:item.id,started_at:started.toISOString(),ended_at:ended.toISOString(),duration_minutes:mins,distance_km:n(box.querySelector('#wlKm').value),steps:n(box.querySelector('#wlSteps').value),rpe:n(box.querySelector('#wlRpe').value),enjoyment:n(box.querySelector('#wlEnjoy').value),pain:n(box.querySelector('#wlPain').value),metrics:{source:'ptpro11_program',program_id:program.id},notes:box.querySelector('#wlNotes').value||null};await api.post('activity_logs',payload);await api.post('calendar_events',{athlete_id:uid(),title:`Attività · ${item.title}`,starts_at:payload.started_at,ends_at:payload.ended_at,all_day:false,event_type:'wellness',notes:`wellness:${item.id}`}).catch(()=>[]);box.remove();toast('Attività registrata ✓');await A.refresh();go('wellness-program',program.id)}}
A.register('wellness-program',async programId=>{state.view='wellness';loading('Carico programma…');let p=null;if(programId){const r=await api.get('wellness_programs',{select:'*',id:`eq.${programId}`,limit:1}).catch(()=>[]);p=r[0]||null}else p=await activeProgram();if(!p)return shell('<div class="card empty">Nessun programma Wellness attivo. Creane uno dalla sezione Wellness & Sport.</div>');const [days,logs]=await Promise.all([api.get('wellness_program_days',{select:'*',program_id:`eq.${p.id}`,order:'sort_order.asc'}),recentLogs(200)]);for(const d of days)d.items=await api.get('wellness_program_items',{select:'*',program_day_id:`eq.${d.id}`,order:'sort_order.asc'});const completed=new Set(logs.map(x=>x.program_item_id).filter(Boolean));shell(`<div class="sectionHead"><div><div class="eyebrow">PROGRAMMA WELLNESS</div><h1>${esc(p.title)}</h1><span class="muted">${p.weeks||4} settimane · ${p.days_per_week||3} giorni/settimana</span></div><button class="btn secondary" data-route="wellness">Riepilogo</button></div><div class="builderDays">${days.map(d=>`<div class="card builderDay"><div class="sectionHead"><div><b>${esc(d.day_name)}</b><span class="muted">${d.planned_date?new Date(`${d.planned_date}T12:00:00`).toLocaleDateString('it-IT')+' · ':''}${esc(d.focus||'')}</span></div></div>${d.items.map(x=>`<div class="proInsight wellnessPlanItem"><div><b>${completed.has(x.id)?'✓ ':''}${esc(x.title)}</b><span>${x.duration_minutes?x.duration_minutes+' min · ':''}${esc(x.target_intensity||'')}${x.target_rpe?' · RPE '+fmt(x.target_rpe,1):''}</span><small>${esc(x.instructions||'')}</small></div><button class="btn ${completed.has(x.id)?'secondary':'primary'}" data-log-item="${x.id}" ${completed.has(x.id)?'disabled':''}>${completed.has(x.id)?'Fatto':'Completa'}</button></div>`).join('')}</div>`).join('')}</div>`);A.bindRoutes();document.querySelectorAll('[data-log-item]').forEach(b=>b.onclick=()=>{const item=days.flatMap(d=>d.items).find(x=>x.id===b.dataset.logItem);if(item)logActivity(item,p)})});
})();